In [1]:
import pandas as pd
import os
import re

In [2]:
DIRECTORY = "./GA_Results_Prim_26/"

In [3]:
# combined_contests = []

# for file in os.listdir(DIRECTORY):
#     temp = pd.read_excel(DIRECTORY+file, sheet_name = "Precinct Results")
#     temp["County"] = file[:-5].title()
#     combined_contests.append(temp)
    
# full_election = pd.concat(combined_contests)
# full_election.to_csv("./full_election.csv",index = False)

In [4]:
full_election=pd.read_csv("./full_election.csv",)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_19335/2841068978.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  full_election=pd.read_csv("./full_election.csv",)

In [5]:
full_election["County"] = full_election["County"].map({'Ben-Hill':'Ben Hill',
'Dekalb':'DeKalb',
'Jeff-Davis':'Jeff Davis',
'Mcduffie':'McDuffie',
'Mcintosh':'McIntosh'}).fillna(full_election["County"])

In [6]:
full_election["County"].unique()

array(['Glynn', 'Habersham', 'Dooly', 'Baldwin', 'Houston', 'Wheeler',
       'Bryan', 'Emanuel', 'Brantley', 'Fulton', 'Union', 'Jackson',
       'Pulaski', 'Terrell', 'Webster', 'Putnam', 'Jasper', 'Jenkins',
       'Murray', 'Glascock', 'Jefferson', 'Randolph', 'Gilmer', 'Johnson',
       'Decatur', 'DeKalb', 'Lowndes', 'Elbert', 'Hancock', 'Catoosa',
       'Calhoun', 'Walker', 'Meriwether', 'Banks', 'Fannin', 'Lincoln',
       'Tattnall', 'Sumter', 'Jeff Davis', 'Rabun', 'Colquitt', 'Camden',
       'Upson', 'Oglethorpe', 'Schley', 'Laurens', 'Forsyth', 'Wayne',
       'Thomas', 'Turner', 'Gwinnett', 'Grady', 'Warren', 'Bacon',
       'Telfair', 'Clayton', 'Ware', 'Long', 'Dade', 'Madison', 'Wilcox',
       'Chattahoochee', 'Berrien', 'Worth', 'Harris', 'Carroll', 'Baker',
       'Clarke', 'Chatham', 'Mitchell', 'Fayette', 'Butts', 'Charlton',
       'Toombs', 'Troup', 'Taliaferro', 'Whitfield', 'Early', 'Appling',
       'Polk', 'McIntosh', 'Seminole', 'White', 'Peach', 'Tift', 'Evans',
       'Monroe', 'Treutlen', 'Cobb', 'Chattooga', 'Floyd', 'Marion',
       'Talbot', 'Jones', 'Quitman', 'Coweta', 'Haralson', 'Stewart',
       'Pike', 'Bleckley', 'McDuffie', 'Pierce', 'Paulding', 'Walton',
       'Newton', 'Crisp', 'Stephens', 'Cook', 'Morgan', 'Brooks',
       'Washington', 'Pickens', 'Montgomery', 'Macon', 'Wilkes', 'Coffee',
       'Towns', 'Barrow', 'Gordon', 'Hart', 'Twiggs', 'Lee', 'Rockdale',
       'Columbia', 'Clay', 'Crawford', 'Lanier', 'Screven', 'Clinch',
       'Atkinson', 'Henry', 'Lamar', 'Miller', 'Muscogee', 'Richmond',
       'Wilkinson', 'Dougherty', 'Liberty', 'Echols', 'Bulloch',
       'Franklin', 'Douglas', 'Lumpkin', 'Bibb', 'Taylor', 'Ben Hill',
       'Cherokee', 'Burke', 'Heard', 'Irwin', 'Dodge', 'Effingham',
       'Greene', 'Spalding', 'Oconee', 'Bartow', 'Dawson', 'Hall',
       'Candler'], dtype=object)

In [7]:
full_election = full_election[~full_election["Ballot Name"].isin(["Total Votes","Ballots Cast"])]

In [8]:
full_election

,Precinct,Office Name,Contest ID,Ballot Name,Choice ID,Party,Total,County
2,BAL,US Senate - Rep,1,"Earl L. ""Buddy"" Carter",1.0,REP,344,Glynn
3,BAL,US Senate - Rep,1,Mike Collins,2.0,REP,170,Glynn
4,BAL,US Senate - Rep,1,John F. Coyne III,3.0,REP,3,Glynn
5,BAL,US Senate - Rep,1,Derek Dooley,4.0,REP,43,Glynn
6,BAL,US Senate - Rep,1,"Jonathan ""Jon"" McColumn",5.0,REP,18,Glynn
...,...,...,...,...,...,...,...,...
647452,Jack Strickland Community Center,BOE - District 2,49,Reagan Donaldson,130.0,NaN,0,Candler
647455,Jack Strickland Community Center,BOE - District 4,50,Ashley L. Donaldson,131.0,NaN,143,Candler
647456,Jack Strickland Community Center,BOE - District 4,50,Chris West (I),132.0,NaN,262,Candler
647459,Jack Strickland Community Center,E-SPLOST,53,Yes,147.0,NaN,1095,Candler
647460,Jack Strickland Community Center,E-SPLOST,53,No,148.0,NaN,716,Candler

In [9]:
SPANISH_FILTER_STR = r"(Senador|Representante|Gobernador|Comisionado|Juez|Alguacil|Fiscal|Secretario|Tesorero|Alcalde|Miembro|Concejal|Senado|Procurador|Vicegobernador|Presidente|Superintendente|Pregunta|Exención|Educación|Anexión)"

In [10]:
full_election.loc[full_election["Office Name"].str.contains(SPANISH_FILTER_STR),"Office Name"] = full_election.loc[full_election["Office Name"].str.contains(SPANISH_FILTER_STR),"Office Name"].apply(lambda x:re.sub(r"\s*/\s*.*?(?=\s*-\s*(?:Dem|Rep|Lib|Ind|NP)\b|$)", "", x))

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_19335/1554295960.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  full_election.loc[full_election["Office Name"].str.contains(SPANISH_FILTER_STR),"Office Name"] = full_election.loc[full_election["Office Name"].str.contains(SPANISH_FILTER_STR),"Office Name"].apply(lambda x:re.sub(r"\s*/\s*.*?(?=\s*-\s*(?:Dem|Rep|Lib|Ind|NP)\b|$)", "", x))

In [11]:
full_election.loc[full_election["Office Name"].str.contains(SPANISH_FILTER_STR),"Office Name"]

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_19335/3276053419.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  full_election.loc[full_election["Office Name"].str.contains(SPANISH_FILTER_STR),"Office Name"]

Series([], Name: Office Name, dtype: object)

In [12]:
ser = full_election["Office Name"].value_counts()

In [13]:
base = ['Governor - Rep', 'Governor - Dem', 'Lieutenant Governor - Rep',
       'US Senate - Rep', 'Commissioner of Insurance - Dem',
       'Secretary of State - Rep', 'Commissioner of Labor - Dem',
       'State School Superintendent - Rep', 'Secretary of State - Dem',
       'PSC - District 5 - Rep', 'State School Superintendent - Dem',
       'PSC - District 5 - Dem', 'Lieutenant Governor - Dem',
       'Party Question 5 - Rep', 'Party Question 1 - Rep',
       'Party Question 7 - Rep', 'Party Question 1 - Dem',
       'Party Question 4 - Rep', 'Party Question 2 - Dem',
       'Party Question 3 - Rep', 'Party Question 2 - Rep',
       'Party Question 6 - Rep', 'Party Question 8 - Rep',
       'Attorney General - Rep', 'Attorney General - Dem',
       'Commissioner of Agriculture - Dem', 'PSC - District 3 - Rep',
       'Judge - Court of Appeals of Georgia (Brown, III)',
       'Justice - Supreme Court of Georgia (Bethel)',
       'Justice - Supreme Court of Georgia (Warren)',
       'Judge - Court of Appeals of Georgia (Gobeil)',
       'PSC - District 3 - Dem', 'Commissioner of Labor - Rep',
       'Commissioner of Insurance - Rep', 'US Senate - Dem',
       'Commissioner of Agriculture - Rep',
       'Judge - Court of Appeals of Georgia (Doyle)',
       'Justice - Supreme Court of Georgia (Land)',
       'Judge - Court of Appeals of Georgia (Markle)',
       'Judge - Court of Appeals of Georgia (Padgett)',]

In [14]:
keep_contests = [i for i in list(full_election["Office Name"].unique()) if "State House of Representatives" in i or "State Senate" in i or "US House of Representatives" in i or "Court of Appeals of Georgia" in i or i in base or 'Justice - Supreme Court of Georgia' in i]
drop_contests = [i for i in list(full_election["Office Name"].unique()) if i not in keep_contests ]

In [15]:
keep_contests

['US Senate - Rep',
 'US Senate - Dem',
 'Governor - Rep',
 'Governor - Dem',
 'Lieutenant Governor - Rep',
 'Lieutenant Governor - Dem',
 'Secretary of State - Rep',
 'Secretary of State - Dem',
 'Attorney General - Rep',
 'Attorney General - Dem',
 'Commissioner of Agriculture - Rep',
 'Commissioner of Agriculture - Dem',
 'Commissioner of Insurance - Rep',
 'Commissioner of Insurance - Dem',
 'State School Superintendent - Rep',
 'State School Superintendent - Dem',
 'Commissioner of Labor - Rep',
 'Commissioner of Labor - Dem',
 'PSC - District 3 - Rep',
 'PSC - District 3 - Dem',
 'PSC - District 5 - Rep',
 'PSC - District 5 - Dem',
 'US House of Representatives - District 1 - Rep',
 'US House of Representatives - District 1 - Dem',
 'State Senate - District 3 - Rep',
 'State House of Representatives - District 179 - Rep',
 'Party Question 1 - Rep',
 'Party Question 2 - Rep',
 'Party Question 3 - Rep',
 'Party Question 4 - Rep',
 'Party Question 5 - Rep',
 'Party Question 6 - Rep',
 'Party Question 7 - Rep',
 'Party Question 8 - Rep',
 'Party Question 1 - Dem',
 'Party Question 2 - Dem',
 'Justice - Supreme Court of Georgia (Bethel)',
 'Justice - Supreme Court of Georgia (Land)',
 'Justice - Supreme Court of Georgia (Warren)',
 'Judge - Court of Appeals of Georgia (Brown, III)',
 'Judge - Court of Appeals of Georgia (Doyle)',
 'Judge - Court of Appeals of Georgia (Gobeil)',
 'Judge - Court of Appeals of Georgia (Markle)',
 'Judge - Court of Appeals of Georgia (Padgett)',
 'State House of Representatives - District 180 - Rep',
 'State House of Representatives - District 167 - Rep',
 'State House of Representatives - District 167 - Dem',
 'US House of Representatives - District 9 - Rep',
 'US House of Representatives - District 9 - Dem',
 'State Senate - District 50 - Rep',
 'State Senate - District 50 - Dem',
 'State House of Representatives - District 10 - Rep',
 'State House of Representatives - District 10 - Dem',
 'State House of Representatives - District 32 - Rep',
 'State House of Representatives - District 32 - Dem',
 'US House of Representatives - District 2 - Rep',
 'US House of Representatives - District 2 - Dem',
 'State Senate - District 20 - Rep',
 'State House of Representatives - District 150 - Rep',
 'State House of Representatives - District 150 - Dem',
 'US House of Representatives - District 8 - Rep',
 'US House of Representatives - District 8 - Dem',
 'State Senate - District 25 - Rep',
 'State House of Representatives - District 149 - Rep',
 'State House of Representatives - District 149 - Dem',
 'State House of Representatives - District 128 - Rep',
 'State House of Representatives - District 128 - Dem',
 'State Senate - District 18 - Rep',
 'State House of Representatives - District 147 - Rep',
 'State House of Representatives - District 147 - Dem',
 'State House of Representatives - District 146 - Rep',
 'State House of Representatives - District 143 - Dem',
 'State House of Representatives - District 148 - Rep',
 'State House of Representatives - District 148 - Dem',
 'State Senate - District 26 - Rep',
 'State Senate - District 26 - Dem',
 'US House of Representatives - District 12 - Rep',
 'US House of Representatives - District 12 - Dem',
 'State Senate - District 19 - Rep',
 'State Senate - District 19 - Dem',
 'State House of Representatives - District 156 - Rep',
 'State Senate - District 1 - Rep',
 'State Senate - District 1 - Dem',
 'State House of Representatives - District 164 - Rep',
 'State House of Representatives - District 164 - Dem',
 'State House of Representatives - District 166 - Rep',
 'State House of Representatives - District 166 - Dem',
 'State House of Representatives - District 160 - Rep',
 'State Senate - District 23 - Rep',
 'State Senate - District 23 - Dem',
 'State House of Representatives - District 158 - Rep',
 'State House of Representatives - District 174 - Rep',
 'State House of Representatives - District 174 - Dem',
 'US House of Representatives - District 5 - Rep',
 'US House of Representatives - District 5 - Dem',
 'State Senate - District 36 - Rep',
 'State Senate - District 36 - Dem',
 'State House of Representatives - District 62 - Dem',
 'State House of Representatives - District 63 - Dem',
 'State House of Representatives - District 59 - Rep',
 'State House of Representatives - District 59 - Dem',
 'State House of Representatives - District 57 - Rep',
 'State House of Representatives - District 57 - Dem',
 'State House of Representatives - District 56 - Dem',
 'State House of Representatives - District 58 - Rep',
 'State House of Representatives - District 58 - Dem',
 'State Senate - District 39 - Rep',
 'State Senate - District 39 - Dem',
 'State House of Representatives - District 55 - Rep',
 'State House of Representatives - District 55 - Dem',
 'State Senate - District 38 - Rep',
 'State Senate - District 38 - Dem',
 'US House of Representatives - District 6 - Rep',
 'US House of Representatives - District 6 - Dem',
 'State Senate - District 14 - Rep',
 'State Senate - District 14 - Dem',
 'State House of Representatives - District 54 - Rep',
 'State House of Representatives - District 54 - Dem',
 'State House of Representatives - District 60 - Dem',
 'State House of Representatives - District 53 - Rep',
 'State House of Representatives - District 53 - Dem',
 'State Senate - District 35 - Dem',
 'State House of Representatives - District 61 - Rep',
 'State House of Representatives - District 61 - Dem',
 'State House of Representatives - District 65 - Rep',
 'State House of Representatives - District 65 - Dem',
 'US House of Representatives - District 7 - Rep',
 'US House of Representatives - District 7 - Dem',
 'State House of Representatives - District 49 - Rep',
 'State House of Representatives - District 49 - Dem',
 'State Senate - District 21 - Rep',
 'State Senate - District 21 - Dem',
 'State House of Representatives - District 48 - Rep',
 'State House of Representatives - District 48 - Dem',
 'State Senate - District 48 - Rep',
 'State Senate - District 48 - Dem',
 'State House of Representatives - District 25 - Rep',
 'State House of Representatives - District 25 - Dem',
 'State House of Representatives - District 47 - Rep',
 'State House of Representatives - District 47 - Dem',
 'State House of Representatives - District 50 - Rep',
 'State House of Representatives - District 50 - Dem',
 'State Senate - District 28 - Dem',
 'State House of Representatives - District 67 - Rep',
 'State House of Representatives - District 67 - Dem',
 'State House of Representatives - District 68 - Dem',
 'State House of Representatives - District 51 - Rep',
 'State House of Representatives - District 51 - Dem',
 'State Senate - District 56 - Rep',
 'State Senate - District 56 - Dem',
 'State House of Representatives - District 69 - Dem',
 'State House of Representatives - District 52 - Dem',
 'State Senate - District 51 - Rep',
 'State Senate - District 51 - Dem',
 'State House of Representatives - District 8 - Rep',
 'State House of Representatives - District 8 - Dem',
 'State Senate - District 47 - Rep',
 'State Senate - District 47 - Dem',
 'State House of Representatives - District 31 - Rep',
 'State House of Representatives - District 120 - Rep',
 'State House of Representatives - District 120 - Dem',
 'State House of Representatives - District 119 - Rep',
 'State House of Representatives - District 119 - Dem',
 'State Senate - District 12 - Dem',
 'State House of Representatives - District 151 - Rep',
 'State House of Representatives - District 151 - Dem',
 'US House of Representatives - District 10 - Rep',
 'US House of Representatives - District 10 - Dem',
 'State House of Representatives - District 144 - Rep',
 'State House of Representatives - District 124 - Rep',
 'State House of Representatives - District 124 - Dem',
 'State House of Representatives - District 126 - Rep',
 'State House of Representatives - District 126 - Dem',
 'US House of Representatives - District 14 - Rep',
 'US House of Representatives - District 14 - Dem',
 'State Senate - District 54 - Rep',
 'State House of Representatives - District 6 - Rep',
 'State House of Representatives - District 6 - Dem',
 'State House of Representatives - District 132 - Dem',
 'State House of Representatives - District 154 - Rep',
 'State House of Representatives - District 154 - Dem',
 'State House of Representatives - District 7 - Rep',
 'State House of Representatives - District 155 - Rep',
 'State House of Representatives - District 155 - Dem',
 'State Senate - District 11 - Rep',
 'State House of Representatives - District 171 - Rep',
 'US House of Representatives - District 4 - Rep',
 'US House of Representatives - District 4 - Dem',
 'State Senate - District 41 - Rep',
 'State Senate - District 41 - Dem',
 'State House of Representatives - District 86 - Dem',
 'State Senate - District 40 - Rep',
 'State Senate - District 40 - Dem',
 'State House of Representatives - District 83 - Rep',
 'State House of Representatives - District 83 - Dem',
 'State House of Representatives - District 80 - Rep',
 'State House of Representatives - District 80 - Dem',
 'State Senate - District 10 - Rep',
 'State Senate - District 10 - Dem',
 'State Senate - District 44 - Rep',
 'State Senate - District 44 - Dem',
 'State House of Representatives - District 84 - Dem',
 'State House of Representatives - District 85 - Rep',
 'State House of Representatives - District 85 - Dem',
 'State House of Representatives - District 89 - Dem',
 'State House of Representatives - District 90 - Rep',
 'State House of Representatives - District 90 - Dem',
 'State House of Representatives - District 101 - Rep',
 'State House of Representatives - District 101 - Dem',
 'State Senate - District 55 - Rep',
 'State Senate - District 55 - Dem',
 'State House of Representatives - District 87 - Rep',
 'State House of Representatives - District 87 - Dem',
 'State House of Representatives - District 115 - Rep',
 'State House of Representatives - District 115 - Dem',
 'State House of Representatives - District 116 - Rep',
 'State House of Representatives - District 116 - Dem',
 'State House of Representatives - District 91 - Dem',
 'US House of Representatives - District 13 - Rep',
 'US House of Representatives - District 13 - Dem',
 'State House of Representatives - District 88 - Rep',
 'State House of Representatives - District 88 - Dem',
 'State Senate - District 43 - Dem',
 'State House of Representatives - District 93 - Dem',
 'State House of Representatives - District 94 - Dem',
 'State House of Representatives - District 95 - Rep',
 'State House of Representatives - District 95 - Dem',
 'State Senate - District 8 - Rep',
 'State House of Representatives - District 175 - Rep',
 'State House of Representatives - District 175 - Dem',
 'State House of Representatives - District 176 - Rep',
 'State House of Representatives - District 176 - Dem',
 'State House of Representatives - District 177 - Dem',
 'State Senate - District 24 - Rep',
 'State Senate - District 24 - Dem',
 'State House of Representatives - District 123 - Rep',
 'State House of Representatives - District 123 - Dem',
 'State Senate - District 53 - Rep',
 'State Senate - District 53 - Dem',
 'State House of Representatives - District 3 - Rep',
 'State House of Representatives - District 3 - Dem',
 'State House of Representatives - District 2 - Rep',
 'State House of Representatives - District 2 - Dem',
 'State House of Representatives - District 1 - Rep',
 'State House of Representatives - District 1 - Dem',
 'US House of Representatives - District 3 - Rep',
 'US House of Representatives - District 3 - Dem',
 'State Senate - District 29 - Rep',
 'State Senate - District 29 - Dem',
 'State House of Representatives - District 137 - Dem',
 'State House of Representatives - District 136 - Rep',
 'State House of Representatives - District 157 - Rep',
 'State House of Representatives - District 157 - Dem',
 'State House of Representatives - District 172 - Rep',
 'State House of Representatives - District 134 - Rep',
 'State Senate - District 15 - Rep',
 'State Senate - District 15 - Dem',
 'State Senate - District 27 - Rep',
 'State Senate - District 27 - Dem',
 'State House of Representatives - District 24 - Rep',
 'State House of Representatives - District 24 - Dem',
 'State House of Representatives - District 28 - Rep',
 'State House of Representatives - District 28 - Dem',
 'State House of Representatives - District 26 - Rep',
 'State House of Representatives - District 26 - Dem',
 'State House of Representatives - District 11 - Rep',
 'State House of Representatives - District 11 - Dem',
 'State House of Representatives - District 100 - Rep',
 'State House of Representatives - District 100 - Dem',
 'State House of Representatives - District 178 - Rep',
 'State House of Representatives - District 178 - Dem',
 'State House of Representatives - District 173 - Rep',
 'State House of Representatives - District 173 - Dem',
 'State Senate - District 13 - Rep',
 'State House of Representatives - District 169 - Rep',
 'State Senate - District 46 - Rep',
 'State Senate - District 46 - Dem',
 'State House of Representatives - District 111 - Rep',
 'State House of Representatives - District 111 - Dem',
 'Justice - Supreme Court of Georgia',
 'Judge - Court of Appeals of Georgia',
 'State Senate - District 45 - Rep',
 'State Senate - District 45 - Dem',
 'State House of Representatives - District 105 - Rep',
 'State House of Representatives - District 105 - Dem',
 'State House of Representatives - District 99 - Rep',
 'State House of Representatives - District 99 - Dem',
 'State Senate - District 9 - Rep',
 'State Senate - District 9 - Dem',
 'State House of Representatives - District 110 - Rep',
 'State House of Representatives - District 110 - Dem',
 'State Senate - District 7 - Rep',
 'State Senate - District 7 - Dem',
 'Special State Senate - District 7',
 'State House of Representatives - District 107 - Rep',
 'State House of Representatives - District 107 - Dem',
 'State House of Representatives - District 104 - Rep',
 'State House of Representatives - District 103 - Rep',
 'State House of Representatives - District 103 - Dem',
 'State House of Representatives - District 108 - Rep',
 'State House of Representatives - District 108 - Dem',
 'State House of Representatives - District 102 - Dem',
 'State Senate - District 5 - Dem',
 'State House of Representatives - District 109 - Dem',
 'State House of Representatives - District 106 - Dem',
 'State House of Representatives - District 96 - Dem',
 'State House of Representatives - District 98 - Dem',
 'State House of Representatives - District 97 - Rep',
 'State House of Representatives - District 97 - Dem',
 'State House of Representatives - District 30 - Rep',
 'State House of Representatives - District 30 - Dem',
 'State House of Representatives - District 112 - Rep',
 'State House of Representatives - District 112 - Dem',
 'State House of Representatives - District 133 - Rep',
 'State House of Representatives - District 76 - Dem',
 'State Senate - District 34 - Dem',
 'State House of Representatives - District 77 - Dem',
 'State House of Representatives - District 79 - Rep',
 'State House of Representatives - District 79 - Dem',
 'State House of Representatives - District 75 - Dem',
 'State Senate - District 17 - Dem',
 'State House of Representatives - District 74 - Dem',
 'State House of Representatives - District 78 - Dem',
 'State House of Representatives - District 33 - Rep',
 'State House of Representatives - District 170 - Rep',
 'State House of Representatives - District 152 - Rep',
 'State House of Representatives - District 152 - Dem',
 'State House of Representatives - District 139 - Rep',
 'State House of Representatives - District 139 - Dem',
 'State House of Representatives - District 138 - Rep',
 'State House of Representatives - District 138 - Dem',
 'State Senate - District 30 - Rep',
 'State Senate - District 30 - Dem',
 'State House of Representatives - District 71 - Rep',
 'State House of Representatives - District 71 - Dem',
 'State House of Representatives - District 18 - Rep',
 'State House of Representatives - District 18 - Dem',
 'State Senate - District 6 - Rep',
 'State Senate - District 6 - Dem',
 'State House of Representatives - District 70 - Rep',
 'State House of Representatives - District 70 - Dem',
 'State House of Representatives - District 72 - Rep',
 'State House of Representatives - District 122 - Rep',
 'State House of Representatives - District 122 - Dem',
 'State House of Representatives - District 121 - Rep',
 'State House of Representatives - District 121 - Dem',
 'State Senate - District 2 - Dem',
 'State House of Representatives - District 163 - Dem',
 'State House of Representatives - District 165 - Dem',
 'State House of Representatives - District 162 - Dem',
 'State House of Representatives - District 161 - Rep',
 'State House of Representatives - District 161 - Dem',
 'State Senate - District 4 - Rep',
 'State Senate - District 16 - Rep',
 'State Senate - District 16 - Dem',
 'State House of Representatives - District 82 - Rep',
 'State House of Representatives - District 82 - Dem',
 'State House of Representatives - District 73 - Rep',
 'State House of Representatives - District 73 - Dem',
 'State House of Representatives - District 118 - Rep',
 'State House of Representatives - District 118 - Dem',
 'State House of Representatives - District 4 - Rep',
 'State House of Representatives - District 4 - Dem',
 'State Senate - District 31 - Rep',
 'State Senate - District 31 - Dem',
 'State House of Representatives - District 16 - Rep',
 'State House of Representatives - District 16 - Dem',
 'State House of Representatives - District 9 - Rep',
 'State House of Representatives - District 9 - Dem',
 'State House of Representatives - District 145 - Rep',
 'State House of Representatives - District 145 - Dem',
 'State Senate - District 37 - Rep',
 'State Senate - District 37 - Dem',
 'State House of Representatives - District 36 - Rep',
 'State House of Representatives - District 36 - Dem',
 'US House of Representatives - District 11 - Rep',
 'US House of Representatives - District 11 - Dem',
 'State House of Representatives - District 22 - Rep',
 'State House of Representatives - District 22 - Dem',
 'State House of Representatives - District 35 - Rep',
 'State House of Representatives - District 35 - Dem',
 'State Senate - District 32 - Rep',
 'State Senate - District 32 - Dem',
 'State House of Representatives - District 44 - Rep',
 'State House of Representatives - District 44 - Dem',
 'State House of Representatives - District 38 - Dem',
 'State House of Representatives - District 39 - Dem',
 'State House of Representatives - District 41 - Dem',
 'State House of Representatives - District 43 - Dem',
 'State House of Representatives - District 34 - Rep',
 'State House of Representatives - District 34 - Dem',
 'State Senate - District 33 - Dem',
 'State House of Representatives - District 45 - Rep',
 'State House of Representatives - District 45 - Dem',
 'State House of Representatives - District 42 - Rep',
 'State House of Representatives - District 42 - Dem',
 'State House of Representatives - District 46 - Rep',
 'State House of Representatives - District 46 - Dem',
 'State House of Representatives - District 37 - Dem',
 'State House of Representatives - District 19 - Rep',
 'State House of Representatives - District 19 - Dem',
 'State House of Representatives - District 12 - Rep',
 'State House of Representatives - District 12 - Dem',
 'State Senate - District 52 - Rep',
 'State House of Representatives - District 13 - Rep',
 'State House of Representatives - District 13 - Dem',
 'State House of Representatives - District 5 - Rep',
 'State House of Representatives - District 5 - Dem',
 'State House of Representatives - District 135 - Rep',

In [16]:
drop_contests

['County Commissioner - Post 1 - Rep',
 'County Commissioner - District 3 - Rep',
 'County Commissioner - District 4 - Rep',
 'County Commissioner - District 4 - Dem',
 'BOE - Post 1 - Rep',
 'BOE - Post 1 - Dem',
 'BOE - District 4 - Rep',
 'BOE - District 4 - Dem',
 'Party Question 9 - Rep',
 'Party Question 10 - Rep',
 'Party Question 3 - Dem',
 'Party Question 4 - Dem',
 'Judge - Superior Court - Brunswick Judicial Circuit (Lane)',
 'Joint Water & Sewer Commissioner - Post 2',
 'BOE - District 2 - Rep',
 'County Commission - District 2 - Rep',
 'County Commission - District 3 - Rep',
 'Special County Commission - District 3',
 'County BOE - District 3 - Rep',
 'County BOE - District 4 - Rep',
 'County BOE - District 5 - Rep',
 'Judge - Superior Court - Mountain Judicial Circuit (Carswell)',
 'Judge - Superior Court - Mountain Judicial Circuit (Jones, III)',
 'Board of Education ESPLOST VII',
 'District Attorney - Cordele Judicial Circuit - Rep',
 'County BOE - District 2 - Rep',
 'County BOE - District 2 - Dem',
 'County Commission - District 4 - Dem',
 'County BOE - District 4 - Dem',
 'County Commissioner - District 3 - Dem',
 'State Court Judge',
 'BOE - District 1',
 'County Commissioner - District 5 - Rep',
 'County Commissioner - District 5 - Dem',
 'BOE - District 5',
 'Solicitor General - Rep',
 'County Commission Chairman- Rep',
 'County Commissioner - Post 2 - Rep',
 'County Commissioner - Post 2 - Dem',
 'Judge - Superior Court - Houston Judicial Circuit (Smith)',
 'BOE - At Large - Post 6',
 'FLOST',
 'BOE - District 2',
 'BOE - District 4',
 'BOE - At Large',
 'BOE - District 6',
 'District Attorney - Atlantic Judicial Circuit - Rep',
 'County Commission - District 5 - Rep',
 'School Board Chairman - Rep',
 'BOE - District 5 - Rep',
 'BOE - District 5 - Dem',
 'Judge - Superior Court - Atlantic Judicial Circuit (Hendrix)',
 'Judge - Superior Court - Atlantic Judicial Circuit (Stewart)',
 'RENEWAL OF 1% ESPLOST',
 'County Commission - District 2 - Dem',
 'BOE - District 1 - Rep',
 'County Commission - District 4 - Rep',
 'Judge - Superior Court - Middle Judicial Circuit (Reeves)',
 'Judge - Superior Court - Middle Judicial Circuit (Smith)',
 'District Attorney - Waycross Judicial Circuit - Rep',
 'County Commission - Post 4 - Rep',
 'County Commission - Post 5 - Rep',
 'Judge - Superior Court - Waycross Judicial Circuit (Kight)',
 'Board of Education - Post 2',
 'Board of Education - Post 4',
 'County Commission Chairperson - Rep',
 'County Commission Chairperson - Dem',
 'Party Question 11 - Rep',
 'Party Question 12 - Rep',
 'Party Question 5 - Dem',
 'Party Question 6 - Dem',
 'Judge - Superior Court - Atlanta Judicial Circuit (Benton)',
 'Judge - Superior Court - Atlanta Judicial Circuit (Eaton)',
 'Judge - Superior Court - Atlanta Judicial Circuit (Ellerbe)',
 'Judge - Superior Court - Atlanta Judicial Circuit (Farmer)',
 'Judge - Superior Court - Atlanta Judicial Circuit (McBurney)',
 'Judge - Superior Court - Atlanta Judicial Circuit (Schwall)',
 'Judge - Superior Court - Atlanta Judicial Circuit (Whitaker)',
 'Judge - Fulton County State Court (Eady)',
 'Judge - Fulton County State Court (Richardson)',
 'Judge - Fulton County State Court (Roth)',
 'Judge - Fulton County Chief Magistrate (Kirk)',
 'County Commissioner - District 5  Dem',
 'County Commissioner - District 1 - Rep',
 'County Commissioner - District 1 - Dem',
 'County BOE - District 2',
 'County BOE - District 5',
 'County BOE - District 6',
 'Special City Council LRG - Fairburn',
 'County BOE - District 7',
 'Special City Council - District 3 - South Fulton',
 'District Attorney - Enotah Judicial Circuit - Rep',
 'Judge - Superior Court - Enotah Judicial Circuit (George)',
 'Judge - Superior Court - Enotah Judicial Circuit (Levins)',
 'County Commission - District 5 - Dem',
 'County BOE - Post 2 - Rep',
 'County BOE - Post 3 - Rep',
 'County BOE - Post 5 - Rep',
 'Judge - Superior Court - Piedmont Judicial Circuit (Griffie)',
 'County Commission - District 3 - Dem',
 'BOE - District 3',
 'BOE - District 7',
 'Pulaski Sales Tax',
 'District Attorney - Pataula Judicial Circuit - Rep',
 'County Commission - District 1 - Dem',
 'Judge - Superior Court - Pataula Judicial Circuit (Balkcom)',
 'Judge - Superior Court - Southwestern Judicial Circuit (Sizemore)',
 'County BOE - District 3',
 'County BOE - District 4 (SE)',
 'Commissioner Chairman- Rep',
 'BOE - District 1 - Dem',
 'BOE - District 2 - Dem',
 'Magistrate Court Judge',
 'County Commissioner - District 2 - Rep',
 'County Commissioner - District 2 - Dem',
 'County BOE - District 6 - Rep',
 'County BOE - District 7 - Rep',
 'Judge - Superior Court - Conasauga Judicial Circuit (Morris)',
 'Judge - Superior Court - Conasauga Judicial Circuit (Wilbanks)',
 'Chief Magistrate',
 'County BOE - District 4',
 'BOE Chairman',
 'ESPLOST Referendum',
 'Board of Education - District 1',
 'Board of Education - District 5',
 'County Commission Chairman - Rep',
 'County Commission - Post 2 - Rep',
 'Judge - Superior Court - Appalachian Judicial Circuit (Priest)',
 'Judge - Superior Court - Appalachian Judicial Circuit (Sosebee)',
 'County BOE - Post 4',
 'County BOE - Post 5',
 'Solicitor General - Dem',
 'Board of Education - District 2',
 'Continuance of 1% Sales Tax (SPLOST) for Decatur County Projects',
 'County Commission - District 1 - Rep',
 'County Commission - District 6 - Rep',
 'Board of Education - District 6',
 'Board of Education - District 4',
 'County Commission - District 7 - Dem',
 'Judge - Superior Court - DeKalb Judicial Circuit (A. Jackson)',
 'Judge - Superior Court - DeKalb Judicial Circuit (L. Jackson)',
 'Judge - Superior Court - DeKalb Judicial Circuit (Johnson)',
 'Judge - State Court - A-1',
 'Judge - State Court - A-2',
 'Judge - State Court - A-4',
 'Judge - State Court - A-7',
 'Judge - State Court - B-10',
 'County Board of Education - District 2',
 'County Board of Education - District 4',
 'County Board of Education - District 6',
 'Party Question 13 - Rep',
 'Party Question 14 - Rep',
 'Party Question 15 - Rep',
 'Judge - Superior Court - Southern Judicial Circuit (Prine)',
 'Judge - Superior Court - Southern Judicial Circuit (Smith)',
 'Judge - Superior Court - Southern Judicial Circuit (Voyles)',
 'County School Board - District 2',
 'Homestead Exemptions from Lowndes County Ad Valorem Taxes - HB 815/Act 335',
 'Homestead Exemptions from Lowndes County Ad Valorem Taxes - HB 814/Act 334',
 'Homestead Exemptions from Lowndes County School District Ad Valorem Taxes - HB 813/Act 333',
 'Homestead Exemptions from Lowndes County School District Ad Valorem Taxes - HB 811/Act 332',
 'County School Board - District 1',
 'County School Board - District 3',
 'County Commission Chair - Rep',
 'County BOE - District 5 - Dem',
 'State Court Solicitor - Rep',
 'Judge - Superior Court - Lookout Mountain Judicial Circuit (Thompson)',
 'Mayor - Ringgold (SE)',
 'Council Member at Large - Ringgold (SE)',
 'Homestead Exemption',
 'County Commissioner - Post 1 - Dem',
 'County Commissioner - Post 3 - Dem',
 'County Commissioner - Post 5 - Dem',
 'Council Member - Rossville (SE)',
 'Judge - Superior Court - Coweta Judicial Circuit (Bendinger)',
 'Chief Magistrate Judge',
 'County BOE - District 1 - Dem',
 'County Commission - Post 2 - Dem',
 'County BOE - Bearden - Rep',
 'County BOE - Cole - Rep',
 'County BOE Chair',
 'One Percent FLOST',
 'County BOE - At Large - Rep',
 'Judge - State Court',
 'County BOE - Post 1 - Rep',
 'Judge of the Magistrate Court',
 'Special Referendum Election - Homestead Exemption From County Ad Valorem Taxes',
 'Special Referendum Election - Homestead Exemption From School Board Ad Valorem Taxes',
 'County Commissioner - District 2  - Rep',
 'Judge - Superior Court - Griffin Judicial Circuit (Coker)',
 'Judge - Superior Court - Griffin Judicial Circuit (Kreuziger)',
 'Judge - Superior Court - Griffin Judicial Circuit (Miller)',
 'County BOE - District 1 - Rep',
 'Educational One Percent Sales and Use Tax',
 'City Council LRG',
 'Party Question 7 - Dem',
 'Party Question 8 - Dem',
 'Party Question 9 - Dem',
 'Judge - Superior Court - Bell-Forsyth Judicial Circuit (Bagley)',
 'Judge - Superior Court - Bell-Forsyth Judicial Circuit (Smith)',
 'Judge - State Court of Forsyth Co',
 'Sunday Alcohol Sales',
 'County School Board - District 1 - Rep',
 'County School Board - District 3 - Rep',
 'County School Board - District 5 - Rep',
 'County School Board - District 7 - Rep',
 'Special Election - Coolidge City Council At-Large',
 'County Commissioner - District 7 - Dem',
 'School Board - District 1 - Dem',
 'School Board - District 3 - Rep',
 'School Board - District 3 - Dem',
 'Judge - Superior Court - Tifton Judicial Circuit (Powell)',
 'Judge - Superior Court - Tifton Judicial Circuit (Reinhardt)',
 'Sales Tax for Education',
 'Judge - Superior Court - Gwinnett Judicial Circuit',
 'Judge, State Court',
 'City of Lawrenceville Annexation',
 'Special Election - Clerk of Superior Court',
 'County BOE - District 1',
 'Board of Education - District 2 - Dem',
 'Board of Education - District 1 - Rep',
 'Board of Education - District 4 - Dem',
 'Board of Education - District 7 - Rep',
 'County BOE - District 8 - Dem',
 'Judge - Superior Court - Clayton Judicial Circuit (Carter)',
 'Judge - Superior Court - Clayton Judicial Circuit (Mason)',
 'State Court Judge (Garrett)',
 'State Court Judge (Hayward)',
 'State Court Judge (Spencer)',
 'County BOE - District 9 - Dem',
 'Nonbinding Advisory Referendum - Perimeter Highway',
 'Board of Commissioners - District 2 - Rep',
 'Board of Commissioners - District 2 - Dem',
 'Board of Commissioners - District 3 - Rep',
 'County Commission - District 1 at Large - Rep',
 'County Commission - District 2 at Large - Rep',
 'County BOE - District 1 at Large - Rep',
 'County BOE - District 1 at Large - Dem',
 'County BOE - District 2 at Large - Rep',
 'Continuation of Special 1% Sales And Use Tax',
 'Magistrate Judge',
 'For the Imposition of the Floating Homestead Local Option Sales Tax (FLOST)',
 'Wilcox County ESPLOST Renewal',
 'Judge - Superior Court - Chattahoochee Judicial Circuit (Burch)',
 'Nonpartisan County Commission - Post 3',
 'Nonpartisan County Commission - Post 4',
 'Nonpartisan County Commission - Post 5',
 'Nonpartisan County BOE - Post 2',
 'Nonpartisan County BOE - Post 4',
 'School Board - District 5 - Rep',
 'Judge - Superior Court - Alapaha Judicial Circuit (Perryman, III)',
 'School Board - District 2 - Rep',
 'School Board - District 4 - Rep',
 'Nashville Freeport Exemption Question 1',
 'Nashville Freeport Exemption Question 2',
 'Nashville Freeport Exemption Question 3',
 'Nashville Freeport Exemption Question 4',
 'Board of Education - District 7',
 'District Attorney - West Georgia Judicial Circuit - Rep',
 'Judge - Superior Court - West Georgia Judicial Circuit (Hightower)',
 'Judge - Carroll County - State Court Judge',
 'Judge - Superior Court - Western Judicial Circuit (Lott)',
 'Judge - Superior Court - Western Judicial Circuit (Norris)',
 'Mayor',
 'County Commission - District 3',
 'County Commission - District 9',
 'TSPLOST',
 'County Commission - District 1',
 'County Commission - District 7',
 'County BOE - District 9',
 'County Commission - District 5',
 'Elections Board Member 1 - Rep',
 'Elections Board Member 2  - Dem',
 'Elections Board Member 3 - Rep',
 'Elections Board Member 4  - Dem',
 'Judge - Superior Court - Eastern Judicial Circuit (Karpf)',
 'Judge - Superior Court - Eastern Judicial Circuit (Stokes)',
 'Judge - Superior Court - Eastern Judicial Circuit (Walmsley)',
 "Recorder's Court Judge (Huffman)",
 "Recorder's Court Judge (Williams)",
 'BOE President',
 'County Commissioner - District 4 (Farrell)',
 'BOE - District 4 (Kachmar)',
 'BOE - District 5 (Smith)',
 'BOE - District 6 (Bringman)',
 'BOE - District 8 (Howard-Hall)',
 'State Court Judge (Thompson)',
 'Judge - Superior Court - Towaliga Judicial Circuit (Wilson)',
 'Special County BOE - District 4',
 'School District Ad Valorem Tax Referendum',
 '2026 Special Purpose Local Option Sales Tax (SPLOST)',
 'County Commissioner Chairman - Special',
 'County Commissioner - District 4 - Special',
 'Sales Tax',
 'County Commission Chairman - Dem',
 'County Commission - Post 1 - Rep',
 'County Commission - Post 1 - Dem',
 'Homestead Exemption Sunset Removal',
 'Special Election - Board of Education - District 1',
 'Board of Education - District 3',
 'County Commissioner Chairman - Rep',
 'Chief Magistrate Court Judge',
 'ESPLOST',
 'Board of Education - District 4 - Rep',
 'County Commission - District 5 LRG - Rep',
 'BOE - District 3 - Rep',
 'BOE - District 3 - Dem',
 'Continuation of White County Education Special Use Sales Tax (ESPLOST)',
 'County Commission - Post 4 - Dem',
 'County BOE - Post 2 - Dem',
 'County BOE - Post 4 - Rep',
 'County BOE - Post 4 - Dem',
 'Board of Education - Post 5 - At Large - Rep',
 'Board of Education - Post 5 - At Large - Dem',
 'Judge - Superior Court - Macon Judicial Circuit (Mincey III)',
 'Judge - Superior Court - Macon Judicial Circuit (Raymond III)',
 'Judge - Superior Court - Macon Judicial Circuit (Smith)',
 'Judge - Superior Court - Macon Judicial Circuit (Williford)',
 'General Obligation Debt - One Percent TSPLOST',
 'Board of Education - District 5 - Rep',
 'Tift County School District Approval Of Bonds And 1% Sales And Use Tax For Educational Purposes (ESPLOST)',
 'Board of Education - District 6 - Rep',
 'BOE -District 1',
 'BOE -District 3',
 'BOE -District 5',
 'Special One Percent Floating Local Option Sales Tax Referendum',
 'Surveyor - Rep',
 'Judge - Superior Court - Cobb Judicial Circuit (Brown)',
 'Judge - Superior Court - Cobb Judicial Circuit (Harris)',
 'Judge - Superior Court - Cobb Judicial Circuit (Leonard)',
 'State Court Judge, Division 1, Post 5',
 'State Court Judge, Division 2, Post 1',
 'State Court Judge, Division 2, Post 4',
 'State Court Judge, Division 2, Post 5',
 'County BOE - District 6 - Dem',
 'County Commission - Post 5 - Dem',
 'Judge - Superior Court - Rome Judicial Circuit (King)',
 'Judge - Superior Court - Rome Judicial Circuit (Sparks)',
 'Juvenile Court Judge',
 'Board of Education - At Large',
 'County BOE - District 3 - Dem',
 'County Commission - Post 3',
 'County Commission - Post 4',
 'County Commission - Post 5',
 'School Board - District 1',
 'School Board - District 2',
 'State Court Judge (Cunningham)',
 'State Court Judge (Poulakos)',
 'State Court Judge (Swope)',
 'County Board of Education At Large Dist 1',
 'TSPLOST Continuation',
 'Nonpartisan County BOE - District 2',
 'Nonpartisan County BOE - District 3',
 'Nonpartisan County BOE - District 6',
 'Nonpartisan County BOE - District 1',
 'City Council Member - Post 5 (SE)',
 'Distilled Spirits Referendum',
 'County Commission - District 1A - Rep',
 'County Commission - District 1A - Dem',
 'County Commission - District 1B - Dem',
 'County BOE - Super District 1',
 'County Commission - Chairman - Rep',
 'Board of Education - Chairman',
 'District Attorney - Paulding Judicial Circuit - Rep',
 'State Court Solicitor General - Rep',
 'Judge - Superior Court - Paulding Judicial Circuit (Rollins)',
 'Judge - State Court (Rountree)',
 'County Commission - Post 3 - Rep',
 'County Commission - Post 3 - Dem',
 'Judge - Superior Court - Alcovy Judicial Circuit (McCamy)',
 'Judge - Superior Court - Alcovy Judicial Circuit (Zon)',
 'Board of Commissioners - District 4 - Dem',
 'County Commission - District 2, Post 1 - Rep',
 'County Commission - District 1, Post 2 - Dem',
 'Board of Education - District 3 - Dem',
 'County BOE - District 1 Post 2 - Rep',
 'County BOE - District 2 Post 1 - Rep',
 'County BOE - District 2 Post 2 - Rep',
 'County BOE - District 3 Post 1 - Rep',
 'ESPLOST VII',
 'Board of Education - District 3 - Rep',
 'Board of Education - At Large - Rep',
 'Board of Education - At Large - Dem',
 'Board of Education - District 2 - Rep',
 'Commissioner Chairman - Rep',
 'Commissioner Chairman - Dem',
 'BOE Chairman - Rep',
 'BOE Chairman - Dem',
 'Renewal of 1% Educational Sales Tax',
 'School Board - District 4',
 'County BOE - Post 2 - Young Harris',
 'County BOE - Post 3 - Hiawassee',
 'County BOE - Post 5 - At Large',
 'Solicitor-General of the State Court of Barrow County - Rep',
 'County BOE - District 7 At Large - Rep',
 'County BOE - District 9 At Large - Rep',
 'Judge of the State Court of Barrow County',
 'General Obligation Bond',
 'SPLOST',
 'County BOE - Post 7 - Rep',
 'Judge - Superior Court - Cherokee Judicial Circuit (Greene)',
 'Judge - Superior Court - Cherokee Judicial Circuit (Patel)',
 'Judge - Superior Court - Cherokee Judicial Circuit (Smith)',
 'BOE Chairperson - Dem',
 'County Board of Education - District 1',
 '1% Sales Tax Continuation and Issuance of General Obligation Debt',
 'County Board of Education - District 3',
 'District Attorney - Rockdale Judicial Circuit - Dem',
 'Judge - Superior Court - Rockdale Judicial Circuit (Bills)',
 'Associate State Court Judge',
 'County BOE - Post 1',
 'County BOE - Post 2',
 'District Attorney - Columbia Judicial Circuit - Rep',
 'Judge - Superior Court - Columbia Judicial Circuit (Blanchard)',
 'Judge - Superior Court - Columbia Judicial Circuit (Fleming)',
 'Judge - Superior Court - Macon Judicial Circuit (Mincey)',
 'Judge - Superior Court - Macon Judicial Circuit (Raymond)',
 'Nonpartisan County BOE - District 5',
 'County Commissioner - District 7- Rep',
 'Board of Education District 7',
 'Board of Education District 1',
 'Board of Education District 4',
 'Judge - Superior Court - Flint Judicial Circuit (Lewis)',
 'Judge - Superior Court - Flint Judicial Circuit (Palmer)',
 'Judge of State Court, Division 2',
 'Judge of State Court, Division 3',
 'County BOE - LRG - Rep',
 'Council - District 3',
 'Council - District 7',
 'Council - District 9 - At Large',
 'County BOE - At Large',
 'Special Council - District 9 - At Large',
 'Council - District 1',
 'Special Council - District 1',
 'County BOE - District 8',
 'Council - District 5',
 'Judge - Superior Court - Augusta Judicial Circuit (Heath)',
 'Judge - Superior Court - Augusta Judicial Circuit (Stone)',
 'Judge - Superior Court - Augusta Judicial Circuit (Wright)',
 'State Court Judge (Pounds)',
 'State Court Judge (Walker)',
 'Chief Judge Civil and Magistrate Court',
 'Reimposition Or Non-Reimposition Of A Special One Percent Sales And Use Tax',
 'Special One-Half Percent Sales And Use Tax To Reduce Property Taxes',
 'Augusta Commission - District 2',
 'Augusta Commission - District 10',
 'Augusta Commission - District 4',
 'Augusta Commission - District 6',
 'Augusta Commission - District 8',
 'Special FLOST',
 'Issuance of Licenses',
 'Drink Sales',
 'Sunday Package Sales',
 'Sunday Sales by Drink',
 'Judge - Superior Court - Dougherty Judicial Circuit (Dent)',
 'Dougherty County FLOST',
 'County Commission - District 6 - Dem',
 'Board of Education - District 6 - Dem',
 'BOE Chairman- At Large',
 'County Commission - District 1 Post 2 - Rep',
 'County Commission - District 2 Post 2 - Rep',
 'Board of Education - Post 1',
 'General Obligation Bond And Reimposition Of 1% Educational Sales Tax',
 'Commissioner- 2-B - Rep',
 'Commissioner- 2-D - Rep',
 'Commissioner- 1-B - Rep',
 'Commissioner- 1-B - Dem',
 'Solicitor-General - Dem',
 'Judge - Superior Court - Douglas Judicial Circuit (Adams)',
 'Special County Commission Chairperson',
 'County BOE Chairperson',
 'State Court Judge (Hanson)',
 'State Court Judge (Lewis)',
 'For Civil/Magistrate Court Judge',
 'Macon Water Authority',
 'Macon Water Authority - District 1',
 'BOE - Post 7 - At Large',
 'BOE - Post 8 - At Large',
 'Macon Water Authority - District 2',
 'Macon Water Authority - District 4',
 'County Commissioner - District 2, Post 2 - Dem',
 'County Commissioner - District 3, Post 1 - Rep',
 'School Board Representative - District 1',
 'School Board Representative - District 2',

In [17]:
full_election = full_election[full_election["Office Name"].isin(keep_contests)]

In [18]:
full_election = full_election[~full_election["Office Name"].str.contains("Special")]

In [19]:
court_dict1 = dict(zip(full_election.loc[full_election["Ballot Name"].isin(['Charles "Charlie" Bethel (I)', 'Miracle Rankin', 'Ben Land (I)',
       'Jen Auer Jordan', 'Sarah Hawkins Warren (I)'])&full_election["Office Name"].str.contains("(",regex=False),"Ballot Name"],full_election.loc[full_election["Ballot Name"].isin(['Charles "Charlie" Bethel (I)', 'Miracle Rankin', 'Ben Land (I)',
       'Jen Auer Jordan', 'Sarah Hawkins Warren (I)'])&full_election["Office Name"].str.contains("(",regex=False),"Office Name"]))

In [20]:
full_election.loc[(full_election["Office Name"].str.contains("Supreme"))&(~full_election["Office Name"].str.contains("(", regex = False)),"Office Name"] = full_election.loc[(full_election["Office Name"].str.contains("Supreme"))&(~full_election["Office Name"].str.contains("(", regex = False)),"Ballot Name"].map(court_dict1)

In [21]:
court_dict2 = dict(zip(full_election.loc[full_election["Ballot Name"].isin(['Trenton "Trent" Brown (I)', 'Will Wooten', 'Sara Doyle (I)',
       'Fatima Harris Felton', 'Elizabeth D. Gobeil (I)',
       'David Todd Markle (I)', 'J. Wade Padgett (I)'])&full_election["Office Name"].str.contains("(",regex=False),"Ballot Name"],full_election.loc[full_election["Ballot Name"].isin(['Trenton "Trent" Brown (I)', 'Will Wooten', 'Sara Doyle (I)',
       'Fatima Harris Felton', 'Elizabeth D. Gobeil (I)',
       'David Todd Markle (I)', 'J. Wade Padgett (I)'])&full_election["Office Name"].str.contains("(",regex=False),"Office Name"]))

In [22]:
full_election.loc[(full_election["Office Name"].str.contains("Court of Appeals"))&(~full_election["Office Name"].str.contains("(", regex = False)),"Office Name"] = full_election.loc[(full_election["Office Name"].str.contains("Court of Appeals"))&(~full_election["Office Name"].str.contains("(", regex = False)),"Ballot Name"].map(court_dict2)

In [23]:
full_election.loc[full_election["Ballot Name"].str.contains("Deandre Mathis"),"Ballot Name"] = "DeAndre Mathis"
full_election.loc[full_election["Ballot Name"].str.contains("Jermarkus A. Jacobs"),"Ballot Name"] = "JerMarkus A. Jacobs"
full_election.loc[full_election["Ballot Name"].str.contains("Robert Flournoy, Jr.(I)", regex = False),"Ballot Name"] = "Robert Flournoy, Jr. (I)"
full_election.loc[full_election["Office Name"].str.contains("State House of Representatives - District 139- Dem"),"Office Name"] = "State House of Representatives - District 139 - Dem"

In [24]:
full_election["Prec_ID"] = full_election["County"]+"-:-"+full_election["Precinct"].astype(str)
full_election["Party"] = full_election["Party"].fillna("NO PARTY")
full_election["Cand_ID"] = full_election["Office Name"]+"-:-"+full_election["Party"]+"-:-"+full_election["Ballot Name"]

In [25]:
data = pd.pivot_table(full_election, index = "Prec_ID", columns = "Cand_ID", values = "Total")

In [26]:
drop_data = [i for i in list(data.columns) if "County" in i]

In [27]:
data.drop(drop_data, axis =1,inplace = True)

In [28]:
data.reset_index(inplace = True, drop = False)

In [29]:
def get_race(race_string, print_debug):
    race_string = race_string.title()
    race_string = race_string.replace("(Vote For 1)","")
    if "U.S. House" in race_string or 'Us House' in race_string or "Representative To Congress" in race_string or "U. S. Representative" in race_string or "United States Representative" in race_string or "Congress" in race_string or "U S House" in race_string or "United States House Of Representatives" in race_string:
        return "CON"
    elif "State House" in race_string or "State Representative" in race_string or "Representative" in race_string or "House Of Delegates" in race_string:
        return "SL"
    elif "State Senate" in race_string or "State Senator" in race_string or "Senate Of Virginia" in race_string or "Tennessee Senate District" in race_string:
        return "SU"
    elif "President" in race_string:
        return "PRE"
    elif "US Senate" in race_string or "Us Senate" in race_string or "U.S. Senator" in race_string or "U. S. Senator" in race_string or "United States Senator" in race_string or "U S Senate" in race_string or "United States Senate" in race_string:
        return "USS"
    elif "Public Service" in race_string or "Psc" in race_string:
        return "PSC"+re.sub("\D","",race_string)
    elif "Attorney General" in race_string:
        return "ATG"
    elif "Auditor General" in race_string or "Auditor" in race_string:
        return "AUD"
    elif "Treasurer" in race_string:
        return "TRE"
    elif "Superintendent" in race_string:
        return "SUP"
    elif "Secretary Of State" in race_string:
        return "SOS"
    elif "Lieutenant Governor" in race_string:
        return "LTG"
    elif "Governor" in race_string:
        return "GOV"


    elif "Commissioner Of Labor" in race_string:
        return "LAB"
    elif "Commissioner Of Agriculture" in race_string:
        return "AGR"
    elif "Commissioner Of Insurance" in race_string:
        return "INS"
    elif "Chief Justice Of The Supreme Court" in race_string:
        return "CJU"
    elif "Supreme" in race_string:

        return "SC"+race_string.split("-:-")[0].split(" ")[-1][1]
    elif "Justice Of The Supreme Court" in race_string:
        return "JUS"
    elif "Party Question" in race_string:
        return "PQ"+re.sub("\D","",race_string).zfill(2)
    elif "Amendment" in race_string:
        num = race_string.split(" ")[2]

        return "AMD"+num
    elif "Bond Question" in race_string:
        num = race_string.split(" ")[3]
        return "BQ"+str(num)
    elif "Judicial Retention" in race_string:
        return "JR"
    elif "Commissioner Of Public Lands" in race_string:
        return "CPL"
    elif "Court Of Appeals" in race_string:
        return "COA"+race_string.split("-:-")[0].split(" ")[-1][1]
    elif "Comptroller" in race_string:
        return "COM"
    
    elif "All Medically Appropriate Assisted" in race_string:
        return "BI1"
    
    elif "Should Any Candidate Appearing On The Illinois Ballot For Federal" in race_string:
        return "BI3"
    
    elif "Illinois Constitution Be Amended To Create An Additional 3%" in race_string:
        return "BI2"

    else:
        if print_debug:
            print("No race for:", race_string)
        raise ValueError
        
def get_election_type(race_string, print_debug):
    if "Special" in race_string:
        return "S"
    else:
        return "P"
        
def get_party(race_string, print_debug):
    race_string = race_string.split("-:-")[1]
    race_string = race_string.replace('"',"'")

    if "JUDICIAL RETENTION" in race_string or "Amendment" in race_string or "amendment" in race_string or "Bond Question" in race_string or "Retain" in race_string:
        return ""
    elif "(REP)" in race_string or "REPUBLICAN" in race_string:
        return "R"
    elif "(DEM)" in race_string or "(Democrat)" in race_string or "DEMOCRAT" in race_string:
        return "D"
    elif "(L)" in race_string or "(LBT)" in race_string or "LIBERTARIAN" in race_string:
        return "L"
    elif "(WI)" in race_string:
        return "O"
    elif "(IND)" in race_string:
        return "I"
    elif "(NOPTY)" in race_string:
        return "N"
    elif race_string[0:3]=="YES":
        return "YES"
    elif "NO PARTY" in race_string:
        return "O"
    else:
        return race_string[0]
           
def get_name(name_string, print_debug):
    name_string_unmodified = name_string
    if "No." in name_string:
        return ""
    elif "All Others" in name_string:
        return "OTH"
    else:
        #print(name_string)
        name_string = name_string.replace(" (write in)","").replace(" (I)","")
        if "President" in name_string:
            name_string = name_string.split("/")[0]        
        else:
            name_string = name_string.split("-:-")[2]
            
        if name_string == "Sharon Stokes Williamson":
            return "WLM"
        
        
            

            
        name_string = name_string.replace("'","")
        name_string = name_string.split(" / ")[0]
        likely_last = name_string.split(" ")[-1]
        if "Special State Senate" in name_string_unmodified:
            likely_last = name_string.split(" ")[-2]
        proposed_last = likely_last[:3]
        if proposed_last in ['II', 'III', 'Jr', 'Jr.', 'Sr.', 'JR.', "JR", "IV", 'I']:
            likely_last = name_string.split(" ")[-2]
            proposed_last = likely_last[:3]
        return proposed_last.upper()
#     else:
#         return name_string.split(" ")[-1][:3].upper()
import re
 

def get_district(race_string, fill_level, print_debug):
    race_string = race_string.replace('"',"'").replace(" (Vote for 1)","").replace(" including precincts 1","")
    temp = race_string
    if "State Representative" in race_string:
        if "Berkshire" in race_string:
            return "BK"+re.sub("\D","",temp)
        elif "Barnstable" in race_string:
            if "Barnstable Dukes and Nantucket" in race_string:
                return "BDN"
            return "BN"+re.sub("\D","",temp)
        elif "Hampshire" in race_string:
            return "HS"+re.sub("\D","",temp)
        return race_string.split("-:-")[0].split(" ")[-1].zfill(fill_level)
    elif "State Senate" in race_string:
        if "Third Bristol Plymouth District" in race_string:
            return "3BP"
        elif "-Worcester Hampden District" in race_string:
            return "WHM"
        elif "-Hampden District" in race_string:
            return "HMN"
        elif "Plymouth and Barnstable District" in race_string:
            return "PLB"
        elif "2nd Essex and Middlesex District" in race_string:
            return "2EM"
        elif "1st Essex District" in race_string:
            return "1ED"
        elif "Norfolk and Suffolk District" in race_string:
            return "NRS"
        elif "Middlesex and Norfolk District" in race_string:
            return "MXN"
        elif "Middlesex and Suffolk District" in race_string:
            return "MXS"
        elif "Bristol and Norfolk District" in race_string:
            return "BLN"
        elif "Norfolk Worcester Middlesex District" in race_string:
            return "NWM"
        elif "5th Middlesex District" in race_string:
            return "5MX"
        elif "4th Middlesex District" in race_string:
            return "4MX"
        elif "3rd Middlesex District" in race_string:
            return "3MX"
        elif "2nd Middlesex District" in race_string:
            return "2MX"
        elif "1st Middlesex District" in race_string:
            return "1MX"
        elif "Second Plymouth Norfolk District" in race_string:
            return "2PN"
        elif "Worcester and Middlesex District" in race_string:
            return "WRM"
        elif "1st Bristol and Plymouth District" in race_string:
            return "1BP"

        elif "Hampshire Franklin and Worcester District" in race_string:
            return "HFW"
        elif "Berkshire Hampden Franklin Hampshire District" in race_string:
            return "BHF"
        elif "1st Worcester District" in race_string:
            return "1WR"
        elif "Hampden Hampshire Worcester District" in race_string:
            return "HHW"
        elif "Cape and Islands District" in race_string:
            return "CPI"
        elif "Suffolk and Middlesex District" in race_string:
            return "SKM"
        elif "2nd Essex District" in race_string:
            return "2ES"
        elif "3rd Essex District" in race_string:
            return "3ES"
        elif "Norfolk Middlesex District" in race_string:
            return "NKM"
        elif "1st Essex and Middlesex District" in race_string:
            return "1EM"
        elif "2nd Suffolk District" in race_string:
            return "2SF"
        elif "1st Suffolk District" in race_string:
            return "1SF"
        elif "2nd Bristol and Plymouth District" in race_string:
            return "2BP"
        elif "Norfolk Plymouth Bristol District" in race_string:
            return "NPB"
        elif "Middlesex and Worcester District" in race_string:
            return "MXW"
        elif "Worcester Hampshire District" in race_string:
            return "WRH"
        elif "3rd Suffolk District" in race_string:
            return "3SF"
        elif "Norfolk and Plymouth District" in race_string:
            return "NRP"
        elif "First Plymouth Norfolk District" in race_string:
            return "1PN"
        elif "2nd Worcester District" in race_string:
            return "2WR"
        elif "Hampden and Hampshire District" in race_string:
            return "HMH"
        else:
            return re.sub("\D","",temp).zfill(fill_level)
        

#         else:
#             print("FIX", race_string)
#             raise ValueError
                
        
    else:
        return re.sub("\D","",temp).zfill(fill_level)

def column_rename_function(name_string, print_debug):
    election_type = get_election_type(name_string, print_debug)
    year = "26"
    party = get_party(name_string,print_debug)
    race = get_race(name_string,print_debug)
    district = ""
    #print(name_string)
    if race in ["CON", "SU"]:
        district = get_district(name_string, 2,print_debug)
        year = ""
    elif race in ["SL"]:
        district = get_district(name_string, 3,print_debug)
        year = ""
    elif race in ["SC"]:
        district = get_district(name_string, 1,print_debug)
        year = ""
    elif "PSC" in race or "PQ" in race or "COA" in race:
        year = ""
    name = get_name(name_string,print_debug)
    if "AMD" in race:
        party = ""
    if "BI" in race:
        party = ""
    new_col_name = election_type + year + race + district + party + name
    if print_debug:
        print(name_string)
        print("election_type: ", election_type)
        print("year: ", year)
        print("race: ", race)
        print("district: ", district)
        print("party: ", party)
        print("name: ", name)
    if len(new_col_name) > 10:
        print("LONG NAME")
        print(name_string, "->", new_col_name)
        raise ValueError
    return new_col_name

# Make a dictionary that points to the new column names and checks for duplicates


def get_column_renaming_vals(df, non_contest_names_list, print_debug = False):

    races_to_clean = [i for i in df.columns if i not in non_contest_names_list]


    race_updates_dict = {}
    race_updates_reversed = {}
    #clean_dups = {}
    new_names = []
    error_w_rename = []
    duplicate_contest = []
    skipped_contest = []
    for val in races_to_clean:
        if "Clerk of Courts" not in val and "Register of Deeds" not in val and "Governor s Council" not in val:
            try:
                new_name = column_rename_function(val, print_debug)
                race_updates_dict[val] = new_name
                if new_name not in new_names:
                    new_names.append(new_name)
                    race_updates_reversed[new_name] = val
                else:
                    duplicate_contest.append(new_name)

                    if print_debug:
                        print("Duplicate", new_name)
                        print(race_updates_reversed[new_name])
                        print(val)
                    #clean_dups[val] = race_updates_reversed[new_name]
            except ValueError as v:
                error_w_rename.append(val)
        else:
            skipped_contest.append(val)
            
    if len(error_w_rename)>0:
        print("Error Renaming")
        print(error_w_rename)
        
    if len(duplicate_contest)>0:
        print("Duplicate Contest")
        print(duplicate_contest)
        
    if len(skipped_contest) > 0:
        print("Skipped Contest")
        print(skipped_contest)        
            
    return race_updates_dict, race_updates_reversed, error_w_rename, duplicate_contest, skipped_contest

In [30]:
race_updates_dict, race_updates_reversed, error_w_rename, duplicate_contest, skipped_contest = get_column_renaming_vals(data, ['Prec_ID'], print_debug = False)

In [31]:
data.rename(columns = race_updates_dict, inplace = True)

In [32]:
# Export the Renamed Columns for the README
pd.DataFrame(race_updates_dict.items()).to_csv("./field_names26prim.csv", index = False)

In [33]:
# Sort the race columns in alphabetical order
race_cols = list(race_updates_reversed.keys())
race_cols.sort()

In [34]:
# Rename to UNIQUE_ID, add COUNTYFP, separate into County and Precinct columns
data["County"] = data["Prec_ID"].apply(lambda x:x.split("-:-")[0])
data["Precinct"] = data["Prec_ID"].apply(lambda x:x.split("-:-")[1])

In [35]:
county = pd.read_csv("/Users/peterhorton/Documents/RDH/raw_data/census/PL_COUNTYFP_NAMES.csv")
ga_cnty_fips_dict = dict((zip(county[county["STUSAB"]=="GA"]["NAME"].str.replace(" County",""),county[county["STUSAB"]=="GA"]["COUNTYFP"].astype(str).str.zfill(3))))

In [36]:
ga_cnty_fips_dict

{'Appling': '001',
 'Atkinson': '003',
 'Bacon': '005',
 'Baker': '007',
 'Baldwin': '009',
 'Banks': '011',
 'Barrow': '013',
 'Bartow': '015',
 'Ben Hill': '017',
 'Berrien': '019',
 'Bibb': '021',
 'Bleckley': '023',
 'Brantley': '025',
 'Brooks': '027',
 'Bryan': '029',
 'Bulloch': '031',
 'Burke': '033',
 'Butts': '035',
 'Calhoun': '037',
 'Camden': '039',
 'Candler': '043',
 'Carroll': '045',
 'Catoosa': '047',
 'Charlton': '049',
 'Chatham': '051',
 'Chattahoochee': '053',
 'Chattooga': '055',
 'Cherokee': '057',
 'Clarke': '059',
 'Clay': '061',
 'Clayton': '063',
 'Clinch': '065',
 'Cobb': '067',
 'Coffee': '069',
 'Colquitt': '071',
 'Columbia': '073',
 'Cook': '075',
 'Coweta': '077',
 'Crawford': '079',
 'Crisp': '081',
 'Dade': '083',
 'Dawson': '085',
 'Decatur': '087',
 'DeKalb': '089',
 'Dodge': '091',
 'Dooly': '093',
 'Dougherty': '095',
 'Douglas': '097',
 'Early': '099',
 'Echols': '101',
 'Effingham': '103',
 'Elbert': '105',
 'Emanuel': '107',
 'Evans': '109',
 'Fannin': '111',
 'Fayette': '113',
 'Floyd': '115',
 'Forsyth': '117',
 'Franklin': '119',
 'Fulton': '121',
 'Gilmer': '123',
 'Glascock': '125',
 'Glynn': '127',
 'Gordon': '129',
 'Grady': '131',
 'Greene': '133',
 'Gwinnett': '135',
 'Habersham': '137',
 'Hall': '139',
 'Hancock': '141',
 'Haralson': '143',
 'Harris': '145',
 'Hart': '147',
 'Heard': '149',
 'Henry': '151',
 'Houston': '153',
 'Irwin': '155',
 'Jackson': '157',
 'Jasper': '159',
 'Jeff Davis': '161',
 'Jefferson': '163',
 'Jenkins': '165',
 'Johnson': '167',
 'Jones': '169',
 'Lamar': '171',
 'Lanier': '173',
 'Laurens': '175',
 'Lee': '177',
 'Liberty': '179',
 'Lincoln': '181',
 'Long': '183',
 'Lowndes': '185',
 'Lumpkin': '187',
 'McDuffie': '189',
 'McIntosh': '191',
 'Macon': '193',
 'Madison': '195',
 'Marion': '197',
 'Meriwether': '199',
 'Miller': '201',
 'Mitchell': '205',
 'Monroe': '207',
 'Montgomery': '209',
 'Morgan': '211',
 'Murray': '213',
 'Muscogee': '215',
 'Newton': '217',
 'Oconee': '219',
 'Oglethorpe': '221',
 'Paulding': '223',
 'Peach': '225',
 'Pickens': '227',
 'Pierce': '229',
 'Pike': '231',
 'Polk': '233',
 'Pulaski': '235',
 'Putnam': '237',
 'Quitman': '239',
 'Rabun': '241',
 'Randolph': '243',
 'Richmond': '245',
 'Rockdale': '247',
 'Schley': '249',
 'Screven': '251',
 'Seminole': '253',
 'Spalding': '255',
 'Stephens': '257',
 'Stewart': '259',
 'Sumter': '261',
 'Talbot': '263',
 'Taliaferro': '265',
 'Tattnall': '267',
 'Taylor': '269',
 'Telfair': '271',
 'Terrell': '273',
 'Thomas': '275',
 'Tift': '277',
 'Toombs': '279',
 'Towns': '281',
 'Treutlen': '283',
 'Troup': '285',
 'Turner': '287',
 'Twiggs': '289',
 'Union': '291',
 'Upson': '293',
 'Walker': '295',
 'Walton': '297',
 'Ware': '299',
 'Warren': '301',
 'Washington': '303',
 'Wayne': '305',
 'Webster': '307',
 'Wheeler': '309',
 'White': '311',
 'Whitfield': '313',
 'Wilcox': '315',
 'Wilkes': '317',
 'Wilkinson': '319',
 'Worth': '321'}

In [37]:
data["COUNTYFP"] = data["County"].map(ga_cnty_fips_dict).fillna(data["County"])

In [38]:
data["County"].unique()

array(['Appling', 'Atkinson', 'Bacon', 'Baker', 'Baldwin', 'Banks',
       'Barrow', 'Bartow', 'Ben Hill', 'Berrien', 'Bibb', 'Bleckley',
       'Brantley', 'Brooks', 'Bryan', 'Bulloch', 'Burke', 'Butts',
       'Calhoun', 'Camden', 'Candler', 'Carroll', 'Catoosa', 'Charlton',
       'Chatham', 'Chattahoochee', 'Chattooga', 'Cherokee', 'Clarke',
       'Clay', 'Clayton', 'Clinch', 'Cobb', 'Coffee', 'Colquitt',
       'Columbia', 'Cook', 'Coweta', 'Crawford', 'Crisp', 'Dade',
       'Dawson', 'DeKalb', 'Decatur', 'Dodge', 'Dooly', 'Dougherty',
       'Douglas', 'Early', 'Echols', 'Effingham', 'Elbert', 'Emanuel',
       'Evans', 'Fannin', 'Fayette', 'Floyd', 'Forsyth', 'Franklin',
       'Fulton', 'Gilmer', 'Glascock', 'Glynn', 'Gordon', 'Grady',
       'Greene', 'Gwinnett', 'Habersham', 'Hall', 'Hancock', 'Haralson',
       'Harris', 'Hart', 'Heard', 'Henry', 'Houston', 'Irwin', 'Jackson',
       'Jasper', 'Jeff Davis', 'Jefferson', 'Jenkins', 'Johnson', 'Jones',
       'Lamar', 'Lanier', 'Laurens', 'Lee', 'Liberty', 'Lincoln', 'Long',
       'Lowndes', 'Lumpkin', 'Macon', 'Madison', 'Marion', 'McDuffie',
       'McIntosh', 'Meriwether', 'Miller', 'Mitchell', 'Monroe',
       'Montgomery', 'Morgan', 'Murray', 'Muscogee', 'Newton', 'Oconee',
       'Oglethorpe', 'Paulding', 'Peach', 'Pickens', 'Pierce', 'Pike',
       'Polk', 'Pulaski', 'Putnam', 'Quitman', 'Rabun', 'Randolph',
       'Richmond', 'Rockdale', 'Schley', 'Screven', 'Seminole',
       'Spalding', 'Stephens', 'Stewart', 'Sumter', 'Talbot',
       'Taliaferro', 'Tattnall', 'Taylor', 'Telfair', 'Terrell', 'Thomas',
       'Tift', 'Toombs', 'Towns', 'Treutlen', 'Troup', 'Turner', 'Twiggs',
       'Union', 'Upson', 'Walker', 'Walton', 'Ware', 'Warren',
       'Washington', 'Wayne', 'Webster', 'Wheeler', 'White', 'Whitfield',
       'Wilcox', 'Wilkes', 'Wilkinson', 'Worth'], dtype=object)

In [39]:
data["COUNTYFP"].unique()

array(['001', '003', '005', '007', '009', '011', '013', '015', '017',
       '019', '021', '023', '025', '027', '029', '031', '033', '035',
       '037', '039', '043', '045', '047', '049', '051', '053', '055',
       '057', '059', '061', '063', '065', '067', '069', '071', '073',
       '075', '077', '079', '081', '083', '085', '089', '087', '091',
       '093', '095', '097', '099', '101', '103', '105', '107', '109',
       '111', '113', '115', '117', '119', '121', '123', '125', '127',
       '129', '131', '133', '135', '137', '139', '141', '143', '145',
       '147', '149', '151', '153', '155', '157', '159', '161', '163',
       '165', '167', '169', '171', '173', '175', '177', '179', '181',
       '183', '185', '187', '193', '195', '197', '189', '191', '199',
       '201', '205', '207', '209', '211', '213', '215', '217', '219',
       '221', '223', '225', '227', '229', '231', '233', '235', '237',
       '239', '241', '243', '245', '247', '249', '251', '253', '255',
       '257', '259', '261', '263', '265', '267', '269', '271', '273',
       '275', '277', '279', '281', '283', '285', '287', '289', '291',
       '293', '295', '297', '299', '301', '303', '305', '307', '309',
       '311', '313', '315', '317', '319', '321'], dtype=object)

In [40]:
data.rename(columns = {"Prec_ID":"UNIQUE_ID"}, inplace = True)

In [41]:
data = data[["UNIQUE_ID","COUNTYFP","County","Precinct"]+race_cols]

In [42]:
data = data.fillna(0)
for col in race_cols:
    data[col] =data[col].astype(str)
    data[col] =data[col].str.replace(",","")
    data[col] =data[col].astype(float)
    data[col] =data[col].astype(int)

## Join to Runoff Data

In [43]:
runoff = pd.read_csv("./prim_runoff_temp.csv")
runoff.rename(columns = {"Prec_ID":"UNIQUE_ID"}, inplace = True)

In [44]:
combined = pd.merge(data,runoff,how = "outer", on = "UNIQUE_ID", indicator = True)

In [45]:
combined["_merge"].value_counts()

_merge
both          2584
right_only       1
left_only        0
Name: count, dtype: int64

In [46]:
combined[combined["_merge"]!="both"]

# Note: These precinct appears in the results, just with 0 votes

,UNIQUE_ID,COUNTYFP,County,Precinct,P26AGRDJUH,P26AGRDROW,P26AGRRHAR,P26ATGDMIL,P26ATGDTRA,P26ATGRCOW,...,RSU07DROM,RSU10DJOH,RSU10DROG,RSU14DABE,RSU14DKAN,RSU46RMCK,RSU46RMCM,RSU51RMIL,RSU51RWAD,_merge
145,Burke-:-Blythe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,right_only

In [47]:
combined.drop("_merge", axis = 1, inplace = True)
combined = combined.fillna(0)

In [48]:
combined_data_cols = [i for i in list(combined.columns) if (i[0]=="P" or i[0]=="R") and i not in ["Precinct"]]

In [49]:
for col in combined_data_cols:
    combined[col] = combined[col].astype(int)

In [50]:
combined

,UNIQUE_ID,COUNTYFP,County,Precinct,P26AGRDJUH,P26AGRDROW,P26AGRRHAR,P26ATGDMIL,P26ATGDTRA,P26ATGRCOW,...,RSU07DGAR,RSU07DROM,RSU10DJOH,RSU10DROG,RSU14DABE,RSU14DKAN,RSU46RMCK,RSU46RMCM,RSU51RMIL,RSU51RWAD
0,Appling-:-1B,001,Appling,1B,24,18,394,33,8,165,...,0,0,0,0,0,0,0,0,0,0
1,Appling-:-1C,001,Appling,1C,14,6,320,15,4,115,...,0,0,0,0,0,0,0,0,0,0
2,Appling-:-2,001,Appling,2,208,144,183,305,55,74,...,0,0,0,0,0,0,0,0,0,0
3,Appling-:-3A1,001,Appling,3A1,5,2,272,6,1,139,...,0,0,0,0,0,0,0,0,0,0
4,Appling-:-3C,001,Appling,3C,48,33,403,65,20,178,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,Worth-:-Scooterville,321,Worth,Scooterville,10,9,238,10,9,53,...,0,0,0,0,0,0,0,0,0,0
2581,Worth-:-Sumner,321,Worth,Sumner,11,19,180,26,5,44,...,0,0,0,0,0,0,0,0,0,0
2582,Worth-:-Sylvester,321,Worth,Sylvester,238,233,191,402,85,52,...,0,0,0,0,0,0,0,0,0,0
2583,Worth-:-Sylvester East,321,Worth,Sylvester East,29,37,296,55,11,83,...,0,0,0,0,0,0,0,0,0,0
2584,Worth-:-Warwick,321,Worth,Warwick,44,21,131,33,32,41,...,0,0,0,0,0,0,0,0,0,0

In [51]:
import os

if not os.path.exists("./ga_2026_prim_prec_csv"):
    os.mkdir("./ga_2026_prim_prec_csv")

combined.to_csv("./ga_2026_prim_prec_csv/ga_2026_prim_prec_csv.csv", index = False)

In [52]:
## Check Totals

In [53]:
prim_totals = pd.read_excel('/Users/peterhorton/Documents/RDH/pber_local/GA_2026/County Totals/tot_votes_prim26.xlsx')
prim_run_totals = pd.read_excel('/Users/peterhorton/Documents/RDH/pber_local/GA_2026/County Totals/tot_votes_prim26_runoff.xlsx')

In [54]:
prim_totals = prim_totals[prim_totals["Ballot Name"]!="Total Votes"]
prim_run_totals = prim_run_totals[prim_run_totals["Ballot Name"]!="Total Votes"]

In [55]:
for col in list(combined.columns):
    if col not in ["UNIQUE_ID","COUNTYFP","County","Precinct"]:
        
        if col[0]=="P" or col[0] == "S":
        
            rows = prim_totals[prim_totals["Total"]==sum(combined[col])].shape[0]
            if rows != 1:
                print(col)
                print(prim_totals[prim_totals["Total"]==sum(combined[col])])
                print("")
                print("******************")
        elif col[0]=="R":
            rows = prim_run_totals[prim_run_totals["Total"]==sum(combined[col])].shape[0]
            if rows != 1:
                print(col)
                print(prim_run_totals[prim_run_totals["Total"]==sum(combined[col])])  
                print("")
                print("******************")

P26LTGRSWA
                                            Office Name Contest ID  \
30                            Lieutenant Governor - Rep        S2R
1322  Judge - Superior Court - Rockdale Judicial Cir...      SJC71

                 Ballot Name Choice ID Party  Total
30              Takosha Swan        27   REP  10054
1322  Clarence Cuthpert, Jr.       139   NaN  10054

******************
PCON14RBRO
                                           Office Name Contest ID  \
197    US House of Representatives - District 14 - Rep     USH14R
595  State House of Representatives - District 37 -...     SHD37D

              Ballot Name Choice ID Party  Total
197            Beau Brown        79   REP   1489
595  Graham Salter Bowers       124   DEM   1489

******************
PCON14RLAM
                                            Office Name Contest ID  \
200     US House of Representatives - District 14 - Rep     USH14R
1020  State House of Representatives - District 149 ...    SHD149D

        Ballot Name Choice ID Party  Total
200      Nicky Lama        83   REP   1220
1020  Ross Sheppard       136   DEM   1220

******************
PSL001RCAM
                                           Office Name Contest ID  \
444  State House of Representatives - District 1 - Rep      SHD1R
871  State House of Representatives - District 111 ...    SHD111D

          Ballot Name Choice ID Party  Total
444  Mike Cameron (I)        92   REP   4747
871  Scott T. Jackson        91   DEM   4747

******************
PSL012DCHA
                                           Office Name Contest ID  \
494  State House of Representatives - District 12 -...     SHD12D
779  State House of Representatives - District 87 -...     SHD87R

           Ballot Name Choice ID Party  Total
494       Holly Chaney        93   DEM   1569
779  Timothy J. Burson       119   REP   1569

******************
PSL014RSCO
                                           Office Name Contest ID  \
501  State House of Representatives - District 14 -...     SHD14R
873  State House of Representatives - District 112 ...    SHD112R

               Ballot Name Choice ID Party  Total
501  Mitchell Scoggins (I)        92   REP   7767
873   Bruce Williamson (I)        92   REP   7767

******************
PSL023DEPS
                                           Office Name Contest ID  \
542  State House of Representatives - District 23 -...     SHD23D
629  State House of Representatives - District 47 -...     SHD47R

     Ballot Name Choice ID Party  Total
542  Rob Epstein       111   DEM   2561
629  Jack Miller       118   REP   2561

******************
PSL037DBOW
                                           Office Name Contest ID  \
197    US House of Representatives - District 14 - Rep     USH14R
595  State House of Representatives - District 37 -...     SHD37D

              Ballot Name Choice ID Party  Total
197            Beau Brown        79   REP   1489
595  Graham Salter Bowers       124   DEM   1489

******************
PSL041DSMI
                                            Office Name Contest ID  \
606   State House of Representatives - District 41 -...     SHD41D
1005  State House of Representatives - District 146 ...    SHD146R

            Ballot Name Choice ID Party  Total
606   Michael Smith (I)       128   DEM   6057
1005  Shaw Blackmon (I)        91   REP   6057

******************
PSL047RMIL
                                           Office Name Contest ID  \
542  State House of Representatives - District 23 -...     SHD23D
629  State House of Representatives - District 47 -...     SHD47R

     Ballot Name Choice ID Party  Total
542  Rob Epstein       111   DEM   2561
629  Jack Miller       118   REP   2561

******************
PSL057RLOV
                                           Office Name Contest ID  \
668  State House of Representatives - District 57 -...     SHD57R
955  State House of Representatives - District 130 ...    SHD130D

            Ballot Name Choice ID Party  Total
668  Helmut Lucero Love       140   REP   1323
955        Karen Gordon        97   DEM   1323

******************
PSL087RBUR
                                           Office Name Contest ID  \
494  State House of Representatives - District 12 -...     SHD12D
779  State House of Representatives - District 87 -...     SHD87R

           Ballot Name Choice ID Party  Total
494       Holly Chaney        93   DEM   1569
779  Timothy J. Burson       119   REP   1569

******************
PSL094DUGW
                                            Office Name Contest ID  \
806   State House of Representatives - District 94 -...     SHD94D
1084  State House of Representatives - District 168 ...    SHD168R

                   Ballot Name Choice ID Party  Total
806   Ikenna Emmanuel Ugwumadu       136   DEM   1998
1084           Kevin Remillard       137   REP   1998

******************
PSL099RREE
                                           Office Name Contest ID  \
825  State House of Representatives - District 99/ ...     SHD99R
859  State House of Representatives - District 108/...    SHD108D

         Ballot Name Choice ID Party  Total
825  Matt Reeves (I)       148   REP   3611
859      Rahim Asani       164   DEM   3611

******************
PSL108DASA
                                           Office Name Contest ID  \
825  State House of Representatives - District 99/ ...     SHD99R
859  State House of Representatives - District 108/...    SHD108D

         Ballot Name Choice ID Party  Total
825  Matt Reeves (I)       148   REP   3611
859      Rahim Asani       164   DEM   3611

******************
PSL111DJAC
                                           Office Name Contest ID  \
444  State House of Representatives - District 1 - Rep      SHD1R
871  State House of Representatives - District 111 ...    SHD111D

          Ballot Name Choice ID Party  Total
444  Mike Cameron (I)        92   REP   4747
871  Scott T. Jackson        91   DEM   4747

******************
PSL111RMAR
                                           Office Name Contest ID  \
869  State House of Representatives - District 111 ...    SHD111R
980  State House of Representatives - District 139 ...    SHD139R

                     Ballot Name Choice ID Party  Total
869  Reynaldo "Rey" Martinez (I)        90   REP   5868
980              Carmen Rice (I)        84   REP   5868

******************
PSL112RWIL
                                           Office Name Contest ID  \
501  State House of Representatives - District 14 -...     SHD14R
873  State House of Representatives - District 112 ...    SHD112R

               Ballot Name Choice ID Party  Total
501  Mitchell Scoggins (I)        92   REP   7767
873   Bruce Williamson (I)        92   REP   7767

******************
PSL130DGOR
                                           Office Name Contest ID  \
668  State House of Representatives - District 57 -...     SHD57R
955  State House of Representatives - District 130 ...    SHD130D

            Ballot Name Choice ID Party  Total
668  Helmut Lucero Love       140   REP   1323
955        Karen Gordon        97   DEM   1323

******************
PSL133RMAT
                                            Office Name Contest ID  \
965   State House of Representatives - District 133 ...    SHD133R
1024  State House of Representatives - District 150 ...    SHD150D

                    Ballot Name Choice ID Party  Total
965            Danny Mathis (I)       142   REP   4723
1024  Patty Bentley Stinson (I)        83   DEM   4723

******************
PSL136RJEN
                                           Office Name Contest ID  \
263                   State Senate - District 15 - Rep     SSD15R
972  State House of Representatives - District 136 ...    SHD136R

           Ballot Name Choice ID Party  Total
263         Chuck Hand        80   REP   6676
972  David Jenkins (I)        91   REP   6676

******************
PSL139RRIC
                                           Office Name Contest ID  \
869  State House of Representatives - District 111 ...    SHD111R
980  State House of Representatives - District 139 ...    SHD139R

                     Ballot Name Choice ID Party  Total
869  Reynaldo "Rey" Martinez (I)        90   REP   5868
980              Carmen Rice (I)        84   REP   5868

******************
PSL146RBLA
                                            Office Name Contest ID  \
606   State House of Representatives - District 41 -...     SHD41D
1005  State House of Representatives - District 146 ...    SHD146R

            Ballot Name Choice ID Party  Total
606   Michael Smith (I)       128   DEM   6057
1005  Shaw Blackmon (I)        91   REP   6057

******************
PSL149DSHE
                                            Office Name Contest ID  \
200     US House of Representatives - District 14 - Rep     USH14R
1020  State House of Representatives - District 149 ...    SHD149D

        Ballot Name Choice ID Party  Total
200      Nicky Lama        83   REP   1220
1020  Ross Sheppard       136   DEM   1220

******************
PSL149RPET
                                            Office Name Contest ID  \
426                    State Senate - District 53 - Rep     SSD53R
1017  State House of Representatives - District 149 ...    SHD149R

              Ballot Name Choice ID Party  Total
426   Denise Pierce Burns        94   REP   3166
1017         Randy Peters       134   REP   3166

******************
PSL150DSTI
                                            Office Name Contest ID  \
965   State House of Representatives - District 133 ...    SHD133R
1024  State House of Representatives - District 150 ...    SHD150D

                    Ballot Name Choice ID Party  Total
965            Danny Mathis (I)       142   REP   4723
1024  Patty Bentley Stinson (I)        83   DEM   4723

******************
PSL153DSAM
                                            Office Name Contest ID  \
1034  State House of Representatives - District 153 ...    SHD153D
1063  State House of Representatives - District 162 ...    SHD162D

                Ballot Name Choice ID Party  Total
1034  David Lee Sampson (I)        88   DEM   6041
1063          Orlando Scott        84   DEM   6041

******************
PSL162DSCO
                                            Office Name Contest ID  \
1034  State House of Representatives - District 153 ...    SHD153D
1063  State House of Representatives - District 162 ...    SHD162D

                Ballot Name Choice ID Party  Total
1034  David Lee Sampson (I)        88   DEM   6041
1063          Orlando Scott        84   DEM   6041

******************
PSL165DCLA
                                            Office Name Contest ID  \
345                    State Senate - District 35 - Dem     SSD35D
1071  State House of Representatives - District 165 ...    SHD165D

            Ballot Name Choice ID Party  Total
345   Elfreda Desvignes       106   DEM   2787
1071       Kendra Clark        88   DEM   2787

******************
PSL168RREM
                                            Office Name Contest ID  \
806   State House of Representatives - District 94 -...     SHD94D
1084  State House of Representatives - District 168 ...    SHD168R

                   Ballot Name Choice ID Party  Total
806   Ikenna Emmanuel Ugwumadu       136   DEM   1998
1084           Kevin Remillard       137   REP   1998

******************
PSU15RHAN
                                           Office Name Contest ID  \
263                   State Senate - District 15 - Rep     SSD15R
972  State House of Representatives - District 136 ...    SHD136R

           Ballot Name Choice ID Party  Total
263         Chuck Hand        80   REP   6676
972  David Jenkins (I)        91   REP   6676

******************
PSU35DDES
                                            Office Name Contest ID  \
345                    State Senate - District 35 - Dem     SSD35D
1071  State House of Representatives - District 165 ...    SHD165D

            Ballot Name Choice ID Party  Total
345   Elfreda Desvignes       106   DEM   2787
1071       Kendra Clark        88   DEM   2787

******************
PSU53RBUR
                                            Office Name Contest ID  \
426                    State Senate - District 53 - Rep     SSD53R
1017  State House of Representatives - District 149 ...    SHD149R

              Ballot Name Choice ID Party  Total
426   Denise Pierce Burns        94   REP   3166
1017         Randy Peters       134   REP   3166

******************

In [56]:

combined["R26INSDMAT"].sum()

157666

In [57]:
combined["R26INSDWAI"].sum()

224125

In [58]:
#File lists 157666 total for R26INSDMAT
#File lists 224125 total for R26INSDWAI

In [59]:
prim_run_totals = pd.read_excel('/Users/peterhorton/Documents/RDH/pber_local/GA_2026/County Totals/tot_votes_prim26_runoff.xlsx',sheet_name = "County Results")

In [60]:
prim_run_totals = prim_run_totals[prim_run_totals["Office Name"]=="Commissioner of Insurance - Dem"]

In [62]:
import shutil

In [64]:
shutil.make_archive("./ga_2026_prim_prec_csv","zip","./ga_2026_prim_prec_csv")

'/Users/peterhorton/Documents/RDH/pber_local/GA_2026/ga_2026_prim_prec_csv.zip'

In [68]:
print(list(combined.columns))

['UNIQUE_ID', 'COUNTYFP', 'County', 'Precinct', 'P26AGRDJUH', 'P26AGRDROW', 'P26AGRRHAR', 'P26ATGDMIL', 'P26ATGDTRA', 'P26ATGRCOW', 'P26ATGRSTR', 'P26GOVDBOT', 'P26GOVDBRO', 'P26GOVDDUF', 'P26GOVDDUN', 'P26GOVDEST', 'P26GOVDJAC', 'P26GOVDTHU', 'P26GOVRCAR', 'P26GOVRDEA', 'P26GOVRJAC', 'P26GOVRJON', 'P26GOVRKIR', 'P26GOVRRAF', 'P26GOVRWIL', 'P26GOVRYAS', 'P26INSDBLA', 'P26INSDDEA', 'P26INSDJAI', 'P26INSDMAT', 'P26INSDWAI', 'P26INSRKIN', 'P26LABDHUL', 'P26LABDMOO', 'P26LABDPOR', 'P26LABDSAN', 'P26LABDSMI', 'P26LABRHOL', 'P26LTGDMCL', 'P26LTGDPAR', 'P26LTGDWRI', 'P26LTGRCLA', 'P26LTGRDOL', 'P26LTGRGOO', 'P26LTGRKEN', 'P26LTGRNEL', 'P26LTGRSWA', 'P26LTGRTIL', 'P26SCBOBET', 'P26SCBORAN', 'P26SCLOLAN', 'P26SCWOJOR', 'P26SCWOWAR', 'P26SOSDASH', 'P26SOSDBAR', 'P26SOSDCON', 'P26SOSDREY', 'P26SOSRFLE', 'P26SOSRJON', 'P26SOSRKIN', 'P26SOSRMET', 'P26SOSRSTE', 'P26SUPDANT', 'P26SUPDPOW', 'P26SUPDTHO', 'P26SUPRLEE', 'P26SUPRLON', 'P26SUPRMAI', 'P26SUPRTRA', 'P26SUPRWOO', 'P26USSDOSS', 'P26USSRCAR', 'P26USSRCOL', 'P26USSRCOY', 'P26USSRDOO', 'P26USSRMCC', 'PCOADODOY', 'PCOAGOFEL', 'PCOAGOGOB', 'PCOAMOMAR', 'PCOAPOPAD', 'PCOAiOBRO', 'PCOAiOWOO', 'PCON01DDAN', 'PCON01DGRI', 'PCON01DHOL', 'PCON01DMCC', 'PCON01DPAL', 'PCON01DWIL', 'PCON01DWLM', 'PCON01DZUR', 'PCON01RFAR', 'PCON01RKIN', 'PCON01RMON', 'PCON01RPEN', 'PCON01RTAY', 'PCON01RYU', 'PCON02DBIS', 'PCON02RDAY', 'PCON03DJOH', 'PCON03DKEL', 'PCON03RJAC', 'PCON04DJOH', 'PCON04DPOS', 'PCON04DTRU', 'PCON04RDUF', 'PCON05DBEA', 'PCON05DWIL', 'PCON05RSAL', 'PCON06DMCB', 'PCON06RMAR', 'PCON06RPIN', 'PCON07DKOZ', 'PCON07DLON', 'PCON07DNOR', 'PCON07DTOW', 'PCON07RMCC', 'PCON08DEST', 'PCON08DLUC', 'PCON08RSCO', 'PCON09DALE', 'PCON09DGEG', 'PCON09RCLY', 'PCON09RCOU', 'PCON09RPOO', 'PCON10DDEL', 'PCON10DDOH', 'PCON10DDOR', 'PCON10RBAK', 'PCON10RGAI', 'PCON10RMIL', 'PCON11DHAR', 'PCON11DWOL', 'PCON11RADK', 'PCON11RCAR', 'PCON11RCOW', 'PCON11RHOB', 'PCON11RKAM', 'PCON11RMOR', 'PCON11RPRI', 'PCON12DGEO', 'PCON12DPEA', 'PCON12DSMI', 'PCON12DSTE', 'PCON12DWOO', 'PCON12RALL', 'PCON12RBRA', 'PCON13DBLA', 'PCON13DCLA', 'PCON13DFAU', 'PCON13DJON', 'PCON13DKIM', 'PCON13DLES', 'PCON13RCHA', 'PCON14DHAR', 'PCON14RBLA', 'PCON14RBOX', 'PCON14RBRO', 'PCON14RFUL', 'PCON14RGRA', 'PCON14RLAM', 'PCON14RMOO', 'PCON14RSTO', 'PPQ01DNO', 'PPQ01DYES', 'PPQ01RNO', 'PPQ01RYES', 'PPQ02DNO', 'PPQ02DYES', 'PPQ02RNO', 'PPQ02RYES', 'PPQ03RNO', 'PPQ03RYES', 'PPQ04RNO', 'PPQ04RYES', 'PPQ05RNO', 'PPQ05RYES', 'PPQ06RNO', 'PPQ06RYES', 'PPQ07RNO', 'PPQ07RYES', 'PPQ08RNO', 'PPQ08RYES', 'PPSC3DHUB', 'PPSC3RJOH', 'PPSC3RMAR', 'PPSC5DCUP', 'PPSC5DEDW', 'PPSC5DPRE', 'PPSC5RMEH', 'PPSC5RROD', 'PPSC5RTOL', 'PSL001DDIS', 'PSL001RCAM', 'PSL001RHOW', 'PSL002DECH', 'PSL002RHUR', 'PSL002RTAR', 'PSL003DSPE', 'PSL003RHOR', 'PSL003RMIL', 'PSL004DPOS', 'PSL004RCAR', 'PSL004RMAN', 'PSL005DJEN', 'PSL005RBAR', 'PSL006DKOT', 'PSL006RRID', 'PSL007RCHA', 'PSL008DMIT', 'PSL008RGUN', 'PSL009DSMI', 'PSL009RDOC', 'PSL009RROW', 'PSL009RSHE', 'PSL010DBRO', 'PSL010RAND', 'PSL011DFOU', 'PSL011RJAS', 'PSL012DCHA', 'PSL012RLUM', 'PSL013DMEN', 'PSL013RDEM', 'PSL013RMIN', 'PSL014DBAU', 'PSL014RSCO', 'PSL015DJON', 'PSL015RGAM', 'PSL016DSPA', 'PSL016RKEL', 'PSL017DGRE', 'PSL017RMOM', 'PSL018DRHU', 'PSL018RPHI', 'PSL018RSMI', 'PSL019DSTA', 'PSL019RGUL', 'PSL020DTAN', 'PSL020DZEI', 'PSL020RBYR', 'PSL020RFER', 'PSL021DARA', 'PSL021RTHO', 'PSL022DSHA', 'PSL022RRID', 'PSL023DEPS', 'PSL023RFIN', 'PSL024DGAU', 'PSL024RBAR', 'PSL025DPAD', 'PSL025DVAR', 'PSL025RJON', 'PSL025RPHI', 'PSL026DGRE', 'PSL026RMCD', 'PSL027DKIR', 'PSL027RHAW', 'PSL028DSAN', 'PSL028RCOX', 'PSL029DSOR', 'PSL029RDUB', 'PSL029REWI', 'PSL030DDOX', 'PSL030RMCC', 'PSL031RBIN', 'PSL032DSIM', 'PSL032RERW', 'PSL033RPOW', 'PSL034DNIC', 'PSL034RSEA', 'PSL035DCAM', 'PSL035RCAS', 'PSL036DNOI', 'PSL036REHR', 'PSL037DBOW', 'PSL037DWIL', 'PSL038DWIL', 'PSL039DCUM', 'PSL040DLAS', 'PSL040RNEW', 'PSL041DSMI', 'PSL042DSAN', 'PSL042DVIL', 'PSL042RSTA', 'PSL043DADE', 'PSL044DBEL', 'PSL044RPAR', 'PSL045DSCH', 'PSL045RCOO', 'PSL046DWAL', 'PSL046RCAR', 'PSL047DDEF', 'PSL047RCOC', 'PSL047RECK', 'PSL047RMIL', 'PSL048DCLE', 'PSL048RHIL', 'PSL049DLIN', 'PSL049RMAR', 'PSL050DAU', 'PSL050RDUA', 'PSL051DBAK', 'PSL051DPAN', 'PSL051RGET', 'PSL052DROB', 'PSL053DDOR', 'PSL053DFUL', 'PSL053RSIL', 'PSL054DHOL', 'PSL054DTUF', 'PSL054RMIL', 'PSL055DWIL', 'PSL055RLEN', 'PSL056DBER', 'PSL057DEVA', 'PSL057DOLN', 'PSL057RLOV', 'PSL058DHEN', 'PSL058DLAD', 'PSL058DLAM', 'PSL058DSAM', 'PSL058RBAL', 'PSL059DOLA', 'PSL059RSUL', 'PSL060DJON', 'PSL061DMCC', 'PSL061DMCQ', 'PSL061RBIS', 'PSL062DARN', 'PSL062DCOL', 'PSL062DRIN', 'PSL062DROS', 'PSL063DSCH', 'PSL064DBAK', 'PSL064RPAR', 'PSL065DDAW', 'PSL065RROL', 'PSL066DALE', 'PSL066DSMI', 'PSL067DGLA', 'PSL067RCOO', 'PSL068DBAK', 'PSL068DBON', 'PSL068DHEA', 'PSL068DPUL', 'PSL068DSAB', 'PSL068DWIL', 'PSL069DBAZ', 'PSL069DBRO', 'PSL069DCOO', 'PSL070DBOU', 'PSL070DWHA', 'PSL070RSTU', 'PSL071DHIG', 'PSL071DYAR', 'PSL071RHOW', 'PSL072RHUD', 'PSL073DWIL', 'PSL073RBON', 'PSL074DFLO', 'PSL075DBEL', 'PSL076DSCO', 'PSL077DBUR', 'PSL078DDOU', 'PSL079DNEA', 'PSL079RHAM', 'PSL080DTRA', 'PSL080RAND', 'PSL081DWHI', 'PSL081RKAH', 'PSL082DDIC', 'PSL082DHAR', 'PSL082RMAT', 'PSL083DLUP', 'PSL083RSMI', 'PSL084DOLI', 'PSL085DDRE', 'PSL085RFIE', 'PSL086DBAR', 'PSL087DDAV', 'PSL087RBUR', 'PSL088DMIT', 'PSL088RFRE', 'PSL089DCRA', 'PSL090DHUD', 'PSL090DSTA', 'PSL090RBOS', 'PSL091DGAR', 'PSL091DMOO', 'PSL092DBRO', 'PSL092DKIN', 'PSL092DTAY', 'PSL093DCAR', 'PSL094DALE', 'PSL094DKAU', 'PSL094DMAS', 'PSL094DUGW', 'PSL095DBRE', 'PSL095DJOH', 'PSL095DKEN', 'PSL095RHAL', 'PSL096DBEC', 'PSL096DISL', 'PSL097DLAU', 'PSL097DSIN', 'PSL097RMOG', 'PSL098DLIM', 'PSL098DROM', 'PSL099DABR', 'PSL099DKAN', 'PSL099RREE', 'PSL100DAMB', 'PSL100RCLA', 'PSL100RDUN', 'PSL101DHOL', 'PSL101RHUT', 'PSL102DOKO', 'PSL103DLUC', 'PSL103RHON', 'PSL104REFS', 'PSL105DMUG', 'PSL105RDON', 'PSL106DALI', 'PSL107DPAR', 'PSL107RBER', 'PSL108DASA', 'PSL108DPRE', 'PSL108RDAV', 'PSL109DEST', 'PSL109DPAR', 'PSL110DADE', 'PSL110RLOL', 'PSL111DJAC', 'PSL111RMAR', 'PSL112DMAR', 'PSL112RWIL', 'PSL113DHOO', 'PSL113DSAN', 'PSL113RSCA', 'PSL114DCAW', 'PSL114RMAU', 'PSL114RMCN', 'PSL115DLEW', 'PSL115RFRA', 'PSL116DHOL', 'PSL116RCON', 'PSL117DBRO', 'PSL117DSAN', 'PSL117DSMI', 'PSL117DWAL', 'PSL117DWIL', 'PSL118DBEL', 'PSL118DLEW', 'PSL118RCRO', 'PSL119DMOR', 'PSL119RPER', 'PSL120DKAR', 'PSL120RBLA', 'PSL120RPAT', 'PSL121DGIS', 'PSL121RGUE', 'PSL122DFRY', 'PSL122RHUB', 'PSL123DBEA', 'PSL123RLEV', 'PSL124DMIL', 'PSL124RRHO', 'PSL125DHEN', 'PSL125RRIC', 'PSL126DMYL', 'PSL126RHAR', 'PSL127DTAY', 'PSL127RNEW', 'PSL128DEVA', 'PSL128DLEW', 'PSL128RSHE', 'PSL129DCAM', 'PSL129DHOW', 'PSL130DCAL', 'PSL130DGOR', 'PSL130DNEL', 'PSL130DPIN', 'PSL130RCAR', 'PSL130RMCA', 'PSL131DEPP', 'PSL131RCLI', 'PSL132DPRI', 'PSL133RMAT', 'PSL133RPRU', 'PSL134RDIC', 'PSL135RCAM', 'PSL136RJEN', 'PSL137DBUC', 'PSL138DHUT', 'PSL138RSMI', 'PSL139DVAL', 'PSL139RRIC', 'PSL140DAVE', 'PSL140RKVI', 'PSL141DHUG', 'PSL141RLIP', 'PSL142DPAR', 'PSL142DTHO', 'PSL142RPAL', 'PSL143DJON', 'PSL144RWAS', 'PSL145DHER', 'PSL145RWIL', 'PSL146RBLA', 'PSL147DDUN', 'PSL147DRIL', 'PSL147RBAL', 'PSL148DBRY', 'PSL148DJOH', 'PSL148RWIL', 'PSL149DGRI', 'PSL149DSHE', 'PSL149RPET', 'PSL150DSTI', 'PSL150RMOO', 'PSL151DWOL', 'PSL151RCHE', 'PSL152DROS', 'PSL152RYEA', 'PSL153DSAM', 'PSL154DJAM', 'PSL154RGRE', 'PSL155DPOW', 'PSL155RCOO', 'PSL155RHAT', 'PSL156RHAG', 'PSL157DKIN', 'PSL157RAND', 'PSL157RWER', 'PSL158RPAR', 'PSL159RBUR', 'PSL159RHOO', 'PSL160RFRA', 'PSL161DDIL', 'PSL161RHIT', 'PSL162DSCO', 'PSL163DWES', 'PSL164DBUR', 'PSL164RSTE', 'PSL165DCLA', 'PSL165DGRE', 'PSL165DMOR', 'PSL166DDAL', 'PSL166RPET', 'PSL167DHIC', 'PSL167DTHO', 'PSL167RDEL', 'PSL168DNEW', 'PSL168DWIL', 'PSL168RREM', 'PSL169ROST', 'PSL170RFOR', 'PSL171RCAM', 'PSL172RCAN', 'PSL173DCHI', 'PSL173DTHO', 'PSL173RTAY', 'PSL174DHAL', 'PSL174RCOR', 'PSL175DWIS', 'PSL175RLAH', 'PSL176DRYA', 'PSL176RBUR', 'PSL176RDOC', 'PSL177DHOW', 'PSL177DMCB', 'PSL177DNAP', 'PSL177DPAY', 'PSL177DROB', 'PSL178DDUN', 'PSL178RMEE', 'PSL179RTOW', 'PSL180RSAI', 'PSU01DFOR', 'PSU01DGOO', 'PSU01RWAT', 'PSU02DMAL', 'PSU03RHOD', 'PSU04RHIC', 'PSU05DMCC', 'PSU05DRAH', 'PSU06DJAC', 'PSU06RBRA', 'PSU07DGAR', 'PSU07DROM', 'PSU07DROS', 'PSU07RSHA', 'PSU08RGOO', 'PSU09DMER', 'PSU09RJOH', 'PSU10DDEN', 'PSU10DJOH', 'PSU10DROG', 'PSU10DSMI', 'PSU10RSTA', 'PSU11RWAT', 'PSU12DBRO', 'PSU12DMOR', 'PSU12DTAY', 'PSU13RSUM', 'PSU14DABE', 'PSU14DHOW', 'PSU14DKAN', 'PSU14RDVO', 'PSU14RJOH', 'PSU14RMCQ', 'PSU15DHAR', 'PSU15DREE', 'PSU15DWIL', 'PSU15RHAN', 'PSU16DHAW', 'PSU16DHEN', 'PSU16RHAR', 'PSU17DDAV', 'PSU17DHAY', 'PSU18RALL', 'PSU18RMCN', 'PSU19DDEL', 'PSU19DWIL', 'PSU19RGIL', 'PSU19RHOD', 'PSU19RSIK', 'PSU20RWAL', 'PSU21DSIM', 'PSU21RDIC', 'PSU22DJON', 'PSU23DBOS', 'PSU23DRAG', 'PSU23RBUR', 'PSU24DTHO', 'PSU24DYOU', 'PSU24RAND', 'PSU25RWIL', 'PSU26DLUC', 'PSU26RHIC', 'PSU26RWHE', 'PSU27DROP', 'PSU27RBUC', 'PSU27RDUD', 'PSU27RMAR', 'PSU27RPAT', 'PSU28DJAM', 'PSU28DKEY', 'PSU29DLOW', 'PSU29RROB', 'PSU30DCOO', 'PSU30RBEA', 'PSU31DMIL', 'PSU31DPLA', 'PSU31RANA', 'PSU31RDAV', 'PSU32DHET', 'PSU32RKIR', 'PSU33DRHE', 'PSU34DMAR', 'PSU34DWIC', 'PSU35DDES', 'PSU35DHOW', 'PSU35DSOL', 'PSU36DORR', 'PSU36RCOR', 'PSU37DCAS', 'PSU37DNEV', 'PSU37RSET', 'PSU38DKEM', 'PSU38RHEL', 'PSU38RTHO', 'PSU39DHAL', 'PSU39RGUE', 'PSU40DHAR', 'PSU40RMAS', 'PSU41DJAC', 'PSU41DMAD', 'PSU41RNEW', 'PSU42DLEE', 'PSU42RDUN', 'PSU43DAND', 'PSU43DFER', 'PSU43DHEN', 'PSU44DDRA', 'PSU44DTHO', 'PSU44RORA', 'PSU45DTIP', 'PSU45RDIX', 'PSU46DGAU', 'PSU46DSMI', 'PSU46RBRO', 'PSU46RMCK', 'PSU46RMCM', 'PSU47DGIL', 'PSU47RBLA', 'PSU47RGIN', 'PSU48DHOM', 'PSU48DMUR', 'PSU48RSTI', 'PSU49DWAL', 'PSU49RECH', 'PSU50DCOO', 'PSU50RHAT', 'PSU51DLAW', 'PSU51RMIL', 'PSU51RSHA', 'PSU51RWAD', 'PSU52RHUF', 'PSU53DZIB', 'PSU53RBUR', 'PSU53RELS', 'PSU53RTHO', 'PSU54RBRO', 'PSU54RHAL', 'PSU54RPAY', 'PSU55DMAN', 'PSU55RBEN', 'PSU56DTHO', 'PSU56RALB', 'R26GOVRJAC', 'R26GOVRJON', 'R26INSDMAT', 'R26INSDWAI', 'R26LABDPOR', 'R26LABDSAN', 'R26LTGDMCL', 'R26LTGDPAR', 'R26LTGRDOL', 'R26LTGRKEN', 'R26SOSDBAR', 'R26SOSDREY', 'R26SOSRFLE', 'R26SOSRJON', 'R26SUPRLON', 'R26SUPRWOO', 'R26USSRCOL', 'R26USSRDOO', 'RCON01DGRI', 'RCON01DHOL', 'RCON07DKOZ', 'RCON07DNOR', 'RCON11RADK', 'RCON11RCOW', 'RCON12DGEO', 'RCON12DSMI', 'RPSC5RMEH', 'RPSC5RTOL', 'RSL047RCOC', 'RSL047RMIL', 'RSL058DHEN', 'RSL058DSAM', 'RSL062DARN', 'RSL062DCOL', 'RSL068DBAK', 'RSL068DSAB', 'RSL094DKAU', 'RSL094DMAS', 'RSL117DSAN', 'RSL117DSMI', 'RSL177DNAP', 'RSL177DPAY', 'RSU07DGAR', 'RSU07DROM', 'RSU10DJOH', 'RSU10DROG', 'RSU14DABE', 'RSU14DKAN', 'RSU46RMCK', 'RSU46RMCM', 'RSU51RMIL', 'RSU51RWAD']