In [1]:
import geopandas as gp
import pandas as pd
import os
import numpy as np
import re
from collections import Counter
import pber_functions_v1 as pber

# Alabama 2024 Primary Election Results

In [2]:
results = pd.read_csv("./al_2024_prim_prec_csv/al_2024_prim_prec_csv.csv")

In [3]:
jefferson = results[results["County"]=="Jefferson"].copy()
others = results[results["County"]!="Jefferson"].copy()
races = [i for i in list(results.columns) if i not in ["UNIQUE_ID","COUNTYFP","County","Precinct"]]

In [4]:
jefferson_absentee = jefferson[jefferson["Precinct"].str.contains("ABSENTEE") | jefferson["Precinct"].str.contains("PROVISIONAL")].copy(deep = True)

In [5]:
jefferson_absentee

,UNIQUE_ID,COUNTYFP,County,Precinct,P24A01NO,P24A01YES,P24CFJRSTE,P24CFJRTAY,P24CR2RAND,P24CR2RGOV,...,PCON06RPAL,PCON06RWIL,PCON07DDAV,PCON07DSEW,PCON07RHOR,PCON07RLIT,RCON02DDAN,RCON02DFIG,RCON02RBRE,RCON02RDOB
960,073-:-BESSEMER ABSENTEE,73,Jefferson,BESSEMER ABSENTEE,321,173,42,32,25,29,...,5,1,16,428,20,32,0,0,0,0
961,073-:-BIRMINGHAM ABSENTEE,73,Jefferson,BIRMINGHAM ABSENTEE,451,402,173,97,118,120,...,192,27,107,448,25,15,0,0,0,0
1137,073-:-PROVISIONAL,73,Jefferson,PROVISIONAL,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
jefferson_absentee_divs = jefferson_absentee[jefferson_absentee["Precinct"].str.contains("BESSEMER") | jefferson_absentee["Precinct"].str.contains("BIRMINGHAM")].copy(deep = True)
jefferson_absentee_cnty = jefferson_absentee[~jefferson_absentee["Precinct"].str.contains("BESSEMER") & ~jefferson_absentee["Precinct"].str.contains("BIRMINGHAM")].copy(deep = True)

In [7]:
jefferson_absentee_divs_bess = jefferson_absentee_divs[jefferson_absentee_divs["Precinct"].str.contains("BESSEMER")].copy(deep = True)
jefferson_absentee_divs_birm = jefferson_absentee_divs[jefferson_absentee_divs["Precinct"].str.contains("BIRMINGHAM")].copy(deep = True)

In [8]:
jefferson_allocate = jefferson[~(jefferson["Precinct"].str.contains("ABSENTEE")) & ~(jefferson["Precinct"].str.contains("PROVISIONAL"))].copy(deep = True)

In [9]:
jefferson_allocate

,UNIQUE_ID,COUNTYFP,County,Precinct,P24A01NO,P24A01YES,P24CFJRSTE,P24CFJRTAY,P24CR2RAND,P24CR2RGOV,...,PCON06RPAL,PCON06RWIL,PCON07DDAV,PCON07DSEW,PCON07RHOR,PCON07RLIT,RCON02DDAN,RCON02DFIG,RCON02RBRE,RCON02RDOB
962,073-:-PREC 1010 - HUFFMAN BAPTIST CH,73,Jefferson,PREC 1010 - HUFFMAN BAPTIST CH,578,565,174,104,114,135,...,0,0,51,861,148,99,0,0,0,0
963,073-:-PREC 1020 - TOM BRADFORD PARK,73,Jefferson,PREC 1020 - TOM BRADFORD PARK,446,383,160,67,84,117,...,214,13,0,0,0,0,0,0,0,0
964,073-:-PREC 1030 - L_M_ SMITH MIDDLE,73,Jefferson,PREC 1030 - L_M_ SMITH MIDDLE,450,213,51,12,28,32,...,0,0,22,588,35,23,0,0,0,0
965,073-:-PREC 1040 - BETHEL BAPTIST CHU,73,Jefferson,PREC 1040 - BETHEL BAPTIST CHU,595,243,8,4,4,7,...,0,0,48,799,8,3,0,0,0,0
966,073-:-PREC 1050 - MIDFIELD COMMUNITY,73,Jefferson,PREC 1050 - MIDFIELD COMMUNITY,384,177,36,10,19,24,...,0,0,23,493,29,13,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132,073-:-PREC 5230 - HOOVER PUBLIC LIBR,73,Jefferson,PREC 5230 - HOOVER PUBLIC LIBR,137,172,127,100,88,95,...,196,23,0,0,0,0,0,0,0,0
1133,073-:-PREC 5240 - SHADES CAHABA ELEM,73,Jefferson,PREC 5240 - SHADES CAHABA ELEM,173,273,177,142,108,147,...,257,46,0,0,0,0,0,0,0,0
1134,073-:-PREC 5250 - CHURCH OF THE HIGH,73,Jefferson,PREC 5250 - CHURCH OF THE HIGH,210,289,201,188,130,194,...,322,57,0,0,0,0,0,0,0,0
1135,073-:-PREC 5260 - CANTERBURY UNITED,73,Jefferson,PREC 5260 - CANTERBURY UNITED,241,418,321,273,158,330,...,509,62,0,0,0,0,0,0,0,0
1136,073-:-PREC 5280 - BIRMINGHAM BOTANIC,73,Jefferson,PREC 5280 - BIRMINGHAM BOTANIC,79,116,85,75,41,84,...,120,17,0,0,0,0,0,0,0,0

In [10]:
#jefferson_allocate[["UNIQUE_ID","County"]].to_csv("./jefferson_precs.csv", index = False)

In [11]:
jefferson_divisions = pd.read_csv("./raw-from-source/jefferson_divisions.csv")
jefferson_divisions.drop(["County"], axis = 1, inplace = True)

In [12]:
jefferson_divisions["Division"].value_counts()

Division
BIRMINGHAM    121
BESSEMER       43
BOTH           11
Name: count, dtype: int64

In [13]:
jefferson_divisions["Division2"] = np.where(jefferson_divisions["Division"]=="BOTH","BIRMINGHAM",jefferson_divisions["Division"])
jefferson_divisions["Division1"] = np.where(jefferson_divisions["Division"]=="BOTH","BESSEMER",jefferson_divisions["Division"])

In [14]:
jefferson_allocate_full = pd.merge(jefferson_allocate,jefferson_divisions,on="UNIQUE_ID", how = "outer", indicator = True)

In [15]:
jefferson_allocate_full.drop("_merge", axis = 1, inplace = True)

In [16]:
birmingham_precs = jefferson_allocate_full[jefferson_allocate_full["Division2"]=="BIRMINGHAM"].copy(deep = True)
bessemer_precs = jefferson_allocate_full[jefferson_allocate_full["Division1"]=="BESSEMER"].copy(deep = True)

In [17]:
birmingham_precs_allocated = pber.allocate_absentee(birmingham_precs, jefferson_absentee_divs_birm, races, "COUNTYFP")
bessemer_precs_allocated = pber.allocate_absentee(bessemer_precs, jefferson_absentee_divs_bess, races, "COUNTYFP")

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:234: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_allocate = int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==race_district][race])
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:234: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_allocate = int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==race_district][race])

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))

In [18]:
for prec in set(birmingham_precs_allocated[birmingham_precs_allocated["Division"]=="BOTH"]["UNIQUE_ID"]):
    for race in races:
        print(birmingham_precs_allocated.loc[birmingham_precs_allocated["UNIQUE_ID"]==prec,race].values[0])
        print(results.loc[results["UNIQUE_ID"]==prec,race].values[0])
        birmingham_precs_allocated.loc[birmingham_precs_allocated["UNIQUE_ID"]==prec,race] -= results.loc[results["UNIQUE_ID"]==prec,race].values[0]
        print(birmingham_precs_allocated.loc[birmingham_precs_allocated["UNIQUE_ID"]==prec,race].values[0])
        print("")

326
322
4

245
242
3

76
75
1

60
60
0

61
60
1

52
52
0

69
68
1

49
49
0

427
418
9

17
16
1

15
15
0

0
0
0

0
0
0

1
1
0

59
58
1

2
2
0

0
0
0

94
93
1

2
2
0

64
63
1

67
67
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

39
36
3

421
412
9

65
64
1

48
48
0

0
0
0

0
0
0

0
0
0

0
0
0

130
128
2

55
54
1

0
0
0

1
1
0

0
0
0

1
1
0

1
1
0

0
0
0

182
178
4

5
5
0

4
4
0

0
0
0

0
0
0

0
0
0

1
1
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

1
1
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

7
7
0

183
179
4

1
1
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

290
286
4

362
357
5

326
323
3

247
245
2

228
226
2

246
244
2

277
274
3

190
189
1

79
77
2

3
3
0

14
14
0

1
1
0

1
1
0

17
17
0

164
162
2

3
3
0

0
0
0

442
439
3

12
12
0

348
345
3

213
212
1

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

41
40
1

495
491
4

64
63
1

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

51
50
1

62
61
1

34
34
0

43
43
0

34
34
0

35
35
0

31
31
0

36
36
0

33
32
1

3
3
0

3
3
0

0
0
0

0
0
0

1
1
0

22
22
0

0
0
0

1
1
0

57
57
0

2
2
0

42
42
0

34
34
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

4
4
0

70
69
1

3
3
0

0
0
0

0
0
0

1
1
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

456
450
6

165
163
2

6
6
0

3
3
0

3
3
0

5
5
0

2
2
0

6
6
0

589
576
13

16
15
1

21
21
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

8
8
0

1
1
0

4
4
0

4
4
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

30
28
2

599
587
12

7
7
0

1
1
0

0
0
0

0
0
0

0
0
0

0
0
0

253
250
3

178
176
2

290
288
2

155
154
1

210
208
2

189
188
1

238
236
2

155
154
1

9
9
0

1
1
0

1
1
0

0
0
0

3
3
0

3
3
0

32
31
1

0
0
0

0
0
0

439
436
3

3
3
0

266
263
3

182
181
1

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

3
3
0

8
8
0

243
241
2

146
145
1

0
0
0

0
0
0

0
0
0

0
0
0

87
86
1

172
170
2

4
4
0

1
1
0

1
1
0

4
4
0

3
3
0

2
2
0

255
249
6

4
4
0

6
6
0

0
0
0

0
0
0

0
0
0

3
3
0

0
0
0

0
0
0

2
2
0

0
0
0

5
5
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

13
12
1

254
249
5

3
3
0

2
2
0

0
0
0

0
0
0

0
0
0

0
0
0

366
361
5

470
464
6

352
349
3

241
239
2

263
261
2

238
236
2

292
289
3

205
204
1

225
220
5

7
7
0

17
17
0

2
2
0

0
0
0

17
17
0

171
169
2

2
2
0

0
0
0

466
463
3

15
15
0

354
351
3

249
248
1

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

1
1
0

0
0
0

20
19
1

220
215
5

247
245
2

247
245
2

0
0
0

0
0
0

0
0
0

0
0
0

388
383
5

445
439
6

385
382
3

291
289
2

243
241
2

312
310
2

289
286
3

253
251
2

138
135
3

8
8
0

26
25
1

0
0
0

0
0
0

21
20
1

183
180
3

3
3
0

1
1
0

536
533
3

14
14
0

357
354
3

305
303
2

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

66
65
1

574
570
4

68
67
1

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

74
73
1

72
71
1

67
66
1

34
34
0

43
43
0

45
45
0

44
44
0

45
45
0

49
48
1

1
1
0

1
1
0

0
0
0

0
0
0

0
0
0

7
7
0

0
0
0

0
0
0

107
106
1

0
0
0

69
68
1

36
36
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

4
4
0

46
45
1

60
59
1

30
30
0

0
0
0

0
0
0

0
0
0

0
0
0

146
144
2

128
126
2

203
201
2

74
73
1

126
125
1

131
130
1

136
135
1

115
114
1

7
7
0

1
1
0

3
3
0

0
0
0

0
0
0

6
6
0

14
14
0

1
1
0

0
0
0

269
267
2

2
2
0

154
153
1

121
120
1

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

0
0
0

1
1
0

9
9
0

141
140
1

112
111
1

0
0
0

0
0
0

0
0
0

0
0
0

In [19]:
jefferson_final = pd.concat([bessemer_precs_allocated,birmingham_precs_allocated])

In [20]:
jefferson_final.drop(["Division","Division2","Division1"], axis = 1, inplace = True)

In [21]:
for race in races:
    print(race)
    jefferson_final[race] = jefferson_final[race].astype(int)

P24A01NO
P24A01YES
P24CFJRSTE
P24CFJRTAY
P24CR2RAND
P24CR2RGOV
P24CV2RHAN
P24CV2RPAR
P24PREDBID
P24PREDPHI
P24PREDUNC
P24PRERBIN
P24PRERCHR
P24PRERDES
P24PRERHAL
P24PRERRAM
P24PRERSTU
P24PRERTRU
P24PRERUNC
P24PSCRCAV
P24PSCRMCC
PCON01RCAR
PCON01RMOO
PCON02DAVE
PCON02DBRA
PCON02DCOL
PCON02DDAN
PCON02DFIG
PCON02DGIV
PCON02DGRA
PCON02DHAR
PCON02DLEN
PCON02DPAT
PCON02DSIM
PCON02RALB
PCON02RBRE
PCON02RDOB
PCON02RDUP
PCON02RGIL
PCON02RHAR
PCON02RSHE
PCON02RTHO
PCON03RBEV
PCON03RNEW
PCON03RROG
PCON04RADE
PCON04RHOL
PCON06RMCF
PCON06RPAL
PCON06RWIL
PCON07DDAV
PCON07DSEW
PCON07RHOR
PCON07RLIT
RCON02DDAN
RCON02DFIG
RCON02RBRE
RCON02RDOB

In [22]:
jefferson_final = jefferson_final.groupby(["UNIQUE_ID","COUNTYFP","County","Precinct"], as_index = False).sum()

In [23]:
others = pd.concat([others, jefferson_final, jefferson_absentee_cnty])

In [24]:
others.reset_index(inplace = True, drop = True)

In [25]:
others_allocate = others[~(others["Precinct"].str.contains("ABSENTEE")) & ~(others["Precinct"].str.contains("PROVISIONAL")) & ~(others["Precinct"].str.contains("PROVSIONAL")) & ~(others["Precinct"].str.contains("PROVISONAL"))].copy(deep = True)

In [26]:
others_absentee = others[(others["Precinct"].str.contains("ABSENTEE")) | (others["Precinct"].str.contains("PROVISIONAL")) | (others["Precinct"].str.contains("PROVSIONAL")) | (others["Precinct"].str.contains("PROVISONAL"))].copy(deep = True)

In [27]:
others_allocated = pber.allocate_absentee(others_allocate, others_absentee, races, "COUNTYFP")

Special allocation used for

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:234: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_allocate = int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==race_district][race])
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:251: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,rem_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:252: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,floor_var]=0.0
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:250: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_receiving_votes.loc[:,add_var]=0.0

 [[91, 'P24PRERBIN']]

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  to_go = int(np.round((int(to_dole_out_totals.loc[to_dole_out_totals[col_allocating]==county][race])-first_allocation.loc[first_allocation.index==county,floor_var])))
/Users/peterhorton/Documents/RDH/pber_local/AL_2024/primary/pber_functions_v1.py:303: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead

In [28]:
others_allocated

,UNIQUE_ID,COUNTYFP,County,Precinct,P24A01NO,P24A01YES,P24CFJRSTE,P24CFJRTAY,P24CR2RAND,P24CR2RGOV,...,PCON06RPAL,PCON06RWIL,PCON07DDAV,PCON07DSEW,PCON07RHOR,PCON07RLIT,RCON02DDAN,RCON02DFIG,RCON02RBRE,RCON02RDOB
0,001-:-10 JONES COMM_ CTR_,1,Autauga,10 JONES COMM_ CTR_,70,73,63,55,64,45,...,86,20,0,0,0,0,0,0,0,0
1,001-:-100 TRINITY METHODIST,1,Autauga,100 TRINITY METHODIST,445,391,449,386,364,308,...,616,123,0,0,0,0,0,0,0,0
2,001-:-110 CENTRAL AL ELECTRIC,1,Autauga,110 CENTRAL AL ELECTRIC,47,71,40,20,24,27,...,52,4,0,0,0,0,0,0,0,0
3,001-:-140 AUTAUGAVILLE VFD,1,Autauga,140 AUTAUGAVILLE VFD,135,134,125,78,87,89,...,167,19,0,0,0,0,0,0,0,0
4,001-:-150 PRATTMONT BAPTIST,1,Autauga,150 PRATTMONT BAPTIST,143,159,155,116,136,103,...,183,65,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105,073-:-PREC 5230 - HOOVER PUBLIC LIBR,73,Jefferson,PREC 5230 - HOOVER PUBLIC LIBR,139,174,128,101,89,96,...,198,23,0,0,0,0,0,0,0,0
2106,073-:-PREC 5240 - SHADES CAHABA ELEM,73,Jefferson,PREC 5240 - SHADES CAHABA ELEM,175,277,179,143,109,148,...,259,47,0,0,0,0,0,0,0,0
2107,073-:-PREC 5250 - CHURCH OF THE HIGH,73,Jefferson,PREC 5250 - CHURCH OF THE HIGH,213,293,203,189,131,195,...,325,58,0,0,0,0,0,0,0,0
2108,073-:-PREC 5260 - CANTERBURY UNITED,73,Jefferson,PREC 5260 - CANTERBURY UNITED,244,424,324,275,159,333,...,513,63,0,0,0,0,0,0,0,0
2109,073-:-PREC 5280 - BIRMINGHAM BOTANIC,73,Jefferson,PREC 5280 - BIRMINGHAM BOTANIC,80,118,86,76,41,85,...,121,17,0,0,0,0,0,0,0,0

In [29]:
for race in races:
    others_allocated[race] = others_allocated[race].astype(int)
    results[race] = results[race].astype(int)
    print(sum(others_allocated[race])-sum(results[race]))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [30]:
pber.county_totals_check(results, "Pre-Alloc", others_allocated, "Post-Alloc", races, "County", full_print=False, method='county')

***Countywide Totals Check***

Counties that match:

['Autauga', 'Baldwin', 'Barbour', 'Bibb', 'Blount', 'Bullock', 'Butler', 'Calhoun', 'Chambers', 'Cherokee', 'Chilton', 'Choctaw', 'Clarke', 'Clay', 'Cleburne', 'Coffee', 'Colbert', 'Conecuh', 'Coosa', 'Covington', 'Crenshaw', 'Cullman', 'Dale', 'Dallas', 'DeKalb', 'Elmore', 'Escambia', 'Etowah', 'Fayette', 'Franklin', 'Geneva', 'Greene', 'Hale', 'Henry', 'Houston', 'Jackson', 'Jefferson', 'Lamar', 'Lauderdale', 'Lawrence', 'Lee', 'Limestone', 'Lowndes', 'Macon', 'Madison', 'Marengo', 'Marion', 'Marshall', 'Mobile', 'Monroe', 'Montgomery', 'Morgan', 'Perry', 'Pickens', 'Pike', 'Randolph', 'Russell', 'Shelby', 'St. Clair', 'Sumter', 'Talladega', 'Tallapoosa', 'Tuscaloosa', 'Walker', 'Washington', 'Wilcox', 'Winston']

In [31]:
others_allocated["COUNTYFP"] = others_allocated["COUNTYFP"].astype(str).str.zfill(3)

In [32]:
others_allocated["UNIQUE_ID"] = others_allocated["County"] + "-:-" + others_allocated["Precinct"]

In [33]:
others_allocated.to_csv("./al_2024_prim_prec_allocated.csv", index = False)

In [34]:
others_allocated

,UNIQUE_ID,COUNTYFP,County,Precinct,P24A01NO,P24A01YES,P24CFJRSTE,P24CFJRTAY,P24CR2RAND,P24CR2RGOV,...,PCON06RPAL,PCON06RWIL,PCON07DDAV,PCON07DSEW,PCON07RHOR,PCON07RLIT,RCON02DDAN,RCON02DFIG,RCON02RBRE,RCON02RDOB
0,Autauga-:-10 JONES COMM_ CTR_,001,Autauga,10 JONES COMM_ CTR_,70,73,63,55,64,45,...,86,20,0,0,0,0,0,0,0,0
1,Autauga-:-100 TRINITY METHODIST,001,Autauga,100 TRINITY METHODIST,445,391,449,386,364,308,...,616,123,0,0,0,0,0,0,0,0
2,Autauga-:-110 CENTRAL AL ELECTRIC,001,Autauga,110 CENTRAL AL ELECTRIC,47,71,40,20,24,27,...,52,4,0,0,0,0,0,0,0,0
3,Autauga-:-140 AUTAUGAVILLE VFD,001,Autauga,140 AUTAUGAVILLE VFD,135,134,125,78,87,89,...,167,19,0,0,0,0,0,0,0,0
4,Autauga-:-150 PRATTMONT BAPTIST,001,Autauga,150 PRATTMONT BAPTIST,143,159,155,116,136,103,...,183,65,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105,Jefferson-:-PREC 5230 - HOOVER PUBLIC LIBR,073,Jefferson,PREC 5230 - HOOVER PUBLIC LIBR,139,174,128,101,89,96,...,198,23,0,0,0,0,0,0,0,0
2106,Jefferson-:-PREC 5240 - SHADES CAHABA ELEM,073,Jefferson,PREC 5240 - SHADES CAHABA ELEM,175,277,179,143,109,148,...,259,47,0,0,0,0,0,0,0,0
2107,Jefferson-:-PREC 5250 - CHURCH OF THE HIGH,073,Jefferson,PREC 5250 - CHURCH OF THE HIGH,213,293,203,189,131,195,...,325,58,0,0,0,0,0,0,0,0
2108,Jefferson-:-PREC 5260 - CANTERBURY UNITED,073,Jefferson,PREC 5260 - CANTERBURY UNITED,244,424,324,275,159,333,...,513,63,0,0,0,0,0,0,0,0
2109,Jefferson-:-PREC 5280 - BIRMINGHAM BOTANIC,073,Jefferson,PREC 5280 - BIRMINGHAM BOTANIC,80,118,86,76,41,85,...,121,17,0,0,0,0,0,0,0,0

In [35]:
set(others_allocated["Precinct"])

{'CHURCH AT CAHABA BEND',
 'PREC 2320 - UNITARIAN UNIVERSA',
 'ANDERSON GYMNASIUM',
 'MOUNTAINBORO VFD',
 'BELGREEN FIRE DEPT_',
 'COUNTY LINE VFD CONG 3',
 'CROSSVILLE SAND MTN RSCH',
 'PREC 5005 - BIRMINGHAM FIRST S',
 'LIVINGSTON CIVIC CTR',
 'LIBERTY BAPTIST CH',
 'MALVERN COMM_ CTR_',
 'REDHILL COMM_ CTR_',
 'HIGHTOGY RIDGE',
 'GLENWOOD SCHOOL GYM',
 'CREOLA SENIOR CTR',
 'MAGNOLIA COMM_ CTR_',
 'PINE RIDGE COMM D-4',
 'GREENPOND FIRE DEPT',
 "PREC 1380 - ST_ MARY'S CATHOLI",
 'CAVE SPRINGS COMM_',
 'MCCARLEY CTR_ 6-1',
 'ELKMONT FIRE DEPT_',
 'UNION FREEWILL BAPTIST',
 'ROCK MILLS',
 'THE WHITESBURG CTR_',
 'PINE APPLE LIBRARY',
 'MOVEMENT CH',
 'SUMMIT',
 'DOTHAN 1ST ASSEMBLY CLC',
 'WHITE PLAINS VFD',
 'STRAIGHT MOUNTAIN',
 'CHURNTOWN',
 'GEIGER TOWN HALL',
 'YELLOW BLUFF CITY HALL',
 'BLAKE COMM CTR',
 'TABERNACLE OF PRAISE',
 'REGENCY CH OF CHRIST',
 'PREC 4025 - TRUSSVILLE CIVIC C',
 'SPRING CREEK VFD',
 'NEW FRANKLIN FIRE DEPT',
 'STRAUGHN HIGH SCHOOL GYM',
 'SHORTERVILLE BAPTIST',
 'ROCK SPRGS_ VOTING',
 'HYTOP TOWN HALL',
 'CTR_ STAR 1ST BAPT_ CONG5',
 'PREC 5280 - BIRMINGHAM BOTANIC',
 'BRILLIANT COMM CTR',
 'PREC 5220 - VESTAVIA CIVIC CEN',
 "HOLLEY'S STORE",
 'SURGINER COMM_ CTR_',
 'WHATLEY BAPT 121_3',
 'HILLABEE BAPTIST CH',
 'BARRETT RD UMC',
 'BEULAH BAPTIST CH',
 'MURPHREE VALLEY',
 'HOPE CHURCH',
 'CARROLLS CRK BAPT CH',
 'LEROY FIRE HOUSE',
 'PREC 5090 - LEEDS FIRST UNITED',
 'OPELIKA SPORTSPLEX',
 'BRUNDIDGE STATION',
 'PREC 5080 - BROOKWOOD BAPTIST',
 'PROSPECT METHODIST CH',
 'PREC 1125 - CENTER POINT SENIO',
 'PREC 2270 - MOUNT ZION MISSION',
 'SULPHER SPRINGS COMM CTR',
 'HERBERT FIRE',
 'CH OF JESUS CHRIST LDS',
 'STOUTS MTN_ BAPT_',
 'PREC 3150 - UNION HILL BAPTIST',
 'OZARK CIVIC CTR_',
 'WIREGRASS PARK',
 'NEWVILLE VT_ HOUSE',
 "MARY'S CROSS ROADS V_ H_",
 'WISE MILL',
 'WHITE HALL TOWN HALL',
 'MONROEVILLE HOUSING',
 'LEVEL PLAINS COMM_ CTR_',
 'DESTINATION CHURCH',
 '1ST BAPTIST CH SATSUMA',
 '90 BOOTH VFD',
 'ROCK RUN CHURCH',
 'CULLMAN CO_ HEALTH DEPT_',
 'JENA FIRE DEPT_',
 'MT CALVARY BAPTIST',
 'ST_ STEPHENS FIRE HOUSE',
 'LINDEN HWY 43',
 'ORRVILLE COMM_ CTR_',
 'TRI-CITY BAPT_',
 'RURAL HOME CO BLDG',
 'MOODY CIVIC CTR_',
 'FLAT ROCK FIRE',
 'FAITH PRESBYTERIAN CH',
 'POPLAR SPRGS CH',
 'PREC 2050 - HARRISON PARK RECR',
 'FRIENDSHIP OLD SCH HOUSE',
 'BYNUM COMM CTR',
 'FAIRVIEW FIRE DEPT_ A-K',
 'JOSEPHINE FIRE DEPT',
 'EUFAULA WATER BOARD',
 'UNIVERSITY BAPT CH',
 'CENTRAL ACTIVITES BLDG',
 'TENBROECK COMM CTR',
 'STEWART',
 'TALLAWEKA BAPT_',
 'PROVIDENCE FIRE DEPT_',
 'CHRISTIAN OUTREACH',
 'SKIPPERVILLE METHODIST',
 'YANTLEY',
 'SANFORD AVE_ GYM',
 'SNEAD',
 'MIFLIN GRAHAM CREEK CTR',
 'ST_ ELMO ELEMENTARY',
 'PREC 5170 - EDGEWOOD ELEMENTAR',
 'QUEEN OF PEACE SCHOOL',
 'PINE GROVE MISSIONARY BAPT',
 'LIMESTONE FAULK',
 'COTTONTON VFD',
 'COATOPA BEL FIRE DEPT',
 'TARENTUM COMM CLUB',
 'LENOX COMM_',
 'RENFROE VFD',
 'FOREST HOME VTG HOUSE',
 'BROOKLYN COMM CTR',
 'BOYS&GIRLS CLUB-PELL CITY',
 'DOWNTOWN CIVIC CTR_',
 'ALLGOOD TOWN HALL',
 'SHOAL CREEK TOWN HALL',
 'PREC 3170 - ALLIANCE COMMUNITY',
 'PEA RIDGE FIRE VOTING CTR',
 'RUSSELLVILLE HIGH',
 'MARLEY MILL FORESTRY',
 'STILLMAN COLLEGE',
 'OXFORD LAKE PK CIVIC CTR',
 'ST_ JOHNS CATHOLIC CH',
 'ESTILL FORK PRINCES STORE',
 'WOODVILLE BOB JONES COMM',
 'BRANTLEY COMM_ CTR',
 'PLEASANT SITE VFD',
 'RAINSVILLE DEKALB CO SCH CLSM',
 'TRULL',
 'PLEASANT HILL COMM CTR',
 'PREC 3140 - VALLEY CREEK BAPTI',
 'WINN FIRE 91_1',
 'ATMORE CITY HALL',
 'PREC 1050 - MIDFIELD COMMUNITY',
 'SR_ MULTIPURPOSE CTR_',
 'INDEPENDENT LIVING CTR',
 'EASTABOGO BAPTIST CH',
 'ARAB SENIOR CTR',
 'PREC 4050 - CLAY COMMUNITY CEN',
 'BUHL VFD STATION',
 'SOMA CH CNG7',
 'CAROLINA CITY HALL',
 'STEELE COMM_ CTR_',
 'CHARITY CHAPEL FIRE HOUSE',
 'LEBANON BAPT CH',
 'BOARD OF ED 25-1',
 'WALL HWY BAPT CH',
 'GROVE OAK CLUB HOUSE',
 'PREC 1240 - MT_ PILGRIM BAPTIS',
 'CARVER COMM_ CTR_',
 'OPINE TALLAHATTA 161_1',
 'FOLEY CIVIC CTR',
 'VAILS',
 'PIKE CO COURTHOUSE',
 '512 ST JAMES METHODIST',
 'ASBURY UN METHODIST',
 'MARLOW/FISHRIVER VFD',
 'GREYSTONE FARMS CLUB',
 'PREC 1290 - NORTH BIRMINGHAM R',
 'PREC 3300 - JOHNS COMMUNITY CE',
 'A & M UNIVERSITY GYM',
 'COURTHOUSE CONF_ ROOM',
 'DEVCO COMM_ CTR_',
 'FAUNSDALE TOWN OFFICE',
 'RIVER FALLS CITY HALL',
 'DODGE ELEMENTARY',
 'NEW HOPE',
 'SAND ROCK TOWN HALL',
 'PREC 2120 - DUNBAR-ABRAMS COMM',
 'WEST CHAMBERS',
 'GATESWOOD FIRE STATION',
 'MCCOLLUM MIDWAY FIRE/RESC',
 'HEALTH DEPT_',
 'LAMON CHAPEL UMC',
 'SULLIGENT CITY HALL NORTH',
 'PREC 4210 - MORRIS SENIOR CITI',
 'FORT PAYNE SENIOR CTR',
 'BRUSHY POND COMM CTR',
 'ALDERSGATE UMC',
 'SUMMERDALE COMM_ CTR',
 'CHILTON BAPT 151_2',
 'PARKWAY BAPT CHURCH',
 'HOBSON CITY- CITY HALL',
 "GROVE HILL NAT'L GUARD",
 'OMAHA',
 'MOLLOY BETTS',
 'PREC 4110 - ROCK SCHOOL CENTER',
 'GOLDEN ACRES BAPT',
 'ONEONTA',
 'HANOVER',
 'PLEVNA/NEW MARKET FIRE DEPT',
 'SPRINGHILL HOUSING',
 'JAMES SEALS JR_ PARK & REC CTR',
 'DAVIDSON HIGH SCH',
 'BEAVERTON CITY HALL SOUTH',
 'NEW ZION BAPT_ 11-1',
 'HENDERSON VOTING CTR #1',
 'WEOGUFKA VOTING HOUSE',
 'ISNEY',
 'ROCK SPRINGS',
 'COLEMAN ASSEM OF GOD',
 'ANTIOCH CH',
 'BOGUELOOSA',
 'CLOPTON COMM_',
 'BUCKSNORT',
 'WEDOWEE CITY HALL',
 '412 UNION CHAPEL AME',
 'PREC 2360 - BESSEMER RECREATIO',
 'MT_ VIEW BAPT',
 'ROUND ISLAND BAPTIST CH',
 'PREC 3035 - BETHEL BAPTIST CHU',
 'EASTERN SHORE BAPT',
 'MUSCADINE VFD',
 '306 EASTDALE BAPT CH',
 'PREC 2340 - THOMPSON MANOR COM',
 'BETHSADIA FIRE DEPT_',
 'IVALEE VFD',
 'MCABEE CTR',
 'LEIGHTON CIVIC CTR',
 'ALBERTA BAPT CH CNG7',
 'EANON VTG HOUSE',
 'GREENS CHAPEL UMC @ BEASON MIL',
 'EWELL FIRE',
 'RUSHENVILLE BAPT_',
 'CANOE CIVIC CLUB',
 'WAINWRIGHT FINCHBURG FD',
 'PREC 5030 - SHADES MOUNTAIN CO',
 'PREC 5015 - HOOVER SENIOR CENT',
 '509 WOODLAND UN METHODIST',
 'HAMILTON REC CTR',
 '210 PINTLALA FIRE',
 'GULF SHORES CIVIC CTR',
 'UNION CHAPEL COMM_ CTR_',
 'UNION GROVE BAPTIST CH',
 'PINE GROVE CHURCH',
 'SAFFORD VFD',
 'LEATHERWOOD RD CIV_',
 'SARDIS SOUTH',
 'ADAMSBURG FIRE DEPT',
 'PERDIDO BEACH VFD',
 'COMMUNITY LIFE',
 'SUGAR CREEK BANGOR',
 'TALLADEGA CENTRAL HS GYM',
 'SEMINOLE FIRE HOUSE',
 '220 UPPER KINGSTON',
 'UNIVERSITY MALL',
 'GURLEY REC CTR',
 'PREC 1030 - L_M_ SMITH MIDDLE',
 'BETHEL BAPT CH',
 'LAVACA',
 'RISE CHURCH',
 'BUENA VISTA VRENDEN',
 'LITTLE ZION CHURCH',
 'BEULAH VTG HOUSE',
 'MT PLEASANT SR_ CTR_',
 '80 FRIENDSHIP BAPTIST',
 'MICHAEL FIGURES COMM CTR',
 'PREC 3280 - BROOKSIDE COMMUNIT',
 'LUSK',
 'MEADOWSMITH LIBRARY',
 'FULTON FIRE',
 'STANDING ROCK',
 'MT_ ZION CHURCH',
 'NEEDMORE VOTING CTR #2',
 'JACKSONVILLE SAFETY COMP',
 'LITTLE VINES CHURCH',
 'GUM POND FIRE STATION',
 'MIDWAY & DAMASCUS VFD',
 'SHILOH COMM BLDG',
 'PREC 5140 - THE CHURCH AT LIBE',
 'COMM CH COTTONDALE',
 'LEVEL ROAD',
 'PLEASANTFIELD COMM_',
 'MACEDONIA BAPT_ FELLOWSHIP',
 'ANTIOCH VOTING',
 'CRANE HILL FIRE DEPT_ COMM BLD',
 'ELM GROVE CHURCH',
 "MCCOLLUM NAT'L GUARD",
 'SRYGLEY CH OF CHRIST',
 'MT_ OLIVE',
 'PREC 2410 - BRYANT CHAPEL AME',
 'COLLINS CHAPEL FS',
 'PREC 1370 - MCALPINE RECREATIO',
 'LINDSEY HALL CH 31-1',
 'FIRE #3 E HIGHLAND D-1',
 "PREC 5180 - SAINT LUKE'S EPISC",
 'GENEVA COUNTY FARM CTR_',
 'MANTUA FIRE DEPT_',
 'PAINT ROCK SR_ CITIZEN',
 'PREC 5230 - HOOVER PUBLIC LIBR',
 'PREC 3200 - MAURICE L_ WEST CO',
 'NAUVOO COMM_ CTR_',
 'HOBSON FIRE HOUSE',
 'PREC 5040 - METROPOLITAN CHURC',
 'CELEBRATIONS',
 'THOMASTON',
 'WILLOWBROOK BAPT CH',
 'GALLOWAY RD COMM CTR',
 'STEMLEY VFD',
 'GATMAN PARK & REC',
 'PREC 1300 - NORTH BIRMINGHAM P',
 'DANVILLE VFD',
 'COURTHOUSE CLANTON',
 'MUNFORD OLD HS GYM',
 'COLETA VALLEY FIRE',
 'NEW BROCKTON COMM_',
 'GEORGIA MTN REC_ CTR',
 'CUSSETA',
 'CHISHOLM COMM CTR',
 'HOPE VALLEY BIBLE CH',
 'SANDY RIDGE COMMUNITY',
 'CATAWBA SPRINGS',
 'PETERSON COMM CH',
 'GWC HOMES CTR_',
 'FRUITHURST CITY HALL',
 'DIST 4 COMM CTR',
 'SIMCOE COMM CTR',
 'BON AIR BAPTIST CH',
 'PREC 3080 - THE STATION CHURCH',
 '406 NEWTOWN COMM CTR',
 'PREC 3010 - HOOVER MET BASEBAL',
 'HATTON BAPT_',
 'EVANGEL PRESBY_ CH',
 'BAKERHILL TOWN HALL',
 'HARBIN FARM CTR',
 'GOODMAN VTG HOUSE',
 '404 ASU ACADOME',
 'UNITY BAPT CH',
 'TOXEY',
 'WEHADKEE',
 'PEARSON CHAPEL',
 'DUTTON CITY HALL',
 'VFW POST #3128',
 'COLONY ED_ COMPLEX',
 'PREC 1210 - GLEN OAKS ELEMENTA',
 'PREC 4140 - LEEDS CIVIC CENTER',
 'WAGARVILLE FIRE HOUSE',
 'TUTWILER FIRE DEPT_',
 'PREC 4045 - FAITH COMMUNITY FE',
 '201 ST PAUL AME CH',
 'SEMMES COMM_ CTR',
 'WILSONVILLE UMC',
 'DANIELS CHAPEL FELLOWSHIP',
 'HURTSBORO CITY VFD',
 'SUMMERFIELD VFD',
 'RANGEDALE CTR_',
 'TRINITY UMC',
 'TRIANA CITY HALL',
 'SARDIS SPRINGS BAPTIST',
 'LEE CO_ LEARNING CTR',
 'PREC 2300 - BUSH HILLS ACADEMY',
 'ARLINGTON PRESBYTERIAN',
 '401 ST_ JAMES BAPT CH',
 'TATE SCHOOL',
 'HIBBETT SCHOOL CONG5',
 'SEMAN CONG_ CHRISTIAN',
 'LAMB OF GOD LUTHERAN CH',
 'PREC 4240 - IRONDALE CITY HALL',
 'PREC 1270 - HOOPER CITY RECREA',
 'HARMONY',
 'PEROTE VOTING BLDG_',
 'PARK VIEW BAPT_',
 'PREC 1150 - ADAMSVILLE SENIOR',
 '101 WILSON COMM & ATHLETIC CTR',
 'ALICEVILLE',
 'CALERA BAPTIST CH',
 'SALEM CH OF CHRIST ACTIVITY',
 'DADEVILLE REC CTR',
 'BLUE RIDGE BAPT_',
 'FAIRVIEW CH',
 '301 DALRAIDA BAPTIST CH',
 'ELAMVILLE VFD',
 'CROSSROADS',
 'EBENEZER MISS_ BAPTIST',
 'PREC 1220 - WILLOW WOOD RECREA',
 'SHEFFIELD BD OF ED',
 'JONESBORO BAPT_ CHURCH',
 'OLD TEXAS CC SIMPKINS',
 'PREC 1250 - FORESTDALE FIRE ST',
 'TONEY UMC',
 'ROCKY CREEK VTG HOUSE',
 'FRIENDSHIP CHURCH',
 'DIXIE VFD',
 'CRAIGHEAD ELEMENTARY CONG 2',
 'CHURCH AT BROOKHILLS',
 'McCORDS CROSSROADS',
 'CHELSEA COMM_ CTR_',
 'JACKSON DOWNTOWN CONG 7',
 'CHAPEL HILL BAPT',
 'JACKSON CITY HALL CONG 7',
 'NEW HOPE CUMBERLAND',
 'HOLLINS COMM_ CTR_',
 'HEFLIN RECREATIONAL CTR',
 'OLD FIELD CHURCH',
 'COLD SPRGS COMM CTR',
 'ELBA CH OF CHRIST',
 'PREC 2040 - ENSLEY PARK RECREA',
 'TOOMEY',
 'HELENA COMM_ CTR_',
 'GULF SHORES CULTURAL',
 'HOUSTON METHODIST CH',
 'LYEFFION FIRE',
 'AUBURN SOCCER COMPLEX',
 'COKER TOWN HALL',
 'ST_ FLORIAN SR CTR_ CONG5',
 'PREC 4200 - FULTONDALE SENIOR',
 'FLATWOODS COMM_ CTR_',
 'FOUNDERS CLUBHOUSE',
 'MORNING STAR 111_1 CONG7',
 'COVIN BAPT CHURCH',
 'FAIRVIEW SIZEMORE',
 'SOUTHWOOD PRESBYTERIAN',
 'OLD MERRITT SCHOOL',
 'EVANS MEMORIAL CIVIC CTR_',
 'RANGELINE BAPTISIT CH',
 'PICKENSVILLE',
 'CVCC',
 'SHOTTSVILLE FIRE',
 'WINFIELD COMM CTR',
 'PREC 2220 - GLEN IRIS ELEMENTA',
 'RED CREEK FIRE HOUSE',
 'LESTER TOWN HALL',
 'PREC 1360 - NORTH AVONDALE PUB',
 'HUXFORD MASONIC',
 'GILMORE VTG HOUSE',
 'SPENCER REC CTR',
 'EAGLE CREEK V_ H_',
 'JEMISON CITY HALL',
 'GOSHEN METHODIST',
 'POINT MALLARD EVENT CTR',
 'PELHAM CIVIC COMPLEX',
 'INTERGRAPH CORP_',
 'NETTLESBORO 112_2 CONG2',
 'MT CALVARY BAPT_ CHURCH',
 'CANE CREEK GAP OF MTN',
 'WILLIE B_ MCCANTS PLACE',
 'JACKSONS GAP V_F_D_',
 'WESTMEADE BAPT CH',
 'ORANGE BEACH EVENT CTR',
 'BREMEN FIRE DEPT_',
 'FREEMAN TAB 26-1',
 'WALTER COMM CTR',
 'PINE GROVE BAPT CH',
 'NORTH VALLEY CH',
 'LATON HILL FIRE HOUSE',
 'DOTHAN CIVIC CTR',
 'PREC 5035 - FULLNESS CHRISTIAN',
 'COLLIER ELEMENTARY',
 'PREC 3130 - SHADES CREST BAPTI',
 'BETHEL COMM CTR',
 'CEDAR GROVE BAPTIST CH',
 'LIBERTY HILL CH',
 'PREC 2245/3060 - BESSEMER CIVI',
 'BELK ACTIVITY CTR',
 'FORDS-REHOBETH BAPT',
 'PREC 1330 - MORTON SIMPSON COM',
 'MT_ HEBRON FIRE DEPT_',
 'PREC 5120 - SHADES MOUNTAIN BA',
 'BARTON FIRST BAPT_',
 'HARVEST CH OF GOD',
 'WILLS VALLEY REC CTR',
 'MOUNDVILLE COMMUNITY CTR',
 'MARBLE VALLEY VFD',
 'AMER LEGION BLDG POST 15',
 'GUNTERSVILLE REC_ CTR',
 'DELMAR FIRE DEPT',
 'WESTSIDE BAPT_',
 'MT_ WEISNER FIRE HALL',
 'FELLOWSHIP BAPTIST',
 'PINE MOUNTAIN',
 'NEW LIFE BAPT CH',
 'HAYDEN',
 'OAK GROVE BAPT',
 'GOOD HOPE CITY HALL',
 'DETROIT CITY HALL',
 'VINEMONT COMM CTR',
 'BERTHA NEW HOPE',
 'PREC 3070 - MT_ OLIVE COMMUNIT',
 'WEAVER MEETING CTR',
 'FIVE POINTS',
 '405 HOUSTON HILLS CC',
 'STATION #2 CARROLLS CRK',
 'OAKWOOD UNIVERSITY CH',
 'MAG SPGS REDEMPTION CH',
 'ASBURY FIRE',
 'TRI-COUNTY VFD',
 'COTACO FIRE STATION',
 'OAK GROVE',
 'MACEDONIA BAPT #2',
 'ANNISTON MEETING CTR',
 '10 JONES COMM_ CTR_',
 'MUSCLE SHOALS CITY HALL',
 'McDAVID JONES ELEM CONG 2',
 'MILLRY FIRE HOUSE',
 'JOSEPH DOTCH COMM CTR',
 'MADISON CITY HALL',
 'RUSSELLVILLE ELECTRIC',
 'FAIRHOPE CIVIC CTR',
 'CHRIST CHAPEL CH CONG5',
 'CAPSHAW BAPTIST CH',
 'SPRINGHILL VFD',
 'LAFAYETTE',
 'LOCK 5 VFD',
 'DILWORTH COMM_ CTR_',
 'ST_ MARGARET PARRISH',
 'LINDSAY LANE BAPTIST CH',
 'SANTUCK COMM_ CTR_',
 'PINE GROVE CH 36-1',
 'BOYKIN COMM_ CTR',
 'PREC 3285/4130 - WARRIOR STORM',
 'CARVER REC_',
 'NEW HOPE BAPT_',
 'PREC 1010 - HUFFMAN BAPTIST CH',
 'W PARK HEIGHTS BAPT',
 'OWENS CROSS ROADS CH',
 'GERALDINE 1ST BAPT',
 'PREC 2350 - OXMOOR VALLEY COMM',
 'FELLOWSHIP BAPT CH',
 'WEST COOSA SR_ CTR',
 'FAIRVIEW TOWN HALL L-Z',
 '170 CAMELLIA BAPTIST',
 'LOCUST GROVE BAPT CH',
 'WADLEY',
 'PREC 4170 - NORTH POINT COMMUN',
 'W HUNTSVILLE CH CHRIST',
 'HAGLER COMM CTR',
 'BROWNVILLE FIRE',
 'BALDWIN FAMILY LIFE CTR',
 'DEATSVILLE VFD',
 'COVENANT CH CONG4',
 'PREC 3290 - MULGA TOWN HALL',
 'PINEVIEW BAPT CH',
 'BUTLER',
 'FITZPATRICK VFD',
 'MARS HILL/W CHILTON FS',
 'WICKSBURG VFD',
 'NEEDMORE WALDROP CH',
 'COPELAND ASSEMBLY OF GOD',
 'HOLY NAME OF JESUS CH CONG 2',
 'GRANDVIEW COMM CTR',
 'WALLACE HALL GSCC',
 'HENAGAR COMM CTR',
 'MONROVIA COMM_ CTR_',
 'LEINKAUF ELEMENTARY',
 'ASBERRY BAPT',
 'CARTERSVILLE FIRE HALL',
 'PREC 3120 - ADAMSVILLE BAPTIST',
 'PREC 5070 - CAHABA HEIGHTS BAP',
 'TUSCUMBIA MULTI-PURPOSE',
 'MORRISON XR FD',
 'SPANISH TRAIL BAPT CH',
 'OLD HERMAN CH',
 'DAYSTAR CH - MADISON',
 'PREC 2140 - NEW BEGINNING CHUR',
 'UNDERWOOD COMM_ CTR CONG4',
 'HONEYCOMB BAPTIST',
 'MT HOPE BAPT_ FELLOW 9-1',
 'SARDIS NORTH',
 "FARMER'S MARKET",
 'COLLEGEDALE CH OF CHRIST',
 'ENON CO BLDG',
 'LANETT',
 'LEESBURG FEMA BLDG_',
 'GARDEN CITY TOWN HALL',
 "ST_ PAUL'S EPISCOPAL CH",
 'MCKESTES COMM CTR',
 'PREC 5260 - CANTERBURY UNITED',
 'INO SR_ CTR_',
 '504 RAMER PUBLIC LIBRARY',
 'PREC 4030 - GREATER GRACE MISS',
 'PUTNAM VTG BOOTH',
 'PREC 3025 - BAPTIST CHURCH OF',
 'OLD UNION CHURCH',
 'MEGARGEL ASSEM OF GOD',
 'BLOUNTSVILLE',
 'SHEFFIELD RECREATION',
 'ST_ LUKE CHRISTIAN CH',
 'COUNTY CAREER TECH',
 '180 OLD KINGSTON VFD',
 'PINE HILL',
 'MT_ GILEAD BAPT CH',
 'LEE-BELK COMM_ CTR_',
 'BLUE SPRGS HORN HILL',
 '107 TRENHOLM COMM COLLEGE',
 '508 PINE LEVEL SO MO VFD',
 'HUGHES COMM_ CTR_',
 '303 EASTMONT BAPT CH',
 'EAST PERRY',
 'WEBSTER-WAYSIDE',
 'WING FIRE DEPT_',
 'MCCULLOUGH VFD',
 'PREC 3045 - BIRMINGHAM COMMUNI',
 'PREC 5250 - CHURCH OF THE HIGH',
 'BETHEL ASSEMBLY OF GOD',
 '140 AUTAUGAVILLE VFD',
 'FAYETTE CIVIC CTR_',
 'PREC 4015 - HOPE COMMUNITY CHU',
 'MARGERUM COMMUNITY',
 'HEBRON COMM_ CTR',
 'SACO VFD #2',
 'PREC 4230 - GUIDING LIGHT CHUR',
 '211 RUFUS LEWIS LIBRARY',
 'BETHEL CH OF CHRIST',
 'TYLER COMM_ CTR_',
 'UNION COMM BUILDING',
 'PREC 1100 - SOUTH HAMPTON ELEM',
 'BURROUGHS ELEMENTARY',
 'PREC 1350 - FAIRFIELD CIVIC CE',
 'CRAGFORD FIRE',
 'SPRINGFIELD METHODIST',
 'PALMER PILLANS MIDDLE SCH',
 'RICHARD B_ STONE COMPLEX',
 'ADULT ED_ BLDG_',
 'MCCOO SCHOOL',
 'OHATCHEE 1ST BAPT',
 'NEWBURG',
 'PREC 1180 - BARRETT ELEMENTARY',
 'PREC 2310 - MT_ ZION COMMUNITY',
 '1ST BAPTIST CHURCH',
 'SPRINGVILLE 1ST UNITED',
 'HARRIETT COCKRELL CTR',
 'MAYFIELD FIRE DEPT',
 'SOJOURNER COMM CTR',
 'COWARTS BAPTIST',
 'FIRST SOUTHERN BAPT_',
 'PREC 4070 - TARRANT CITY HALL',
 'WAKEFIELD VFD',
 'COUNTY LINE VFD CONG 6',
 'ALEXANDRIA CIVITAN CLUB',
 'TITUS COMM_ CTR_',
 'SARDIS COMM_ CTR_',
 'LAWRENCE HEALTH DEPT 19-1',
 'MENTAL HEALTH CTR',
 'DANIELVILLE SCH',
 '304 OLD ELAM BAPT CH',
 'MT_ PLEASANT CURRY',
 'SARAGOSSA COMM_ CTR_',
 'CORNERSTONE BAPT CH',
 'SHERROD AVE CH OF CHRIST',
 'LITTLE RIVER SAIL CTR',
 'HOPE CHAPEL A_M_E_Z_',
 'NEWBIA VTG HOUSE',
 'BANKS VOTING CTR #2',
 'MT OLIVE BAPT CH',
 'IDAHO FIRE DEPT_',
 'OURTOWN V_F_D_',
 'NEW HOPE METHODIST',
 'PHIPPS WORK CTR',
 'LEBANON CHAPEL',
 'JACKSON SKIPPER FIRE',
 'LOWNDES CITY DEV OFC',
 'FRIENDSHIP COMM_ CTR_',
 'MORELAND FIRE DEPT_',
 "GREEN'S CROSSROADS",
 'PREC 2130 - MINOR ELEMENTARY S',
 'MT_ SPRINGS',
 'HUGULEY',
 'FISCHER COMM CTR D-1',
 'PREC 5110 - MOUNTAIN BROOK CIT',
 'RAGLAND TOWN HALL',
 'CORONA BAPTIST CH',
 'PREC 3260 - WEST JEFFERSON REC',
 'JOHN J SPARKMAN CIVIC CTR',
 'RICHVILLE VFD',
 'EAST POINT COMM CTR',
 'BURKEVILLE VFD',
 'PETERMAN BAPT CH',
 'AUBURN COMM_ CHURCH',
 'GILBERTOWN',
 'COPELAND BRDG LIBERTY HILL',
 'LITTLE ROCK VFD',
 '102 VAUGHN PARK CH',
 'COALING TOWN HALL',
 'CHELSEA CHURCH OF GOD',
 'ANTIOCH FIRE 102_1',
 'BERRY CIVIC CTR_',
 'GARLAND VFD',
 'AFLAME CH',
 'BOLIGEE FIRE DEPT_',
 'HUGHES VTG HOUSE',
 'NEW HOPE BAPTIST CH',
 'CHRIST CHAPEL CH CONG4',
 'ARITON CITY HALL',
 'CHASE PARK CH OF CHRIST',
 'CH OF THE HIGHLANDS',
 'HAYNEVILLE C_H_ ANNEX',
 'E_R_ DICKSON ELEMENTARY',
 'PREC 5200 - MOUNTAINTOP COMMUN',
 'HOPEWELL',
 'JACKSON CITY HALL CONG 2',
 'MAPLESVILLE LIBRARY',
 'HIGDON N SAND MTN SCHOOL',
 'SULLIGENT CITY HALL SOUTH',
 'UNIONTOWN CITY HALL',
 'JUDSON BAPTIST',
 'DOUBLE SPRINGS MUN_ BLDG',
 'FOSTERS XR',
 'HOWELL SULLINS CH',
 'TEXASVILLE COMM_ CTR_',
 'AMERICAN LEGION BLDG',
 'KINGWOOD CH',
 'YORK SUMTER RESCUE',
 'ST_ FLORIAN SR CTR_ CONG4',
 'DORA CIVIC CTR_',
 'PLEASANT GROVE VFD',
 'CTR_ STAR 1ST BAPT_ CONG4',
 'PREC 3020 - GRACE LIFE BAPTIST',
 'REVELS STORE',
 '305 FRAZER METHODIST',
 'ST_ MATTHEWS PB CH',
 'LANDERSVILLE M_C_ 12-1',
 'SALITPA FIRE 81_1',
 'BROADWAY RECREATION CTR_',
 'MT_ ZION ENRICHMENT CTR',
 'SHOAL CREEK COMM_ CTR_',
 'LAKEWOOD COMM_ CTR_',
 'VICTORY BAPT_',
 'COLLINS-RHODES ELEMENTARY',
 'CUBA COMMUNITY CTR',
 'CHEROKEE RIDGE',
 'ZION REST BAPT CH',
 'INDUSTRY OLD SCH HOUSE',
 'NEW MCLAINS VTG HOUSE',
 'DODGE CITY COMM CTR',
 'ANNISTON THANKFUL BAPT',
 'COFFEVILLE HIGH',
 'RED LEVEL FIRE DEPT_',
 'THARPTOWN BAPT_ CHURCH',
 'F_S_ ERVIN ELEM_',
 'MELVIN',
 'PLEASANT RIDGE VTG',
 'CENTER HILL COMM CTR',
 '506 DAVIS CROSSRDS',
 'CARLOWVILLE MINTER 01501_001',
 'ELDRIDGE CITY HALL',
 'BROWNSBORO BAPT CH',
 "PLEASANT HOME/CATOE'S",
 'WATERMARK EAST',
 'KNOXVILLE FIRE DEPT_',
 "TILLMAN'S CORNER COMM CTR CONG 1",
 'SEVERE',
 'KINSTON CITY HALL',
 'MOULTON CITY HALL 24-1',
 'ROSE HILL COMM_ CTR_',
 '105 ALDERSGATE METHODIST',
 'MOBILE MUSEUM OF ART',
 '511 AUM OUTREACH CTR',
 'BLUE SPRINGS CITY HALL',
 'OXFORD PUBLIC LIBRARY',
 'AKRON CITY HALL',
 'EDWARDSVILLE COMM_',
 'PREC 3015 - HOOVER MET SPORTS',
 'WAVERLY',
 'HIGHLAND HOME FD',
 'ELLIOTT COMM_ CTR_',
 "70 BOONE'S CHAPEL",
 'WOLF SPRING BAPT_ 10-1',
 'TRIMBLE FIRE DEPT_',
 'PLEASANT GRV 14 20 23 27',
 'OAKLAND VFD',
 'COVENANT ACADEMY CONG 2',
 'TOWN CREEK COM_ CTR_ 5-1',
 'CRAWFORD VFD',
 'PREC 4250 - TRAFFORD CITY HALL',
 'MT_ HERMAN',
 'CROSS ROADS COMM CTR',
 'DAMASCUS BOYKIN',
 'PREC 1110 - DON HAWKINS PARK &',
 'ARGUTA COMM_ CTR_',
 'GRANT CITY HALL',
 'PREC 2100/2420 - MEMORIAL PARK',
 'EXCEL ASSEM OF GOD',
 'MT_ ZION BAPT CH',
 'PREC 4020 - TRUSSVILLE FIRST B',
 'ROBINSONS MILL',
 'GANTT CITY HALL',
 'GRAND BAY MIDDLE SCH',
 'CREEKWOOD CH OF CHRIST',
 'PINEDALE VFD',
 '207 HUNTER STATION CC',
 'WALDO CITY HALL',
 'COURTHOUSE ANNEX',
 'J_E_TURNER ELEMENTARY',
 'PREC 3050 - PLEASANT RIDGE BAP',
 'HIGHLAND COPPERMINE',
 'PINE SPRINGS',
 'TWILLEY TOWN CH',
 'TROY PUBLIC LIBRARY',
 'MIDLAND VOTING HALL',
 'WEST POINT COMM CTR',
 'THE VINES MINISTRIES',
 'CLIO CITY HALL',
 'INDIAN CREEK BAPT CH',
 'PREC 1140 - THE GIRLS INC BUIL',
 'KATE SHEPARD ELEMENTARY',
 'PINE LEVEL SR_ CTR_',
 'NATL GUARD ARMORY',
 'HAMPTON COVE CH CHRIST',
 'ROYAL',
 'PREC 2030 - HIGHLAND PARK GOLF',
 'BRANCHVILLE CUMBERLAND',
 'SPARE',
 'PINCKARD TOWN HALL',
 'MT_ OLIVE SUNDERLAND VFD',
 'EUTAW ACTIVITY CTR_',
 'STRICKLAND KINGVILLE',
 'WESTGATE PARK',
 'PINEY GROVE CH 32-1',
 'DIXONS MILLS VFD',
 'BACCUS UNION HALL',
 'BEREA CHURCH OF CHRIST',
 '502 SNOWDOUN VFD',
 'NEEDMOREVOTING CTR #1',
 'ANDALUSIA KIWANIS FAIR',
 'ASHRIDGE FIRE DEPT_',
 'RANGE FIRE',
 'FRANKFORT COMM_ CTR_',
 'ELBA MASONIC LODGE',
 'WALNUT GROVE CHURCH',

In [36]:
results = pd.read_csv("./al_2024_prim_prec_csv/al_2024_prim_prec_csv.csv")

In [37]:
others_allocated = pd.read_csv("./raw-from-source/al_2024_prim_prec_allocated.csv")

In [38]:
others_allocated.sum()

UNIQUE_ID     Autauga-:-10 JONES COMM_ CTR_Autauga-:-100 TRI...
COUNTYFP                                                 139394
County        AutaugaAutaugaAutaugaAutaugaAutaugaAutaugaAuta...
Precinct      10 JONES COMM_ CTR_100 TRINITY METHODIST110 CE...
P24A01NO                                                 360944
                                    ...
PCON07RLIT                                                12986
RCON02DDAN                                                14006
RCON02DFIG                                                21962
RCON02RBRE                                                10471
RCON02RDOB                                                14705
Length: 62, dtype: object

In [39]:
for race in races:
    print(results.sum()[race]-others_allocated.sum()[race])

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [40]:
others_allocated.sum()

UNIQUE_ID     Autauga-:-10 JONES COMM_ CTR_Autauga-:-100 TRI...
COUNTYFP                                                 139394
County        AutaugaAutaugaAutaugaAutaugaAutaugaAutaugaAuta...
Precinct      10 JONES COMM_ CTR_100 TRINITY METHODIST110 CE...
P24A01NO                                                 360944
                                    ...
PCON07RLIT                                                12986
RCON02DDAN                                                14006
RCON02DFIG                                                21962
RCON02RBRE                                                10471
RCON02RDOB                                                14705
Length: 62, dtype: object