In [412]:
import pandas as pd
import geopandas as gp
import os
import numpy as np
import pber_functions_v1 as pdv

In [413]:
holder = []

for file in os.listdir("./raw-from-source/"):
    if ".csv" in file:
        temp = pd.read_csv("./raw-from-source/"+file)
        holder.append(temp)

full_il = pd.concat(holder)

In [414]:
contests = list(full_il[~full_il["ContestName"].isna()]["ContestName"].unique())

In [415]:
keep_contests = ['109TH REPRESENTATIVE',
 '40TH REPRESENTATIVE',
 '42ND REPRESENTATIVE',
 '67TH REPRESENTATIVE',
 '89TH REPRESENTATIVE',
 '33RD REPRESENTATIVE',
 '85TH REPRESENTATIVE',
 '16TH CONGRESS',
 '73RD REPRESENTATIVE',
 '52ND SENATE',
 '27TH REPRESENTATIVE',
 '117TH REPRESENTATIVE',
 '14TH CONGRESS',
 '55TH REPRESENTATIVE',
 '22ND SENATE',
 '59TH REPRESENTATIVE',
 '5TH CONGRESS',
 '1ST SENATE',
 '6TH CONGRESS',
 '40TH SENATE',
 '3RD CONGRESS',
 '86TH REPRESENTATIVE',
 '58TH REPRESENTATIVE',
 '54TH REPRESENTATIVE',
 'PRESIDENT AND VICE PRESIDENT',
 '91ST REPRESENTATIVE',
 '62ND REPRESENTATIVE',
 '60TH REPRESENTATIVE',
 '"Should any candidate appearing on the Illinois ballot for federal, State, or local office be subjec',
 '108TH REPRESENTATIVE',
 '70TH REPRESENTATIVE',
 '72ND REPRESENTATIVE',
 '1ST SUPREME - BURKE VACANCY',
 '4TH SUPREME - GARMAN VACANCY',
 '32ND REPRESENTATIVE',
 '30TH REPRESENTATIVE',
 '56TH REPRESENTATIVE',
 '13TH SENATE',
 '34TH SENATE',
 '103RD REPRESENTATIVE',
 '10TH REPRESENTATIVE',
 '116TH REPRESENTATIVE',
 '84TH REPRESENTATIVE',
 '88TH REPRESENTATIVE',
 '20TH SENATE',
 '5TH REPRESENTATIVE',
 '49TH REPRESENTATIVE',
 '58TH SENATE',
 '45TH REPRESENTATIVE',
 '2ND CONGRESS',
 '27TH SENATE',
 '113TH REPRESENTATIVE',
 '114TH REPRESENTATIVE',
 '37TH REPRESENTATIVE',
 '63RD REPRESENTATIVE',
 '28TH SENATE',
 '23RD REPRESENTATIVE',
 '95TH REPRESENTATIVE',
 '99TH REPRESENTATIVE',
 '77TH REPRESENTATIVE',
 '17TH REPRESENTATIVE',
 '51ST REPRESENTATIVE',
 '17TH CONGRESS',
 '98TH REPRESENTATIVE',
 '94TH REPRESENTATIVE',
 '9TH REPRESENTATIVE',
 '46TH REPRESENTATIVE',
 '82ND REPRESENTATIVE',
 '80TH REPRESENTATIVE',
 '9TH CONGRESS',
 '37TH SENATE',
 '21ST REPRESENTATIVE',
 '44TH REPRESENTATIVE',
 '48TH REPRESENTATIVE',
 '115TH REPRESENTATIVE',
 '96TH REPRESENTATIVE',
 '102ND REPRESENTATIVE',
 '15TH CONGRESS',
 '1ST CONGRESS',
 '79TH REPRESENTATIVE',
 '97TH REPRESENTATIVE',
 '75TH REPRESENTATIVE',
 '6TH REPRESENTATIVE',
 '35TH REPRESENTATIVE',
 '16TH SENATE',
 '83RD REPRESENTATIVE',
 '39TH REPRESENTATIVE',
 '110TH REPRESENTATIVE',
 '2ND REPRESENTATIVE',
 '15TH REPRESENTATIVE',
 '19TH REPRESENTATIVE',
 '31ST SENATE',
 '106TH REPRESENTATIVE',
 '47TH REPRESENTATIVE',
 '111TH REPRESENTATIVE',
 '8TH CONGRESS',
 '7TH REPRESENTATIVE',
 '53RD REPRESENTATIVE',
 '3RD REPRESENTATIVE',
 '118TH REPRESENTATIVE',
 '19TH SENATE',
 '4TH SENATE',
 '11TH CONGRESS',
 '81ST REPRESENTATIVE',
 '16TH REPRESENTATIVE',
 '12TH CONGRESS',
 '36TH REPRESENTATIVE',
 '50TH REPRESENTATIVE',
 '52ND REPRESENTATIVE',
 '10TH SENATE',
 '55TH SENATE',
 '7TH SENATE',
 '76TH REPRESENTATIVE',
 '"Should all medically appropriate assisted reproductive treatments, including, but not limited to, i',
 '74TH REPRESENTATIVE',
 '4TH REPRESENTATIVE',
 '78TH REPRESENTATIVE',
 '38TH REPRESENTATIVE',
 '34TH REPRESENTATIVE',
 '18TH REPRESENTATIVE',
 '"Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $',
 '107TH REPRESENTATIVE',
 '14TH REPRESENTATIVE',
 '25TH SENATE',
 '22ND REPRESENTATIVE',
 '20TH REPRESENTATIVE',
 '12TH REPRESENTATIVE',
 '49TH SENATE',
 '53RD SENATE',
 '13TH CONGRESS',
 '43RD REPRESENTATIVE',
 '57TH REPRESENTATIVE',
 '41ST REPRESENTATIVE',
 '10TH CONGRESS',
 '46TH SENATE',
 '13TH REPRESENTATIVE',
 '105TH REPRESENTATIVE',
 '112TH REPRESENTATIVE',
 '5TH SENATE',
 '29TH REPRESENTATIVE',
 '100TH REPRESENTATIVE',
 '1ST REPRESENTATIVE',
 '25TH REPRESENTATIVE',
 '93RD REPRESENTATIVE',
 '101ST REPRESENTATIVE',
 '65TH REPRESENTATIVE',
 '7TH CONGRESS',
 '87TH REPRESENTATIVE',
 '69TH REPRESENTATIVE',
 '92ND REPRESENTATIVE',
 '90TH REPRESENTATIVE',
 '11TH REPRESENTATIVE',
 '61ST REPRESENTATIVE',
 '8TH REPRESENTATIVE',
 '104TH REPRESENTATIVE',
 '4TH CONGRESS',
 '24TH REPRESENTATIVE',
 '28TH REPRESENTATIVE',
 '68TH REPRESENTATIVE',
 '64TH REPRESENTATIVE',
 '66TH REPRESENTATIVE',
 '43RD SENATE',
 '26TH REPRESENTATIVE',
 '71ST REPRESENTATIVE',
 '31ST REPRESENTATIVE']

In [416]:
il_state = full_il[full_il["ContestName"].isin(keep_contests)]

In [417]:
removed = full_il[~full_il["ContestName"].isin(keep_contests)]

In [418]:
il_state.loc[:,"PrecinctName"] = il_state.loc[:,"PrecinctName"].fillna("NONAME")

In [419]:
il_state["pivot_col"] = il_state["JurisName"] + "-:-" + il_state["PrecinctName"].astype(str)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/2954982048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  il_state["pivot_col"] = il_state["JurisName"] + "-:-" + il_state["PrecinctName"].astype(str)

In [420]:
il_state["CandidateName"] = il_state["CandidateName"].str.upper()
il_state = il_state[~il_state["CandidateName"].isin(['UNDER VOTES', 'OVER VOTES', 'BLANK BALLOTS'])]

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/388221713.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  il_state["CandidateName"] = il_state["CandidateName"].str.upper()

In [421]:
il_state.loc[il_state["CandidateName"]=="WRITE-IN","PartyName"]="OTHER"
il_state["PartyName"] = il_state["PartyName"].str.upper()
il_state["PartyName"] = il_state["PartyName"].str.replace("DEMOCRATIC","DEMOCRAT").str.replace('NONPARTISAN','NON-PARTISAN').str.replace('DEMOCRAT PARTY','DEMOCRAT').str.replace('REPUBLICAN PARTY','REPUBLICAN')

In [422]:
il_state["PartyName"].unique()

array(['REPUBLICAN', 'DEMOCRAT', 'OTHER', 'NON-PARTISAN', 'INDEPENDENT',
       'WORKING CLASS PARTY'], dtype=object)

In [423]:
il_state["cand_id"] = il_state["ContestName"]+"-:-"+il_state["CandidateName"]

In [424]:
non_nan = il_state.loc[~il_state["PartyName"].isna()]
na = il_state.loc[il_state["PartyName"].isna()]

In [425]:
non_nan.shape

(142344, 14)

In [426]:
non_nan_dict = dict(zip(non_nan["ContestName"]+"-:-"+non_nan["CandidateName"],non_nan["PartyName"]))

In [427]:
il_state["PartyName"] = il_state["cand_id"].map(non_nan_dict).fillna(il_state["PartyName"])

In [428]:
il_state.loc[(il_state["PartyName"]=="NON-PARTISAN")&(~il_state["ContestName"].str.contains("amendment")),"PartyName"] = "Other"

In [429]:
nan = il_state.loc[il_state["PartyName"].isna()]
nan.shape

(0, 14)

In [430]:
remaining_cands = {"40TH SENATE-:-PHILIP NAGEL": 'REPUBLICAN',
                  "80TH REPRESENTATIVE-:-ANTHONY DELUCA":"DEMOCRAT",
                  '37TH REPRESENTATIVE-:-PATRICK SHEEHAN':'REPUBLICAN',
'86TH REPRESENTATIVE-:-LAWRENCE "LARRY" WALSH, JR.':'DEMOCRAT',
'80TH REPRESENTATIVE-:-ADAM M. BEATY':'REPUBLICAN',
'38TH REPRESENTATIVE-:-DEBBIE MEYERS-MARTIN':'DEMOCRAT',
'107TH REPRESENTATIVE-:-BRAD HALBROOK':'REPUBLICAN',
'98TH REPRESENTATIVE-:-NATALIE A. MANLEY':'DEMOCRAT',
'86TH REPRESENTATIVE-:-JIM LANHAM':'REPUBLICAN',
'49TH SENATE-:-MEG LOUGHRAN CAPPEL':'DEMOCRAT',
'97TH REPRESENTATIVE-:-HARRY BENTON':'DEMOCRAT',
'19TH SENATE-:-SAMANTHA JEAN GASCA':'REPUBLICAN',
'79TH REPRESENTATIVE-:-JACKIE HAAS':'REPUBLICAN',
'97TH REPRESENTATIVE-:-GABBY SHANAHAN':'REPUBLICAN',
'19TH SENATE-:-MICHAEL E. HASTINGS':'DEMOCRAT',
'49TH SENATE-:-KATIE DEANE-SCHLOTTMAN':'REPUBLICAN',
'71ST REPRESENTATIVE-:-DAN SWANSON':'REPUBLICAN',}

il_state["PartyName"] = il_state["cand_id"].map(remaining_cands).fillna(il_state["PartyName"])

In [431]:
il_state = il_state.loc[il_state["CandidateName"]!="NO CANDIDATE"]

## Name Standardization

In [432]:
# cand_fixes = {"BABETTE U. PEYTON":"BABETTE U PEYTON",
# "JEFFREY A ENGLISH":"JEFFREY A. ENGLISH",
# "CONSTANT CONNOR VLAKANCIC":"CONSTANT 'CONNOR' VLAKANCIC",
# "TORI NICK NICHOLSON":"TORI NICHOLSON",
# 'TORI "NICK" NICHOLSON':"TORI NICHOLSON"}

# il_state["CandidateName"] = il_state["CandidateName"].map(cand_fixes).fillna(il_state["CandidateName"])

In [433]:
il_state["cand_col"] = il_state["ContestName"] + "-:-" + il_state["CandidateName"] + "-:-" + il_state["PartyName"]

In [434]:
il_state_filtered = il_state[(il_state["VoteCount"]>0)]

In [435]:
il_state_filtered

,JurisdictionID,JurisContainerID,JurisName,EISCandidateID,CandidateName,EISContestID,ContestName,PrecinctName,Registration,EISPartyID,PartyName,VoteCount,pivot_col,cand_id,cand_col
0,3,0,BOND,1380,CHARLIE MEIER,2460,109TH REPRESENTATIVE,CENTRAL 1-A,551,12,REPUBLICAN,363,BOND-:-CENTRAL 1-A,109TH REPRESENTATIVE-:-CHARLIE MEIER,109TH REPRESENTATIVE-:-CHARLIE MEIER-:-REPUBLICAN
1,14,0,CLINTON,1380,CHARLIE MEIER,2460,109TH REPRESENTATIVE,SUGAR CREEK 5,992,12,REPUBLICAN,709,CLINTON-:-SUGAR CREEK 5,109TH REPRESENTATIVE-:-CHARLIE MEIER,109TH REPRESENTATIVE-:-CHARLIE MEIER-:-REPUBLICAN
2,14,0,CLINTON,1380,CHARLIE MEIER,2460,109TH REPRESENTATIVE,BREESE 1,910,12,REPUBLICAN,538,CLINTON-:-BREESE 1,109TH REPRESENTATIVE-:-CHARLIE MEIER,109TH REPRESENTATIVE-:-CHARLIE MEIER-:-REPUBLICAN
3,14,0,CLINTON,1380,CHARLIE MEIER,2460,109TH REPRESENTATIVE,BREESE 2,843,12,REPUBLICAN,523,CLINTON-:-BREESE 2,109TH REPRESENTATIVE-:-CHARLIE MEIER,109TH REPRESENTATIVE-:-CHARLIE MEIER-:-REPUBLICAN
4,14,0,CLINTON,1380,CHARLIE MEIER,2460,109TH REPRESENTATIVE,BREESE 3,1400,12,REPUBLICAN,973,CLINTON-:-BREESE 3,109TH REPRESENTATIVE-:-CHARLIE MEIER,109TH REPRESENTATIVE-:-CHARLIE MEIER-:-REPUBLICAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,105,16,CITY OF CHICAGO,755,MICHAEL CRAWFORD,1680,31ST REPRESENTATIVE,Ward 21 Precinct 23,1530,11,DEMOCRAT,696,CITY OF CHICAGO-:-Ward 21 Precinct 23,31ST REPRESENTATIVE-:-MICHAEL CRAWFORD,31ST REPRESENTATIVE-:-MICHAEL CRAWFORD-:-DEMOCRAT
128,105,16,CITY OF CHICAGO,760,CARL R. KUNZ,1680,31ST REPRESENTATIVE,Ward 06 Precinct 13,1063,12,REPUBLICAN,19,CITY OF CHICAGO-:-Ward 06 Precinct 13,31ST REPRESENTATIVE-:-CARL R. KUNZ,31ST REPRESENTATIVE-:-CARL R. KUNZ-:-REPUBLICAN
129,105,16,CITY OF CHICAGO,760,CARL R. KUNZ,1680,31ST REPRESENTATIVE,Ward 18 Precinct 03,624,12,REPUBLICAN,28,CITY OF CHICAGO-:-Ward 18 Precinct 03,31ST REPRESENTATIVE-:-CARL R. KUNZ,31ST REPRESENTATIVE-:-CARL R. KUNZ-:-REPUBLICAN
130,105,16,CITY OF CHICAGO,760,CARL R. KUNZ,1680,31ST REPRESENTATIVE,Ward 18 Precinct 13,1679,12,REPUBLICAN,122,CITY OF CHICAGO-:-Ward 18 Precinct 13,31ST REPRESENTATIVE-:-CARL R. KUNZ,31ST REPRESENTATIVE-:-CARL R. KUNZ-:-REPUBLICAN
131,105,16,CITY OF CHICAGO,760,CARL R. KUNZ,1680,31ST REPRESENTATIVE,Ward 19 Precinct 25,867,12,REPUBLICAN,119,CITY OF CHICAGO-:-Ward 19 Precinct 25,31ST REPRESENTATIVE-:-CARL R. KUNZ,31ST REPRESENTATIVE-:-CARL R. KUNZ-:-REPUBLICAN

In [436]:
il_state_filtered = il_state_filtered[il_state_filtered["PrecinctName"]!="NONAME"]

In [437]:
pivoted_filtered = pd.pivot_table(il_state_filtered, index = ["pivot_col","JurisName"], columns = "cand_col", values = "VoteCount", aggfunc = sum)
pivoted = pd.pivot_table(il_state, index = "pivot_col", columns = "cand_col", values = "VoteCount", aggfunc = sum)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/154044327.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivoted_filtered = pd.pivot_table(il_state_filtered, index = ["pivot_col","JurisName"], columns = "cand_col", values = "VoteCount", aggfunc = sum)
/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/154044327.py:2: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivoted = pd.pivot_table(il_state, index = "pivot_col", columns = "cand_col", values = "VoteCount", aggfunc = sum)

In [438]:
pivoted.reset_index(inplace = True, drop = False)
pivoted_filtered.reset_index(inplace = True, drop = False)

In [439]:
set(pivoted["pivot_col"]).difference(set(pivoted_filtered["pivot_col"]))

{'BOND-:-PRESIDENTIAL BALLOT ONLY',
 'BUREAU-:-PRESIDENTIAL ONLY BALLOT',
 'CASS-:-ARENZVILLE 11-F15',
 'CASS-:-ASHLAND 20-F15',
 'CASS-:-ASHLAND 21-F15',
 'CASS-:-BEARDSTOWN 1-F15',
 'CASS-:-BEARDSTOWN 2-F15',
 'CASS-:-BEARDSTOWN 3-F15',
 'CASS-:-BEARDSTOWN 4-F15',
 'CASS-:-BEARDSTOWN 5-F15',
 'CASS-:-BEARDSTOWN 6-F15',
 'CASS-:-BEARDSTOWN 7-F15',
 'CASS-:-BEARDSTOWN 8-F15',
 'CASS-:-BLUFF SPRINGS 10-F15',
 'CASS-:-CHANDLERVILLE 18-F15',
 'CASS-:-HAGENER 9-F15',
 'CASS-:-NEWMANSVILLE 19-F15',
 'CASS-:-PANTHER CREEK 17-F15',
 'CASS-:-PHILADELPHIA 16-F15',
 'CASS-:-SANGAMON VALLEY 12-F15',
 'CASS-:-VIRGINIA 13-F15',
 'CASS-:-VIRGINIA 14-F15',
 'CASS-:-VIRGINIA 15-F15',
 'CHRISTIAN-:-PRESIDENTIAL ONLY BALLOT',
 'CITY OF GALESBURG-:-NONAME',
 'CLARK-:-PRESIDENTIAL ONLY BALLOT',
 'CLAY-:-PRESIDENTIAL ONLY BALLOT',
 'COLES-:-PRESIDENTIAL ONLY BALLOT',
 'CRAWFORD-:-PRESIDENTIAL ONLY BALLOT',
 'CUMBERLAND-:-COTTONWOOD-F12',
 'CUMBERLAND-:-CROOKED CREEK-F12',
 'CUMBERLAND-:-GREENUP 1-F12',
 'CUMBERLAND-:-GREENUP 2-F12',
 'CUMBERLAND-:-GREENUP 3-F12',
 'CUMBERLAND-:-NEOGA 1-F12',
 'CUMBERLAND-:-NEOGA 2-F12',
 'CUMBERLAND-:-SPRING POINT-F12',
 'CUMBERLAND-:-SUMPTER 1-F12',
 'CUMBERLAND-:-SUMPTER 2-F12',
 'CUMBERLAND-:-UNION-F12',
 'CUMBERLAND-:-WOODBURY-F12',
 'DOUGLAS-:-PRESIDENTIAL ONLY BALLOT',
 'DeWITT-:-PRESIDENTIAL ONLY BALLOT',
 'DuPAGE-:-Addison 049-0206',
 'DuPAGE-:-Bloomingdale 002-0049',
 'DuPAGE-:-Bloomingdale 022-0082',
 'DuPAGE-:-Bloomingdale 036-0100',
 'DuPAGE-:-Bloomingdale 040-0111',
 'DuPAGE-:-Bloomingdale 070-0149',
 'DuPAGE-:-Downers Grove 012-0709',
 'DuPAGE-:-Downers Grove 013-0711',
 'DuPAGE-:-Downers Grove 014-0713',
 'DuPAGE-:-Downers Grove 017-0722',
 'DuPAGE-:-Lisle 003-0588',
 'DuPAGE-:-Lisle 046-0650',
 'DuPAGE-:-Milton 004-0274',
 'DuPAGE-:-Milton 007-0281',
 'DuPAGE-:-Milton 065-0367',
 'DuPAGE-:-Milton 081-0393',
 'DuPAGE-:-Naperville 004-0516',
 'DuPAGE-:-Naperville 004-0518',
 'DuPAGE-:-Naperville 045-0569',
 'DuPAGE-:-PRESIDENTIAL',
 'DuPAGE-:-Winfield 023-0256',
 'DuPAGE-:-York 007-0402',
 'DuPAGE-:-York 008-0405',
 'DuPAGE-:-York 041-0441',
 'DuPAGE-:-York 070-0482',
 'EDGAR-:-PRESIDENTIAL ONLY BALLOT',
 'FORD-:-PRESIDENTIAL ONLY BALLOT',
 'FULTON-:-ASTORIA-F15',
 'FULTON-:-BANNER-F17',
 'FULTON-:-BERNADOTTE-F15',
 'FULTON-:-BUCKHEART-F17',
 'FULTON-:-CANTON  1-F17',
 'FULTON-:-CANTON  2-F17',
 'FULTON-:-CANTON  3-F17',
 'FULTON-:-CANTON  4-F17',
 'FULTON-:-CANTON  5-F17',
 'FULTON-:-CANTON  6-F17',
 'FULTON-:-CANTON  7-F17',
 'FULTON-:-CANTON  8-F17',
 'FULTON-:-CANTON  9-F17',
 'FULTON-:-CANTON 10-F17',
 'FULTON-:-CANTON 11-F17',
 'FULTON-:-CANTON 13-F17',
 'FULTON-:-CANTON 14-F17',
 'FULTON-:-CANTON 15-F17',
 'FULTON-:-CANTON 16-F17',
 'FULTON-:-CASS-F17',
 'FULTON-:-DEERFIELD-F17',
 'FULTON-:-ELLISVILLE-F17',
 'FULTON-:-FAIRVIEW-F17',
 'FULTON-:-FARMERS-F15',
 'FULTON-:-FARMINGTON 1-F17',
 'FULTON-:-FARMINGTON 2-F17',
 'FULTON-:-HARRIS-F17',
 'FULTON-:-ISABEL-F15',
 'FULTON-:-JOSHUA-F17',
 'FULTON-:-KERTON-F15',
 'FULTON-:-LEE TWP-F17',
 'FULTON-:-LEWISTOWN 2-F15',
 'FULTON-:-LEWISTOWN 3-F15',
 'FULTON-:-LIVERPOOL-F15',
 'FULTON-:-ORION-F17',
 'FULTON-:-PLEASANT-F15',
 'FULTON-:-PUTMAN-F17',
 'FULTON-:-VERMONT-F15',
 'FULTON-:-WATERFORD-F15',
 'FULTON-:-WOODLAND-F15',
 'FULTON-:-YOUNG HICKORY-F17',
 'GREENE-:-ATHENSVILLE 1-F15',
 'GREENE-:-BLUFFDALE 1-F15',
 'GREENE-:-CARROLLTON 1-F15',
 'GREENE-:-CARROLLTON 3-F15',
 'GREENE-:-KANE 1-F15',
 'GREENE-:-KANE 2-F15',
 'GREENE-:-LINDER 1-F15',
 'GREENE-:-PATTERSON 1-F15',
 'GREENE-:-ROCKBRIDGE 1-F15',
 'GREENE-:-ROCKBRIDGE 3-F15',
 'GREENE-:-ROODHOUSE 1-F15',
 'GREENE-:-ROODHOUSE 2-F15',
 'GREENE-:-ROODHOUSE 3-F15',
 'GREENE-:-RUBICON 1-F15',
 'GREENE-:-WALKERVILLE 1-F15',
 'GREENE-:-WHITE HALL 1-F15',
 'GREENE-:-WHITE HALL 3-F15',
 'GREENE-:-WOODVILLE 1-F15',
 'GREENE-:-WRIGHTS 2-F15',
 'GRUNDY-:-AUX SABLE 02-F16',
 'GRUNDY-:-AUX SABLE 03-F16',
 'GRUNDY-:-AUX SABLE 04-F16',
 'GRUNDY-:-AUX SABLE 05-F16',
 'GRUNDY-:-AUX SABLE 06-F16',
 'GRUNDY-:-AUX SABLE 07-F16',
 'GRUNDY-:-BRACEVILLE 01-F16',
 'GRUNDY-:-BRACEVILLE 02-F16',
 'GRUNDY-:-BRACEVILLE 03-F16',
 'GRUNDY-:-BRACEVILLE 04-F16',
 'GRUNDY-:-ERIENNA 02-020',
 'GRUNDY-:-ERIENNA 02-F16',
 'GRUNDY-:-FELIX 01-F16',
 'GRUNDY-:-FELIX 02-F16',
 'GRUNDY-:-FELIX 03-F16',
 'GRUNDY-:-FELIX 04-F16',
 'GRUNDY-:-GARFIELD 01-F16',
 'GRUNDY-:-GOODFARM 01-F16',
 'GRUNDY-:-GOOSE LAKE 01-F16',
 'GRUNDY-:-GREENFIELD 01-F16',
 'GRUNDY-:-MAINE 01-F16',
 'GRUNDY-:-MAZON 01-F16',
 'GRUNDY-:-MORRIS 01-F16',
 'GRUNDY-:-MORRIS 02-F16',
 'GRUNDY-:-MORRIS 03-F16',
 'GRUNDY-:-MORRIS 04-F16',
 'GRUNDY-:-MORRIS 05-F16',
 'GRUNDY-:-NETTLE CREEK 01-F16',
 'GRUNDY-:-NORMAN 01-F16',
 'GRUNDY-:-SARATOGA 01-F16',
 'GRUNDY-:-SARATOGA 02-F16',
 'GRUNDY-:-SARATOGA 03-F16',
 'GRUNDY-:-SARATOGA 05-F16',
 'GRUNDY-:-WAUPONSEE 01-F16',
 'HARDIN-:-PRESIDENTIAL ONLY BALLOT',
 'IROQUOIS-:-ARTESIA-F2',
 'IROQUOIS-:-ASHKUM 2-F2',
 'IROQUOIS-:-BEAVER-F2',
 'IROQUOIS-:-BEAVERVILLE-F2',
 'IROQUOIS-:-BELMONT 1-F2',
 'IROQUOIS-:-BELMONT 2-F2',
 'IROQUOIS-:-BELMONT 3-F2',
 'IROQUOIS-:-CHEBANSE 1-F2',
 'IROQUOIS-:-CHEBANSE 2-F2',
 'IROQUOIS-:-CONCORD-F2',
 'IROQUOIS-:-DANFORTH-F2',
 'IROQUOIS-:-DOUGLAS 1-F2',
 'IROQUOIS-:-DOUGLAS 2-F2',
 'IROQUOIS-:-FOUNTAIN CREEK-F2',
 'IROQUOIS-:-LODA-F2',
 'IROQUOIS-:-LOVEJOY-F2',
 'IROQUOIS-:-MARTINTON-F2',
 'IROQUOIS-:-MIDDLEPORT 3-F2',
 'IROQUOIS-:-MIDDLEPORT 4-F2',
 'IROQUOIS-:-MILKS GROVE-F2',
 'IROQUOIS-:-ONARGA 2-F2',
 'IROQUOIS-:-PAPINEAU-F2',
 'IROQUOIS-:-PRAIRIE GREEN-F2',
 'IROQUOIS-:-RIDGELAND-F2',
 'IROQUOIS-:-SHELDON 2-F2',
 'IROQUOIS-:-STOCKLAND-F2',
 'JACKSON-:-BRADLEY - AVA-F12',
 'JACKSON-:-BRADLEY - CAMPBELL HILL-F12',
 'JACKSON-:-CARBONDALE 1-F12',
 'JACKSON-:-CARBONDALE 10-F12',
 'JACKSON-:-CARBONDALE 11-F12',
 'JACKSON-:-CARBONDALE 12-F12',
 'JACKSON-:-CARBONDALE 13-F12',
 'JACKSON-:-CARBONDALE 14-F12',
 'JACKSON-:-CARBONDALE 16-F12',
 'JACKSON-:-CARBONDALE 19-F12',
 'JACKSON-:-CARBONDALE 20-F12',
 'JACKSON-:-CARBONDALE 24-F12',
 'JACKSON-:-CARBONDALE 25-F12',
 'JACKSON-:-CARBONDALE 26-F12',
 'JACKSON-:-CARBONDALE 5-F12',
 'JACKSON-:-CARBONDALE 6-F12',
 'JACKSON-:-CARBONDALE 7-F12',
 'JACKSON-:-CARBONDALE 8-F12',
 'JACKSON-:-DEGOGNIA-F12',
 'JACKSON-:-DESOTO 1-F12',
 'JACKSON-:-DESOTO 2-F12',
 'JACKSON-:-ELK 1-F12',
 'JACKSON-:-ELK 3-F12',
 'JACKSON-:-FOUNTAIN BLUFF-F12',
 'JACKSON-:-GRAND TOWER-F12',
 'JACKSON-:-KINKAID-F12',
 'JACKSON-:-LEVAN-F12',
 'JACKSON-:-MAKANDA 2-F12',
 'JACKSON-:-MAKANDA 3-F12',
 'JACKSON-:-MAKANDA 4-F12',
 'JACKSON-:-MURPHYSBORO 1-F12',
 'JACKSON-:-MURPHYSBORO 10-F12',
 'JACKSON-:-MURPHYSBORO 12-F12',
 'JACKSON-:-MURPHYSBORO 2-F12',
 'JACKSON-:-MURPHYSBORO 4-F12',
 'JACKSON-:-MURPHYSBORO 6-F12',
 'JACKSON-:-MURPHYSBORO 7-F12',
 'JACKSON-:-MURPHYSBORO 8-F12',
 'JACKSON-:-MURPHYSBORO 9-F12',
 'JACKSON-:-ORA-F12',
 'JACKSON-:-POMONA-F12',
 'JACKSON-:-SAND RIDGE-F12',
 'JACKSON-:-SOMERSET 1-F12',
 'JACKSON-:-SOMERSET 2-F12',
 'JACKSON-:-SOMERSET 3-F12',
 'JACKSON-:-SOMERSET 4-F12',
 'JASPER-:-CROOKED CREEK-F12',
 'JASPER-:-FOX-F12',
 'JASPER-:-GRANDVILLE-F12',
 'JASPER-:-GROVE-F12',
 'JASPER-:-HUNT CITY-F12',
 'JASPER-:-NORTH MUDDY-F12',
 'JASPER-:-SMALLWOOD-F12',
 'JASPER-:-SOUTH MUDDY-F12',
 'JASPER-:-STE. MARIE 1-F12',
 'JASPER-:-STE. MARIE 2-F12',
 'JASPER-:-WADE 1-F12',
 'JASPER-:-WADE 2-F12',
 'JASPER-:-WADE 3-F12',
 'JASPER-:-WADE 4-F12',
 'JASPER-:-WILLOW HILL-F12',
 'JOHNSON-:-BELKNAP-F12',
 'JOHNSON-:-BLOOMFIELD-F12',
 'JOHNSON-:-BURNSIDE-F12',
 'JOHNSON-:-CACHE-F12',
 'JOHNSON-:-ELVIRA-F12',
 'JOHNSON-:-GOREVILLE 1-F12',
 'JOHNSON-:-GOREVILLE 2-F12',
 'JOHNSON-:-GRANTSBURG-F12',
 'JOHNSON-:-LAKE 1-F12',
 'JOHNSON-:-LAKE 2-F12',
 'JOHNSON-:-OZARK-F12',
 'JOHNSON-:-SIMPSON-F12',
 'JOHNSON-:-TUNNEL HILL-F12',
 'JOHNSON-:-VIENNA 1-F12',
 'JOHNSON-:-VIENNA 3-F12',
 'KANE-:-AU0001-FEDCD11',
 'KANE-:-AU0009-FEDCD14',
 'KANE-:-BB0002-96',
 'KANE-:-BB0007-102',
 'KANE-:-BU0001-113',
 'KANE-:-CA0004-120',
 'KANE-:-CA0008-126',
 'KANE-:-DU0001-FEDCD8',
 'KANE-:-DU0006-140',
 'KANE-:-EL0031-213',
 'KANE-:-HA0003-273',
 'KANE-:-PL0002-279',
 'KANE-:-RU0005-303',
 'KANE-:-SC0021-343',
 'KANKAKEE-:-PRESIDENTIAL ONLY BALLOT',
 'KNOX-:-ELECTIONS OFFICE',
 'LAWRENCE-:-NONAME',
 'LEE-:-PRESIDENTIAL ONLY BALLOT',
 'LIVINGSTON-:-PRESIDENTIAL ONLY BALLOT',
 'LOGAN-:-PRESIDENTIAL ONLY BALLOT',
 'LaSALLE-:-PRESIDENTIAL ONLY BALLOT',
 'MACOUPIN-:-PRESIDENTIAL ONLY BALLOT',
 'MARSHALL-:-NONAME',
 'MASON-:-PRESIDENTIAL ONLY BALLOT',
 'MASSAC-:-ADKINS-F12',
 'MASSAC-:-BENTON-F12',
 'MASSAC-:-EAST BROOKLYN-F12',
 'MASSAC-:-FRANKLIN-F12',
 "MASSAC-:-GEORGE'S CREEK-F12",
 'MASSAC-:-GRANT-F12',
 'MASSAC-:-HILLERMAN-F12',
 'MASSAC-:-JACKSON-F12',
 'MASSAC-:-JEFFERSON-F12',
 'MASSAC-:-LINCOLN-F12',
 'MASSAC-:-LOGAN-F12',
 'MASSAC-:-METROPOLIS 1-F12',
 'MASSAC-:-METROPOLIS 2-F12',
 'MASSAC-:-METROPOLIS 3-F12',
 'MASSAC-:-METROPOLIS 4-F12',
 'MASSAC-:-WASHINGTON-F12',
 'MASSAC-:-WEST BROOKLYN-F12',
 'MENARD-:-NONAME',
 'MONTGOMERY-:-PRESIDENTIAL ONLY BALLOT',
 'MORGAN-:-ALEX-PRENT-SINC-F15',
 'MORGAN-:-ARCADIA-F15',
 'MORGAN-:-CHAPIN-CONCORD-F15',
 'MORGAN-:-FRANKLIN-F15',
 'MORGAN-:-JACKSONVILLE 01-F15',
 'MORGAN-:-JACKSONVILLE 02-F15',
 'MORGAN-:-JACKSONVILLE 04-F15',
 'MORGAN-:-JACKSONVILLE 05-F15',
 'MORGAN-:-JACKSONVILLE 06-F15',
 'MORGAN-:-JACKSONVILLE 07-F15',
 'MORGAN-:-JACKSONVILLE 08-F15',
 'MORGAN-:-JACKSONVILLE 09-F15',
 'MORGAN-:-JACKSONVILLE 10-F15',
 'MORGAN-:-JACKSONVILLE 11-F15',
 'MORGAN-:-JACKSONVILLE 12-F15',
 'MORGAN-:-LITERBERRY-F15',
 'MORGAN-:-LYNNVL-MARKM-F15',
 'MORGAN-:-MEREDOSIA-F15',
 'MORGAN-:-MURRVL-NORTNVL-5',
 'MORGAN-:-MURRVL-NORTNVL-F15',
 'MORGAN-:-PISGAH-F15',
 'MORGAN-:-S JACKSONVILLE 3-F15',
 'MORGAN-:-WAVERLY 01-4',
 'MORGAN-:-WAVERLY 01-F15',
 'MORGAN-:-WAVERLY 02-F15',
 'MORGAN-:-WOODSON-F15',
 'MOULTRIE-:-PRESIDENTIAL ONLY BALLOT',
 'McDONOUGH-:-BETHEL-F15',
 'McDONOUGH-:-BLANDINSVILLE-F15',
 'McDONOUGH-:-BUSHNELL 1-F15',
 'McDONOUGH-:-ELDORADO-F15',
 'McDONOUGH-:-EMMET-F15',
 'McDONOUGH-:-EMMET-F17',
 'McDONOUGH-:-HIRE-F15',
 'McDONOUGH-:-LAMOINE-F15',
 'McDONOUGH-:-MACOMB CITY #1-F15',
 'McDONOUGH-:-MACOMB CITY #2-F15',
 'McDONOUGH-:-MACOMB CITY #4-F17',
 'McDONOUGH-:-MACOMB CITY #5-F17',
 'McDONOUGH-:-MOUND-F15',
 'McDONOUGH-:-MOUND-F17',
 'McDONOUGH-:-NEW SALEM-F15',
 'McDONOUGH-:-PRAIRIE CITY-F15',
 'McDONOUGH-:-SCIOTA-F15',
 'McDONOUGH-:-SCOTLAND-F15',
 'McDONOUGH-:-SCOTLAND-F17',
 'McDONOUGH-:-TENNESSEE-42',
 'McDONOUGH-:-TENNESSEE-F15',
 'OGLE-:-PRESIDENTIAL ONLY BALLOT',
 'PEORIA-:-BR01 FED ONLY',
 'PEORIA-:-CH01 FED ONLY',
 'PEORIA-:-CH02 FED ONLY',
 'PEORIA-:-CH03 FED ONLY',
 'PEORIA-:-CH04 FED ONLY',
 'PEORIA-:-CH05 FED ONLY',
 'PEORIA-:-CH06 FED ONLY',
 'PEORIA-:-EL01 FED ONLY',
 'PEORIA-:-EL02 FED ONLY',
 'PEORIA-:-HA01 FED ONLY',
 'PEORIA-:-HO01 FED ONLY',
 'PEORIA-:-JU01 FED ONLY',
 'PEORIA-:-JU02 FED ONLY',
 'PEORIA-:-KI01 16TH FED ONLY',
 'PEORIA-:-KI01 17TH FED ONLY',
 'PEORIA-:-KI02 FED ONLY',
 'PEORIA-:-LI01 16TH FED ONLY',
 'PEORIA-:-LI01 17TH FED ONLY',
 'PEORIA-:-LI02 16TH FED ONLY',
 'PEORIA-:-LI02 17TH FED ONLY',
 'PEORIA-:-LI03 FED ONLY',
 'PEORIA-:-LI05 FED ONLY',
 'PEORIA-:-LI08 FED ONLY',
 'PEORIA-:-LI09 FED ONLY',
 'PEORIA-:-LI10 FED ONLY',
 'PEORIA-:-LO01 FED ONLY',
 'PEORIA-:-LO02 FED ONLY',
 'PEORIA-:-ME01 FED ONLY',
 'PEORIA-:-ME02 FED ONLY',
 'PEORIA-:-ME03 FED ONLY',
 'PEORIA-:-ME04 FED ONLY',
 'PEORIA-:-MI01 FED ONLY',
 'PEORIA-:-PE01 FED ONLY',
 'PEORIA-:-PE02 FED ONLY',
 'PEORIA-:-PE03 FED ONLY',
 'PEORIA-:-PE04 FED ONLY',
 'PEORIA-:-PE06 FED ONLY',
 'PEORIA-:-PE07 FED ONLY',
 'PEORIA-:-PE08 FED ONLY',
 'PEORIA-:-PE09 FED ONLY',
 'PEORIA-:-PE10 FED ONLY',
 'PEORIA-:-PE14 FED ONLY',
 'PEORIA-:-PE15 FED ONLY',
 'PEORIA-:-PE16 FED ONLY',
 'PEORIA-:-PE17 FED ONLY',
 'PEORIA-:-PE18 FED ONLY',
 'PEORIA-:-PE19 FED ONLY',
 'PEORIA-:-PE20 FED ONLY',
 'PEORIA-:-PE21 - 86',
 'PEORIA-:-PE21 FED ONLY',
 'PEORIA-:-PE22 FED ONLY',
 'PEORIA-:-PE23 FED ONLY',
 'PEORIA-:-PE24 FED ONLY',
 'PEORIA-:-PE25 FED ONLY',
 'PEORIA-:-PE26 FED ONLY',
 'PEORIA-:-PE29 FED ONLY',
 'PEORIA-:-PE34 FED ONLY',
 'PEORIA-:-PE35 FED ONLY',
 'PEORIA-:-PE36 FED ONLY',
 'PEORIA-:-PE37 FED ONLY',
 'PEORIA-:-PE38 FED ONLY',
 'PEORIA-:-PE39 FED ONLY',
 'PEORIA-:-PE41 FED ONLY',
 'PEORIA-:-PE42 FED ONLY',
 'PEORIA-:-PE44 FED ONLY',
 'PEORIA-:-PE45 FED ONLY',
 'PEORIA-:-PE46 FED ONLY',
 'PEORIA-:-PE47 - 125',
 'PEORIA-:-PE47 FED ONLY',
 'PEORIA-:-PE48 FED ONLY',
 'PEORIA-:-PE50 FED ONLY',
 'PEORIA-:-PE51 - 140',
 'PEORIA-:-PE51 FED ONLY',
 'PEORIA-:-PE52 FED ONLY',
 'PEORIA-:-PE53 FED ONLY',
 'PEORIA-:-PE54 FED ONLY',
 'PEORIA-:-PE56 FED ONLY',
 'PEORIA-:-PE58 FED ONLY',
 'PEORIA-:-PE61 FED ONLY',
 'PEORIA-:-PE62 FED ONLY',
 'PEORIA-:-PE63 FED ONLY',
 'PEORIA-:-PE64 FED ONLY',
 'PEORIA-:-PE65 FED ONLY',
 'PEORIA-:-PR01 - 189',
 'PEORIA-:-PR01 FED ONLY',
 'PEORIA-:-RI01 16TH FED ONLY',
 'PEORIA-:-RI01 17TH FED ONLY',
 'PEORIA-:-RI02 FED ONLY',
 'PEORIA-:-RI03 16TH FED ONLY',
 'PEORIA-:-RI03 17TH FED ONLY',
 'PEORIA-:-RI04 FED ONLY',
 'PEORIA-:-RO01 16TH FED ONLY',
 'PEORIA-:-RO01 17TH FED ONLY',
 'PEORIA-:-TI01 FED ONLY',
 'PEORIA-:-TR01 FED ONLY',
 'PEORIA-:-WP01 FED ONLY',
 'PEORIA-:-WP03 FED ONLY',
 'PERRY-:-BEAUCOUP-F12',
 'PERRY-:-CUTLER-F12',
 'PERRY-:-DUQUOIN 1-F12',
 'PERRY-:-DUQUOIN 10-F12',
 'PERRY-:-DUQUOIN 11-F12',
 'PERRY-:-DUQUOIN 12-F12',
 'PERRY-:-DUQUOIN 2-F12',
 'PERRY-:-DUQUOIN 3-F12',
 'PERRY-:-DUQUOIN 4-F12',
 'PERRY-:-DUQUOIN 5-F12',
 'PERRY-:-DUQUOIN 6-F12',
 'PERRY-:-DUQUOIN 7-F12',
 'PERRY-:-DUQUOIN 8-F12',
 'PERRY-:-DUQUOIN 9-F12',
 'PERRY-:-PINCKNEYVILLE 1-F12',
 'PERRY-:-PINCKNEYVILLE 2-F12',
 'PERRY-:-PINCKNEYVILLE 3-F12',
 'PERRY-:-PINCKNEYVILLE 4-F12',
 'PERRY-:-PINCKNEYVILLE 5-F12',
 'PERRY-:-PINCKNEYVILLE 6-F12',
 'PERRY-:-PINCKNEYVILLE 7-F12',
 'PERRY-:-PINCKNEYVILLE 8-F12',
 'PERRY-:-SWANWICK-F12',
 'PERRY-:-TAMAROA 2-F12',
 'PERRY-:-WILLISVILLE-F12',
 'PIATT-:-PRESIDENTIAL ONLY BALLOT',
 'PUTNAM-:-PRESIDENTIAL ONLY BALLOT',
 'RICHLAND-:-BONPAS-F12',
 'RICHLAND-:-CLAREMONT-F12',
 'RICHLAND-:-DECKER-F12',
 'RICHLAND-:-DENVER-F12',
 'RICHLAND-:-GERMAN-F12',
 'RICHLAND-:-MADISON 1-F12',
 'RICHLAND-:-MADISON 2-F12',
 'RICHLAND-:-NOBLE 1-F12',
 'RICHLAND-:-NOBLE 2-F12',
 'RICHLAND-:-OLNEY 1-F12',
 'RICHLAND-:-OLNEY 10-F12',
 'RICHLAND-:-OLNEY 11-F12',
 'RICHLAND-:-OLNEY 2-F12',
 'RICHLAND-:-OLNEY 3-F12',
 'RICHLAND-:-OLNEY 4-F12',
 'RICHLAND-:-OLNEY 5-F12',
 'RICHLAND-:-OLNEY 6-F12',
 'RICHLAND-:-OLNEY 9-F12',
 'RICHLAND-:-PRESTON 1-F12',
 'RICHLAND-:-PRESTON 2-F12',
 'SCHUYLER-:-BAINBRIDGE-F15',
 'SCHUYLER-:-BIRMINGHAM-F15',
 'SCHUYLER-:-BROOKLYN-F15',
 'SCHUYLER-:-BROWNING-F15',
 'SCHUYLER-:-BUENAVISTA 1-F15',
 'SCHUYLER-:-BUENAVISTA 2-F15',
 'SCHUYLER-:-FREDERICK-F15',
 'SCHUYLER-:-HICKORY-F15',
 'SCHUYLER-:-HUNTSVILLE-F15',
 'SCHUYLER-:-LITTLETON-F15',
 'SCHUYLER-:-OAKLAND-F15',
 'SCHUYLER-:-RUSHVILLE 1-F15',
 'SCHUYLER-:-RUSHVILLE 2-F15',
 'SCHUYLER-:-RUSHVILLE 3-F15',
 'SCHUYLER-:-RUSHVILLE 4-F15',
 'SCHUYLER-:-WOODSTOCK-F15',
 'SCOTT-:-ALSEY-F15',
 'SCOTT-:-BLOOMFIELD-F15',
 'SCOTT-:-EXETER-BLUFFS-F15',
 'SCOTT-:-GLASGOW-F15',
 'SCOTT-:-MANCHESTER-F15',
 'SCOTT-:-MERRITT-F15',
 'SCOTT-:-NAPLES-BLUFFS-F15',
 'SCOTT-:-WINCHESTER I-F15',
 'SCOTT-:-WINCHESTER II-F15',
 'SCOTT-:-WINCHESTER III-F15',
 'SHELBY-:-PRESIDENTIAL ONLY BALLOT',
 'STEPHENSON-:-PRESIDENTIAL ONLY BALLOT',
 'VERMILION-:-PRESIDENTIAL ONLY BALLOT',
 'WARREN-:-BERWICK 1-F15',
 'WARREN-:-COLDBROOK 1-F17',
 'WARREN-:-ELLISON 1-F15',
 'WARREN-:-FLOYD 1-F15',
 'WARREN-:-GREENBUSH 1-F15',
 'WARREN-:-HALE 1-F15',
 'WARREN-:-LENOX 1-F15',
 'WARREN-:-MONMOUTH  1-F17',
 'WARREN-:-MONMOUTH  2-F17',
 'WARREN-:-MONMOUTH  3-F17',
 'WARREN-:-MONMOUTH  4-F17',
 'WARREN-:-MONMOUTH  5-F17',
 'WARREN-:-MONMOUTH  6-F17',
 'WARREN-:-MONMOUTH  7-F17',
 'WARREN-:-MONMOUTH  8-F17',
 'WARREN-:-MONMOUTH  9-F17',
 'WARREN-:-MONMOUTH 10-F17',
 'WARREN-:-MONMOUTH 12-F17',
 'WARREN-:-POINT PLEASANT 1-F15',
 'WARREN-:-ROSEVILLE 2-F15',
 'WARREN-:-SPRING GROVE-ALEXIS 1-F17',
 'WARREN-:-SPRING GROVE-GERLAW 2-F17',
 'WARREN-:-SUMNER 1-F15',
 'WARREN-:-SWAN 1-F15',
 'WASHINGTON-:-BEAUCOUP-F12',
 'WASHINGTON-:-BOLO-F12',
 'WASHINGTON-:-COVINGTON-F12',
 'WASHINGTON-:-DuBOIS-F12',
 'WASHINGTON-:-HOYLETON-F12',
 'WASHINGTON-:-IRVINGTON-F12',
 'WASHINGTON-:-JOHANNISBURG-F12',
 'WASHINGTON-:-LIVELY GROVE-F12',
 'WASHINGTON-:-NASHVILLE 1-F12',
 'WASHINGTON-:-NASHVILLE 4-F12',
 'WASHINGTON-:-OKAWVILLE 1-F12',
 'WASHINGTON-:-OKAWVILLE 2-F12',
 'WASHINGTON-:-PILOT KNOB-F12',
 'WASHINGTON-:-PLUM HILL-F12',
 'WASHINGTON-:-RICHVIEW-F12',
 'WASHINGTON-:-VENEDY-F12',
 'WHITE-:-BURNT PRAIRIE 10-F12',
 'WHITE-:-CARMI 12-F12',
 'WHITE-:-CARMI 13-F12',
 'WHITE-:-CARMI 14-F12',
 'WHITE-:-CARMI 16-F12',
 'WHITE-:-CARMI 18-F12',
 'WHITE-:-CARMI 19-F12',
 'WHITE-:-CARMI 20-F12',
 'WHITE-:-EMMA 30-F12',
 'WHITE-:-ENFIELD 4-F12',
 'WHITE-:-GRAY 24-F12',
 'WHITE-:-HAWTHORNE 28-F12',
 'WHITE-:-HERALDS PRAIRIE 22-F12',
 'WHITE-:-INDIAN CREEK 6-F12',
 'WHITE-:-INDIAN CREEK 8-F12',
 'WHITE-:-MILL SHOALS 1-F12',
 'WHITE-:-MILL SHOALS 2-F12',
 'WHITE-:-PHILLIPS 26-F12',
 'WHITESIDE-:-PRESIDENTIAL ONLY BALLOT',
 'WILL-:-CHANNAHON PCT 005-FED01',
 'WILL-:-CRETE PCT 001-FED02',
 'WILL-:-CRETE PCT 002-FED02',
 'WILL-:-CRETE PCT 006-FED02',
 'WILL-:-CRETE PCT 008-FED02',
 'WILL-:-CRETE PCT 010-FED02',
 'WILL-:-CRETE PCT 012-FED02',
 'WILL-:-CUSTER PCT 001-FED01',
 'WILL-:-DUPAGE PCT 004-FED11',
 'WILL-:-DUPAGE PCT 009-STYLE 36',
 'WILL-:-DUPAGE PCT 012-FED11',
 'WILL-:-DUPAGE PCT 018-FED11',
 'WILL-:-DUPAGE PCT 019-FED11',
 'WILL-:-DUPAGE PCT 021-FED11',
 'WILL-:-DUPAGE PCT 022-FED11',
 'WILL-:-DUPAGE PCT 023-FED11',
 'WILL-:-DUPAGE PCT 024-STYLE 55',
 'WILL-:-DUPAGE PCT 025-FED11',
 'WILL-:-DUPAGE PCT 027-FED11',
 'WILL-:-DUPAGE PCT 028-FED11',
 'WILL-:-DUPAGE PCT 031-FED11',
 'WILL-:-DUPAGE PCT 032-FED11',
 'WILL-:-DUPAGE PCT 032-FED14',
 'WILL-:-DUPAGE PCT 033-FED14',
 'WILL-:-DUPAGE PCT 034-FED11',
 'WILL-:-DUPAGE PCT 036-FED11',
 'WILL-:-DUPAGE PCT 036-FED14',
 'WILL-:-DUPAGE PCT 037-FED14',
 'WILL-:-FLORENCE PCT 001-FED01',
 'WILL-:-FRANKFORT PCT 002-STYLE 82',
 'WILL-:-FRANKFORT PCT 003-FED01',
 'WILL-:-FRANKFORT PCT 004-FED01',
 'WILL-:-FRANKFORT PCT 007-FED01',
 'WILL-:-FRANKFORT PCT 008-FED01',
 'WILL-:-FRANKFORT PCT 009-FED01',
 'WILL-:-FRANKFORT PCT 011-FED01',
 'WILL-:-FRANKFORT PCT 015-FED01',
 'WILL-:-FRANKFORT PCT 016-FED01',
 'WILL-:-FRANKFORT PCT 024-FED01',
 'WILL-:-FRANKFORT PCT 026-FED01',
 'WILL-:-FRANKFORT PCT 027-FED01',
 'WILL-:-FRANKFORT PCT 028-FED01',
 'WILL-:-GREEN GARDEN PCT 002-FED01',
 'WILL-:-HOMER PCT 001-FED01',
 'WILL-:-HOMER PCT 003-FED01',
 'WILL-:-HOMER PCT 005-FED01',
 'WILL-:-HOMER PCT 008-FED01',
 'WILL-:-HOMER PCT 010-FED01',
 'WILL-:-HOMER PCT 013-FED01',
 'WILL-:-HOMER PCT 015-FED01',
 'WILL-:-HOMER PCT 017-FED01',
 'WILL-:-JACKSON PCT 001-FED14',
 'WILL-:-JACKSON PCT 002-FED14',
 'WILL-:-JOLIET PCT 001-FED14',
 'WILL-:-JOLIET PCT 004-FED14',
 'WILL-:-JOLIET PCT 006-FED14',
 'WILL-:-JOLIET PCT 007-FED14',
 'WILL-:-JOLIET PCT 008-FED14',
 'WILL-:-JOLIET PCT 010-FED14',
 'WILL-:-JOLIET PCT 012-FED14',
 'WILL-:-JOLIET PCT 013-FED14',
 'WILL-:-JOLIET PCT 014-FED14',
 'WILL-:-JOLIET PCT 016-FED14',
 'WILL-:-JOLIET PCT 017-FED14',
 'WILL-:-JOLIET PCT 021-FED14',
 'WILL-:-JOLIET PCT 024-FED14',
 'WILL-:-JOLIET PCT 026-FED14',
 'WILL-:-JOLIET PCT 027-FED14',
 'WILL-:-JOLIET PCT 028-FED14',
 'WILL-:-JOLIET PCT 029-FED14',
 'WILL-:-JOLIET PCT 031-FED14',
 'WILL-:-JOLIET PCT 032-FED14',
 'WILL-:-JOLIET PCT 034-FED14',
 'WILL-:-JOLIET PCT 037-FED14',
 'WILL-:-LOCKPORT PCT 003-FED14',
 'WILL-:-LOCKPORT PCT 004-FED14',
 'WILL-:-LOCKPORT PCT 005-FED01',
 'WILL-:-LOCKPORT PCT 006-FED14',
 'WILL-:-LOCKPORT PCT 010-FED01',
 'WILL-:-LOCKPORT PCT 013-FED14',
 'WILL-:-LOCKPORT PCT 014-FED14',
 'WILL-:-LOCKPORT PCT 015-FED14',
 'WILL-:-LOCKPORT PCT 020-FED14',
 'WILL-:-LOCKPORT PCT 023-FED14',
 'WILL-:-MANHATTAN PCT 002-FED01',
 'WILL-:-MANHATTAN PCT 003-FED01',
 'WILL-:-MANHATTAN PCT 004-FED01',
 'WILL-:-MANHATTAN PCT 005-FED01',
 'WILL-:-MONEE PCT 002-FED02',
 'WILL-:-MONEE PCT 003-FED02',

## Rename Columns

In [440]:
def get_race(race_string):
    race_string = race_string.title()
    race_string = race_string.replace("(Vote For 1)","")
    if "U.S. House" in race_string or 'Us House' in race_string or "Representative To Congress" in race_string or "U. S. Representative" in race_string or "United States Representative" in race_string or "Congress" in race_string:
        return "CON"
    elif "State House" in race_string or "State Representative" in race_string or "Representative" in race_string:
        return "SL"
    elif "State Senate" in race_string or "State Senator" in race_string or "Senate" in race_string:
        return "SU"
    elif "President" in race_string:
        return "PRE"
    elif "US Senate" in race_string or "Us Senate" in race_string or "U.S. Senator" in race_string or "U. S. Senator" in race_string or "United States Senator" in race_string:
        return "USS"
    elif "Public Service" in race_string:
        return "PSC"
    elif "Attorney General" in race_string:
        return "ATG"
    elif "Auditor General" in race_string or "Auditor" in race_string:
        return "AUD"
    elif "Treasurer" in race_string:
        return "TRE"
    elif "Superintendent" in race_string:
        return "SUP"
    elif "Secretary Of State" in race_string:
        return "SOS"
    elif "Governor" in race_string:
        return "GOV"
    elif "Lieutenant Governor" in race_string:
        return "LTG"

    elif "Commissioner Of Labor" in race_string:
        return "LAB"
    elif "Commissioner Of Agriculture" in race_string:
        return "AGR"
    elif "Commissioner Of Insurance" in race_string:
        return "INS"
    elif "Chief Justice Of The Supreme Court" in race_string:
        return "CJU"
    elif "Supreme" in race_string:
        return "SC"
    elif "Justice Of The Supreme Court" in race_string:
        return "JUS"
    elif "Amendment" in race_string:
        #num = race_string.split(" ")[2][:-1]
        return "AMD"
    elif "Bond Question" in race_string:
        num = race_string.split(" ")[2][:-1]
        return "BQ"+str(num)
    elif "Judicial Retention" in race_string:
        return "JR"
    elif "Commissioner Of Public Lands" in race_string:
        return "CPL"
    elif "Comptroller" in race_string:
        return "COM"
    
    elif "All Medically Appropriate Assisted" in race_string:
        return "BI1"
    
    elif "Should Any Candidate Appearing On The Illinois Ballot For Federal" in race_string:
        return "BI3"
    
    elif "Illinois Constitution Be Amended To Create An Additional 3%" in race_string:
        return "BI2"

    else:
        print("No race for:", race_string)
        raise ValueError
        
def get_election_type(race_string):
    return "G"
        
def get_party(race_string):
    race_string = race_string.replace('"',"'")

    if "JUDICIAL RETENTION" in race_string or "Amendment" in race_string or "amendment" in race_string or "Bond Question" in race_string or "Retain" in race_string:
        return ""
    elif "(REP)" in race_string or "REPUBLICAN" in race_string:
        return "R"
    elif "(DEM)" in race_string or "(Democrat)" in race_string or "DEMOCRAT" in race_string:
        return "D"
    elif "(L)" in race_string or "(LBT)" in race_string or "LIBERTARIAN" in race_string:
        return "L"
    elif "(WI)" in race_string:
        return "O"
    elif "(IND)" in race_string:
        return "I"
    elif "(NOPTY)" in race_string:
        return "N"
    elif race_string[0:3]=="YES":
        return "YES"
    elif race_string[0:2]=="NO":
        return "NO"
    else:
        return race_string.split("-:-")[-1][0]
           
def get_name(name_string):
    if "No." in name_string:
        return ""
    else:
        #print(name_string)
        name_string = name_string.replace(" (write in)","")
        name_string = name_string.split("-:-")[1]
        name_string = name_string.replace("'","")
        likely_last = name_string.split(" ")[-1]
        proposed_last = likely_last[:3]
        if proposed_last in ['II', 'III', 'Jr', 'Jr.', 'Sr.', 'JR.', "JR", "IV", 'I']:
            likely_last = name_string.split(" ")[-2]
            proposed_last = likely_last[:3]
        #print(proposed_last.upper())
        return proposed_last.upper()
#     else:
#         return name_string.split(" ")[-1][:3].upper()
import re
 

def get_district(race_string, fill_level):
    race_string = race_string.replace('"',"'")
    temp = race_string
    return re.sub("\D","",temp).zfill(fill_level)

def column_rename_function(name_string):
    election_type = get_election_type(name_string)
    year = "24"
    party = get_party(name_string)
    race = get_race(name_string)
    district = ""
    #print(name_string)
    if race in ["CON", "SU"]:
        district = get_district(name_string, 2)
        year = ""
    elif race in ["SL"]:
        district = get_district(name_string, 3)
        year = ""
    elif race in ["SC"]:
        district = get_district(name_string, 1)
        year = ""
    name = get_name(name_string)
    if "BI" in race:
        party = ""
    new_col_name = election_type + year + race + district + party + name
    print(name_string)
    print("election_type: ", election_type)
    print("year: ", year)
    print("race: ", race)
    print("district: ", district)
    print("party: ", party)
    print("name: ", name)
    if len(new_col_name) > 10:
        print("LONG NAME")
        print(name_string, "->", new_col_name)
    return new_col_name

# Make a dictionary that points to the new column names and checks for duplicates

#la_20_state_level.rename(columns = {"Lessie Olivia Leblanc (DEM)-:-U. S. Representative -- 3rd Congressional District":"Lessie OliviaLeblanc (DEM)-:-U. S. Representative -- 3rd Congressional District"}, inplace = True)

races_to_clean = [i for i in pivoted_filtered.columns if i not in ["pivot_col","JurisName"]]


race_updates_dict = {}
race_updates_reversed = {}
#clean_dups = {}
new_names = []
for val in races_to_clean:
    if "Judge" not in val:
        new_name = column_rename_function(val)
        race_updates_dict[val] = new_name
        if new_name not in new_names:
            new_names.append(new_name)
            race_updates_reversed[new_name] = val
        else:
            print("Duplicate", new_name)
            print(race_updates_reversed[new_name])
            print(val)
            #clean_dups[val] = race_updates_reversed[new_name]
    else:
        print("ADD:", val)

"Should all medically appropriate assisted reproductive treatments, including, but not limited to, i-:-NO-:-Other
election_type:  G
year:  24
race:  BI1
district:
party:
name:  NO
"Should all medically appropriate assisted reproductive treatments, including, but not limited to, i-:-YES-:-Other
election_type:  G
year:  24
race:  BI1
district:
party:
name:  YES
"Should any candidate appearing on the Illinois ballot for federal, State, or local office be subjec-:-NO-:-Other
election_type:  G
year:  24
race:  BI3
district:
party:
name:  NO
"Should any candidate appearing on the Illinois ballot for federal, State, or local office be subjec-:-YES-:-Other
election_type:  G
year:  24
race:  BI3
district:
party:
name:  YES
"Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $-:-NO-:-Other
election_type:  G
year:  24
race:  BI2
district:
party:
name:  NO
"Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $-:-YES-:-Other
election_type:  G
year:  24
race:  BI2
district:
party:
name:  YES
100TH REPRESENTATIVE-:-CHRISTOPHER "C.D." DAVIDSMEYER-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  100
party:  R
name:  DAV
101ST REPRESENTATIVE-:-CHRIS G. MILLER-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  101
party:  R
name:  MIL
102ND REPRESENTATIVE-:-ADAM M. NIEMERG-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  102
party:  R
name:  NIE
103RD REPRESENTATIVE-:-CAROL AMMONS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  103
party:  D
name:  AMM
104TH REPRESENTATIVE-:-BRANDUN SCHWEIZER-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  104
party:  R
name:  SCH
104TH REPRESENTATIVE-:-JARRETT CLEM-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  104
party:  D
name:  CLE
105TH REPRESENTATIVE-:-DENNIS TIPSWORD JR.-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  105
party:  R
name:  TIP
105TH REPRESENTATIVE-:-MORGAN PHILLIPS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  105
party:  D
name:  PHI
106TH REPRESENTATIVE-:-JASON R. BUNTING-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  106
party:  R
name:  BUN
107TH REPRESENTATIVE-:-BRAD HALBROOK-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  107
party:  R
name:  HAL
108TH REPRESENTATIVE-:-WAYNE A. ROSENTHAL-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  108
party:  R
name:  ROS
109TH REPRESENTATIVE-:-CHARLIE MEIER-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  109
party:  R
name:  MEI
10TH CONGRESS-:-BRAD SCHNEIDER-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  10
party:  D
name:  SCH
10TH CONGRESS-:-JIM CARRIS-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  10
party:  R
name:  CAR
10TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  10
party:  O
name:  WRI
10TH REPRESENTATIVE-:-JAWAHARIAL "OMAR" WILLIAMS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  010
party:  D
name:  WIL
10TH SENATE-:-JON LUERS-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  10
party:  R
name:  LUE
10TH SENATE-:-ROBERT MARTWICK-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  10
party:  D
name:  MAR
110TH REPRESENTATIVE-:-BLAINE WILHOUR-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  110
party:  R
name:  WIL
111TH REPRESENTATIVE-:-AMY ELIK-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  111
party:  R
name:  ELI
111TH REPRESENTATIVE-:-NICK RAFTOPOULOS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  111
party:  D
name:  RAF
112TH REPRESENTATIVE-:-JAY KEEVEN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  112
party:  R
name:  KEE
112TH REPRESENTATIVE-:-KATIE STUART-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  112
party:  D
name:  STU
113TH REPRESENTATIVE-:-JAY HOFFMAN-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  113
party:  D
name:  HOF
114TH REPRESENTATIVE-:-KEVIN SCHMIDT-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  114
party:  R
name:  SCH
114TH REPRESENTATIVE-:-LATOYA GREENWOOD-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  114
party:  D
name:  GRE
115TH REPRESENTATIVE-:-DAVID FRIESS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  115
party:  R
name:  FRI
116TH REPRESENTATIVE-:-DAVE SEVERIN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  116
party:  R
name:  SEV
117TH REPRESENTATIVE-:-PATRICK WINDHORST-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  117
party:  R
name:  WIN
118TH REPRESENTATIVE-:-PAUL JACOBS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  118
party:  R
name:  JAC
11TH CONGRESS-:-BILL FOSTER-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  11
party:  D
name:  FOS
11TH CONGRESS-:-JERRY EVANS-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  11
party:  R
name:  EVA
11TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  11
party:  O
name:  WRI
11TH REPRESENTATIVE-:-ANN M. WILLIAMS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  011
party:  D
name:  WIL
12TH CONGRESS-:-BRIAN ROBERTS-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  12
party:  D
name:  ROB
12TH CONGRESS-:-MIKE BOST-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  12
party:  R
name:  BOS
12TH REPRESENTATIVE-:-MARGARET CROKE-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  012
party:  D
name:  CRO
13TH CONGRESS-:-JOSHUA LOYD-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  13
party:  R
name:  LOY
13TH CONGRESS-:-NIKKI BUDZINSKI-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  13
party:  D
name:  BUD
13TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  13
party:  O
name:  WRI
13TH REPRESENTATIVE-:-HOAN HUYNH-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  013
party:  D
name:  HUY
13TH REPRESENTATIVE-:-TERRY NGUYEN LE-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  013
party:  R
name:  LE
13TH SENATE-:-ROBERT PETERS-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  13
party:  D
name:  PET
14TH CONGRESS-:-JAMES T. "JIM" MARTER-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  14
party:  R
name:  MAR
14TH CONGRESS-:-LAUREN UNDERWOOD-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  14
party:  D
name:  UND
14TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  14
party:  O
name:  WRI
14TH REPRESENTATIVE-:-KELLY M. CASSIDY-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  014
party:  D
name:  CAS
15TH CONGRESS-:-MARY E. MILLER-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  15
party:  R
name:  MIL
15TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  15
party:  O
name:  WRI
15TH REPRESENTATIVE-:-MARK R. ALBERS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  015
party:  R
name:  ALB
15TH REPRESENTATIVE-:-MICHAEL J. KELLY-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  015
party:  D
name:  KEL
16TH CONGRESS-:-DARIN LAHOOD-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  16
party:  R
name:  LAH
16TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  16
party:  O
name:  WRI
16TH REPRESENTATIVE-:-KEVIN JOHN OLICKAL-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  016
party:  D
name:  OLI
16TH SENATE-:-WILLIE PRESTON-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  16
party:  D
name:  PRE
17TH CONGRESS-:-ERIC SORENSEN-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  17
party:  D
name:  SOR
17TH CONGRESS-:-JOE MCGRAW-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  17
party:  R
name:  MCG
17TH REPRESENTATIVE-:-JENNIFER GONG-GERSHOWITZ-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  017
party:  D
name:  GON
17TH REPRESENTATIVE-:-JIM GELDERMANN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  017
party:  R
name:  GEL
18TH REPRESENTATIVE-:-CHARLES HUTCHINSON-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  018
party:  R
name:  HUT
18TH REPRESENTATIVE-:-ROBYN GABEL-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  018
party:  D
name:  GAB
19TH REPRESENTATIVE-:-JOHN "JZ" ZIMMERS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  019
party:  R
name:  ZIM
19TH REPRESENTATIVE-:-LINDSEY LAPOINTE-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  019
party:  D
name:  LAP
19TH SENATE-:-MICHAEL E. HASTINGS-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  19
party:  D
name:  HAS
19TH SENATE-:-SAMANTHA JEAN GASCA-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  19
party:  R
name:  GAS
1ST CONGRESS-:-JONATHAN L. JACKSON-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  01
party:  D
name:  JAC
1ST CONGRESS-:-MARCUS LEWIS-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  01
party:  R
name:  LEW
1ST CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  01
party:  O
name:  WRI
1ST REPRESENTATIVE-:-AARON M. ORTIZ-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  001
party:  D
name:  ORT
1ST SENATE-:-JAVIER LOERA CERVANTES-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  01
party:  D
name:  CER
1ST SUPREME - BURKE VACANCY-:-JOY VIRGINIA CUNNINGHAM-:-DEMOCRAT
election_type:  G
year:
race:  SC
district:  1
party:  D
name:  CUN
20TH REPRESENTATIVE-:-BRAD STEPHENS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  020
party:  R
name:  STE
20TH SENATE-:-GRACIELA GUZMAN-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  20
party:  D
name:  GUZ
20TH SENATE-:-JASON PROCTOR-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  20
party:  R
name:  PRO
21ST REPRESENTATIVE-:-ABDELNASSER RASHID-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  021
party:  D
name:  RAS
22ND REPRESENTATIVE-:-ANGIE GUERRERO-CUELLAR-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  022
party:  D
name:  GUE
22ND SENATE-:-CRISTINA CASTRO-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  22
party:  D
name:  CAS
23RD REPRESENTATIVE-:-EDGAR GONZALEZ, JR.-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  023
party:  D
name:  GON
24TH REPRESENTATIVE-:-NATALIAN BOLTON-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  024
party:  R
name:  BOL
24TH REPRESENTATIVE-:-THERESA MAH-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  024
party:  D
name:  MAH
25TH REPRESENTATIVE-:-CURTIS J. TARVER II-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  025
party:  D
name:  TAR
25TH SENATE-:-HEATHER BROWN-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  25
party:  R
name:  BRO
25TH SENATE-:-KARINA VILLA-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  25
party:  D
name:  VIL
26TH REPRESENTATIVE-:-AUDREY BARRETT-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  026
party:  R
name:  BAR
26TH REPRESENTATIVE-:-KAM BUCKNER-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  026
party:  D
name:  BUC
27TH REPRESENTATIVE-:-JUSTIN Q. SLAUGHTER-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  027
party:  D
name:  SLA
27TH SENATE-:-MARK L. WALKER-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  27
party:  D
name:  WAL
27TH SENATE-:-TOM SCHLENHARDT-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  27
party:  R
name:  SCH
28TH REPRESENTATIVE-:-ROBERT "BOB" RITA-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  028
party:  D
name:  RIT
28TH SENATE-:-LAURA M. MURPHY-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  28
party:  D
name:  MUR
29TH REPRESENTATIVE-:-THADDEUS JONES-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  029
party:  D
name:  JON
29TH REPRESENTATIVE-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  SL
district:  029
party:  O
name:  WRI
2ND CONGRESS-:-ASHLEY RAMOS-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  02
party:  R
name:  RAM
2ND CONGRESS-:-ROBIN KELLY-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  02
party:  D
name:  KEL
2ND CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  02
party:  O
name:  WRI
2ND REPRESENTATIVE-:-ELIZABETH "LISA" HERNANDEZ-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  002
party:  D
name:  HER
2ND REPRESENTATIVE-:-LAURA HRUSKA-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  002
party:  R
name:  HRU
30TH REPRESENTATIVE-:-PATRICIA BONK-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  030
party:  R
name:  BON
30TH REPRESENTATIVE-:-WILLIAM "WILL" DAVIS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  030
party:  D
name:  DAV
31ST REPRESENTATIVE-:-CARL R. KUNZ-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  031
party:  R
name:  KUN
31ST REPRESENTATIVE-:-MICHAEL CRAWFORD-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  031
party:  D
name:  CRA
31ST SENATE-:-ASHLEY JENSEN-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  31
party:  R
name:  JEN
31ST SENATE-:-MARY EDLY-ALLEN-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  31
party:  D
name:  EDL
32ND REPRESENTATIVE-:-LISA J. DAVIS-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  032
party:  D
name:  DAV
33RD REPRESENTATIVE-:-MARCUS C. EVANS, JR.-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  033
party:  D
name:  EVA
34TH REPRESENTATIVE-:-FREDERICK L. WALLS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  034
party:  R
name:  WAL
34TH REPRESENTATIVE-:-NICHOLAS "NICK" SMITH-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  034
party:  D
name:  SMI
34TH SENATE-:-CRYSTAL VILLARREAL SOLTOW-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  34
party:  R
name:  SOL
34TH SENATE-:-STEVE STADELMAN-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  34
party:  D
name:  STA
35TH REPRESENTATIVE-:-HERBERT HEBEIN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  035
party:  R
name:  HEB
35TH REPRESENTATIVE-:-MARY GILL-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  035
party:  D
name:  GIL
36TH REPRESENTATIVE-:-CHRISTINE SHANAHAN MCGOVERN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  036
party:  R
name:  MCG
36TH REPRESENTATIVE-:-RICK RYAN-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  036
party:  D
name:  RYA
37TH REPRESENTATIVE-:-PATRICK SHEEHAN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  037
party:  R
name:  SHE
37TH SENATE-:-LI ARELLANO, JR.-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  37
party:  R
name:  ARE
38TH REPRESENTATIVE-:-DEBBIE MEYERS-MARTIN-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  038
party:  D
name:  MEY
39TH REPRESENTATIVE-:-ANTHONY CURRAN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  039
party:  R
name:  CUR
39TH REPRESENTATIVE-:-WILL GUZZARDI-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  039
party:  D
name:  GUZ
39TH REPRESENTATIVE-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  SL
district:  039
party:  O
name:  WRI
3RD CONGRESS-:-DELIA RAMIREZ-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  03
party:  D
name:  RAM
3RD CONGRESS-:-JOHN BOORAS-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  03
party:  R
name:  BOO
3RD CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  03
party:  O
name:  WRI
3RD REPRESENTATIVE-:-EVA-DINA DELGADO-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  003
party:  D
name:  DEL
40TH REPRESENTATIVE-:-JAIME M. ANDRADE, JR.-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  040
party:  D
name:  AND
40TH REPRESENTATIVE-:-PATRYCJA KARLIN-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  040
party:  R
name:  KAR
40TH SENATE-:-PATRICK JOYCE-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  40
party:  D
name:  JOY
40TH SENATE-:-PHILIP NAGEL-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  40
party:  R
name:  NAG
41ST REPRESENTATIVE-:-JANET YANG ROHR-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  041
party:  D
name:  ROH
42ND REPRESENTATIVE-:-TERRA COSTA HOWARD-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  042
party:  D
name:  HOW
42ND REPRESENTATIVE-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  SL
district:  042
party:  O
name:  WRI
43RD REPRESENTATIVE-:-ANNA MOELLER-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  043
party:  D
name:  MOE
43RD REPRESENTATIVE-:-DONALD P. PUCKETT-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  043
party:  R
name:  PUC
43RD SENATE-:-JENNIFER "JEN" MONSON-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  43
party:  R
name:  MON
43RD SENATE-:-RACHEL VENTURA-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  43
party:  D
name:  VEN
44TH REPRESENTATIVE-:-FRED CRESPO-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  044
party:  D
name:  CRE
45TH REPRESENTATIVE-:-DENNIS M. REBOLETTI-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  045
party:  R
name:  REB
45TH REPRESENTATIVE-:-MARTHA "MARTI" DEUTER-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  045
party:  D
name:  DEU
46TH REPRESENTATIVE-:-DIANE BLAIR-SHERLOCK-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  046
party:  D
name:  BLA
46TH REPRESENTATIVE-:-ROBERT "RUSTY" STEVENS-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  046
party:  R
name:  STE
46TH SENATE-:-DAVE KOEHLER-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  46
party:  D
name:  KOE
46TH SENATE-:-SALLY OWENS-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  46
party:  R
name:  OWE
47TH REPRESENTATIVE-:-AMY L. GRANT-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  047
party:  R
name:  GRA
47TH REPRESENTATIVE-:-JACKIE WILLIAMSON-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  047
party:  D
name:  WIL
48TH REPRESENTATIVE-:-JENNIFER SANALITRO-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  048
party:  R
name:  SAN
48TH REPRESENTATIVE-:-MARIA C. VESEY-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  048
party:  D
name:  VES
49TH REPRESENTATIVE-:-HANNAH BILLINGSLEY-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  049
party:  R
name:  BIL
49TH REPRESENTATIVE-:-MAURA HIRSCHAUER-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  049
party:  D
name:  HIR
49TH SENATE-:-KATIE DEANE-SCHLOTTMAN-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  49
party:  R
name:  DEA
49TH SENATE-:-MEG LOUGHRAN CAPPEL-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  49
party:  D
name:  CAP
4TH CONGRESS-:-ED HERSHEY-:-WORKING CLASS PARTY
election_type:  G
year:
race:  CON
district:  04
party:  W
name:  HER
4TH CONGRESS-:-JESUS "CHUY" GARCIA-:-DEMOCRAT
election_type:  G
year:
race:  CON
district:  04
party:  D
name:  GAR
4TH CONGRESS-:-LUPE CASTILLO-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  04
party:  R
name:  CAS
4TH CONGRESS-:-WRITE-IN-:-OTHER
election_type:  G
year:
race:  CON
district:  04
party:  O
name:  WRI
4TH REPRESENTATIVE-:-LILIAN JIMENEZ-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  004
party:  D
name:  JIM
4TH SENATE-:-KIMBERLY A. LIGHTFORD-:-DEMOCRAT
election_type:  G
year:
race:  SU
district:  04
party:  D
name:  LIG
4TH SENATE-:-ROBERT SUMRELL JR.-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  04
party:  R
name:  SUM
4TH SUPREME - GARMAN VACANCY-:-LISA HOLDER WHITE-:-REPUBLICAN
election_type:  G
year:
race:  SC
district:  4
party:  R
name:  WHI
50TH REPRESENTATIVE-:-BARBARA HERNANDEZ-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  050
party:  D
name:  HER
50TH REPRESENTATIVE-:-TERESA L. ALEXANDER-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  050
party:  R
name:  ALE
51ST REPRESENTATIVE-:-NABEELA SYED-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  051
party:  D
name:  SYE
51ST REPRESENTATIVE-:-TOSI UFODIKE-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  051
party:  R
name:  UFO
52ND REPRESENTATIVE-:-MARIA PETERSON-:-DEMOCRAT
election_type:  G
year:
race:  SL
district:  052
party:  D
name:  PET

In [441]:
pivoted_filtered.rename(columns = race_updates_dict, inplace = True)

In [442]:
# Export the Renamed Columns for the README
pd.DataFrame(race_updates_dict.items()).to_csv("./field_names.csv", index = False)

In [443]:
# Sort the race columns in alphabetical order
race_cols = list(race_updates_reversed.keys())
race_cols.sort()

In [444]:
pivoted_filtered = pivoted_filtered.fillna(0)

In [445]:
pivoted_filtered = pivoted_filtered[["pivot_col","JurisName"]+race_cols]

In [446]:
for race in race_cols:
    pivoted_filtered[race] = pivoted_filtered[race].astype(int)

In [447]:
pivoted_filtered

cand_col,pivot_col,JurisName,G24BI1NO,G24BI1YES,G24BI2NO,G24BI2YES,G24BI3NO,G24BI3YES,G24PREDHAR,G24PREIKEN,...,GSU43RMON,GSU46DKOE,GSU46ROWE,GSU49DCAP,GSU49RDEA,GSU52DFAR,GSU52RBRO,GSU53RBAL,GSU55RPLU,GSU58RBRY
0,ADAMS-:-BEVERLY PCT 1,ADAMS,83,86,109,60,31,140,28,1,...,0,0,0,0,0,0,0,0,0,0
1,ADAMS-:-BURTON PCT 1,ADAMS,270,241,339,177,94,419,65,2,...,0,0,0,0,0,0,0,0,0,0
2,ADAMS-:-CAMP POINT PCT 1,ADAMS,189,208,233,160,77,322,54,3,...,0,0,0,0,0,0,0,0,0,0
3,ADAMS-:-CAMP POINT PCT 2,ADAMS,214,248,276,187,81,372,49,2,...,0,0,0,0,0,0,0,0,0,0
4,ADAMS-:-CLAYTON PCT 1,ADAMS,202,241,238,203,78,365,75,6,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9315,WOODFORD-:-WORTH 4,WOODFORD,240,346,312,276,94,498,222,9,...,0,0,0,0,0,0,0,0,0,0
9316,WOODFORD-:-WORTH 5,WOODFORD,242,309,307,249,86,471,221,11,...,0,0,0,0,0,0,0,0,0,0
9317,WOODFORD-:-WORTH 6,WOODFORD,210,290,228,272,63,441,200,10,...,0,0,0,0,0,0,0,0,0,0
9318,WOODFORD-:-WORTH 7,WOODFORD,376,474,439,420,122,735,348,14,...,0,0,0,0,0,0,0,0,0,0
9319,WOODFORD-:-WORTH 9,WOODFORD,476,522,562,440,167,831,260,19,...,0,0,0,0,0,0,0,445,0,0

## Check Election Result Totals

In [448]:
cand_id_name = {int(i):race_updates_dict[j] for i,j in zip(il_state_filtered["EISCandidateID"],il_state_filtered["cand_col"])}

In [449]:
county_results = pd.read_excel("./raw-from-source/ge2024cty_638942182699685529.xlsx")

In [450]:
# county_results["col_name"] = county_results["CandidateID"].map(cand_id_name).fillna(county_results["CandidateID"])

In [451]:
county_results["CanName"] = np.where(county_results["CanFirstName"].isna(),county_results["CanLastName"],county_results["CanFirstName"] + " " +county_results["CanLastName"])

In [452]:
keep_races_counties = [i for i in county_results["OfficeName"].unique() if "CIRCUIT" not in i and "APPELLATE" not in i]

In [453]:
keep_races_counties =['110TH REPRESENTATIVE',
 '111TH REPRESENTATIVE',
 '112TH REPRESENTATIVE',
 '113TH REPRESENTATIVE',
 '114TH REPRESENTATIVE',
 '115TH REPRESENTATIVE',
 '116TH REPRESENTATIVE',
 '117TH REPRESENTATIVE',
 '118TH REPRESENTATIVE',
 '11TH CONGRESS',
 '11TH REPRESENTATIVE',
 '12TH CONGRESS',
 '100TH REPRESENTATIVE',
 '101ST REPRESENTATIVE',
 '102ND REPRESENTATIVE',
 '103RD REPRESENTATIVE',
 '104TH REPRESENTATIVE',
 '105TH REPRESENTATIVE',
 '106TH REPRESENTATIVE',
 '107TH REPRESENTATIVE',
 '108TH REPRESENTATIVE',
 '109TH REPRESENTATIVE',
 '10TH CONGRESS',
 '10TH REPRESENTATIVE',
 '10TH SENATE',
 '12TH REPRESENTATIVE',
 '60TH REPRESENTATIVE',
 '61ST REPRESENTATIVE',
 '62ND REPRESENTATIVE',
 '63RD REPRESENTATIVE',
 '64TH REPRESENTATIVE',
 '65TH REPRESENTATIVE',
 '66TH REPRESENTATIVE',
 '67TH REPRESENTATIVE',
 '68TH REPRESENTATIVE',
 '69TH REPRESENTATIVE',
 '6TH CONGRESS',
 '6TH REPRESENTATIVE',
 '70TH REPRESENTATIVE',
 '71ST REPRESENTATIVE',
 '72ND REPRESENTATIVE',
 '73RD REPRESENTATIVE',
 '74TH REPRESENTATIVE',
 '75TH REPRESENTATIVE',
 '76TH REPRESENTATIVE',
 '77TH REPRESENTATIVE',
 '78TH REPRESENTATIVE',
 '79TH REPRESENTATIVE',
 '7TH CONGRESS',
 '7TH REPRESENTATIVE',
 '7TH SENATE',
 '80TH REPRESENTATIVE',
 '81ST REPRESENTATIVE',
 '82ND REPRESENTATIVE',
 '83RD REPRESENTATIVE',
 '84TH REPRESENTATIVE',
 '85TH REPRESENTATIVE',
 '86TH REPRESENTATIVE',
 '87TH REPRESENTATIVE',
 '88TH REPRESENTATIVE',
 '89TH REPRESENTATIVE',
 '8TH CONGRESS',
 '8TH REPRESENTATIVE',
 '90TH REPRESENTATIVE',
 '91ST REPRESENTATIVE',
 '92ND REPRESENTATIVE',
 '93RD REPRESENTATIVE',
 '94TH REPRESENTATIVE',
 '95TH REPRESENTATIVE',
 '96TH REPRESENTATIVE',
 '97TH REPRESENTATIVE',
 '98TH REPRESENTATIVE',
 '99TH REPRESENTATIVE',
 '9TH CONGRESS',
 '9TH REPRESENTATIVE',
 'PRESIDENT AND VICE PRESIDENT',
 '27TH SENATE',
 '"Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $1,000,000 for the purpose of dedicating funds raised to property tax relief?"',
 '24TH REPRESENTATIVE',
 '25TH REPRESENTATIVE',
 '25TH SENATE',
 '26TH REPRESENTATIVE',
 '27TH REPRESENTATIVE',
 '28TH REPRESENTATIVE',
 '28TH SENATE',
 '29TH REPRESENTATIVE',
 '2ND CONGRESS',
 '2ND REPRESENTATIVE',
 '30TH REPRESENTATIVE',
 '31ST REPRESENTATIVE',
 '31ST SENATE',
 '32ND REPRESENTATIVE',
 '13TH CONGRESS',
 '13TH REPRESENTATIVE',
 '13TH SENATE',
 '14TH CONGRESS',
 '15TH CONGRESS',
 '15TH REPRESENTATIVE',
 '16TH CONGRESS',
 '16TH REPRESENTATIVE',
 '16TH SENATE',
 '17TH CONGRESS',
 '17TH REPRESENTATIVE',
 '18TH REPRESENTATIVE',
 '19TH REPRESENTATIVE',
 '19TH SENATE',
 '1ST CONGRESS',
 '1ST REPRESENTATIVE',
 '1ST SENATE',
 '1ST SUPREME - BURKE VACANCY',
 '20TH REPRESENTATIVE',
 '20TH SENATE',
 '21ST REPRESENTATIVE',
 '22ND REPRESENTATIVE',
 '22ND SENATE',
 '14TH REPRESENTATIVE',
 '23RD REPRESENTATIVE',
 '33RD REPRESENTATIVE',
 '34TH REPRESENTATIVE',
 '34TH SENATE',
 '35TH REPRESENTATIVE',
 '36TH REPRESENTATIVE',
 '37TH REPRESENTATIVE',
 '37TH SENATE',
 '38TH REPRESENTATIVE',
 '39TH REPRESENTATIVE',
 '3RD CONGRESS',
 '3RD REPRESENTATIVE',
 '40TH REPRESENTATIVE',
 '40TH SENATE',
 '41ST REPRESENTATIVE',
 '42ND REPRESENTATIVE',
 '43RD REPRESENTATIVE',
 '43RD SENATE',
 '44TH REPRESENTATIVE',
 '45TH REPRESENTATIVE',
 '46TH REPRESENTATIVE',
 '46TH SENATE',
 '47TH REPRESENTATIVE',
 '48TH REPRESENTATIVE',
 '49TH REPRESENTATIVE',
 '49TH SENATE',
 '4TH CONGRESS',
 '4TH REPRESENTATIVE',
 '4TH SENATE',
 '4TH SUPREME - GARMAN VACANCY',
 '50TH REPRESENTATIVE',
 '51ST REPRESENTATIVE',
 '52ND REPRESENTATIVE',
 '52ND SENATE',
 '53RD REPRESENTATIVE',
 '53RD SENATE',
 '54TH REPRESENTATIVE',
 '55TH REPRESENTATIVE',
 '55TH SENATE',
 '56TH REPRESENTATIVE',
 '57TH REPRESENTATIVE',
 '58TH REPRESENTATIVE',
 '58TH SENATE',
 '59TH REPRESENTATIVE',
 '5TH CONGRESS',
 '5TH REPRESENTATIVE',
 '5TH SENATE',
 '"Should any candidate appearing on the Illinois ballot for federal, State, or local office be subject to civil penalties if the candidate interferes or attempts to interfere with an election worker\'s official duties?"',
 '"Should all medically appropriate assisted reproductive treatments, including, but not limited to, in vitro fertilization, be covered by any health insurance plan in Illinois that provides coverage for pregnancy benefits, without limitation on the number of treatments?"']

In [454]:
county_results = county_results[county_results["OfficeName"].isin(keep_races_counties)]

In [455]:
county_results[county_results["OfficeName"].str.contains("amendment")]

Empty DataFrame
Columns: [Election, OfficeName, VoteFor, BallotGroup, OfficeSequence, CandidateID, CanFirstName, CanLastName, CanAffilCommit, County, Votes, PartyName, PartyAbbrev, CanName]
Index: []

In [456]:
county_results["PartyName"] = county_results["PartyName"].fillna("OTHER")

In [457]:
county_results["cand_col"] = county_results["OfficeName"] + "-:-" + county_results["CanName"] + "-:-" + county_results["PartyName"]

In [458]:
pivoted_county = pd.pivot_table(county_results, index = "County", values = "Votes", columns = "cand_col")

In [459]:
pivoted_county.reset_index(inplace = True, drop = False)

In [460]:
pivoted_county

cand_col,County,"""Should all medically appropriate assisted reproductive treatments, including, but not limited to, in vitro fertilization, be covered by any health insurance plan in Illinois that provides coverage for pregnancy benefits, without limitation on the number of treatments?""-:-NO-:-OTHER","""Should all medically appropriate assisted reproductive treatments, including, but not limited to, in vitro fertilization, be covered by any health insurance plan in Illinois that provides coverage for pregnancy benefits, without limitation on the number of treatments?""-:-YES-:-OTHER","""Should any candidate appearing on the Illinois ballot for federal, State, or local office be subject to civil penalties if the candidate interferes or attempts to interfere with an election worker's official duties?""-:-NO-:-OTHER","""Should any candidate appearing on the Illinois ballot for federal, State, or local office be subject to civil penalties if the candidate interferes or attempts to interfere with an election worker's official duties?""-:-YES-:-OTHER","""Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $1,000,000 for the purpose of dedicating funds raised to property tax relief?""-:-NO-:-OTHER","""Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $1,000,000 for the purpose of dedicating funds raised to property tax relief?""-:-YES-:-OTHER","100TH REPRESENTATIVE-:-Christopher ""C.D."" Davidsmeyer-:-REPUBLICAN",101ST REPRESENTATIVE-:-Chris G. Miller-:-REPUBLICAN,102ND REPRESENTATIVE-:-Adam M. Niemerg-:-REPUBLICAN,...,PRESIDENT AND VICE PRESIDENT-:-Latrina Peete-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Melina Abdullah-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Mike ter Maat-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Peter Sonski-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Richard Mayers-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Robert F. Kennedy Jr.-:-INDEPENDENT,PRESIDENT AND VICE PRESIDENT-:-Rudolph Ware-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Shiva Ayyadurai-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Shondra Irving-:-OTHER,PRESIDENT AND VICE PRESIDENT-:-Susan Maude Buchser-:-OTHER
0,ADAMS,12989.0,17445.0,4773.0,25774.0,15972.0,14550.0,2815.0,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,472.0,0.0,3.0,NaN,0.0
1,ALEXANDER,778.0,1312.0,326.0,1803.0,1040.0,1065.0,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,26.0,0.0,0.0,NaN,0.0
2,BOND,3115.0,4512.0,1086.0,6597.0,3693.0,4004.0,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,172.0,0.0,0.0,NaN,0.0
3,BOONE,7745.0,15473.0,2785.0,20591.0,10038.0,13402.0,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,384.0,0.0,0.0,NaN,0.0
4,BROWN,973.0,1382.0,330.0,2064.0,1252.0,1107.0,524.0,NaN,NaN,...,NaN,0.0,0.0,NaN,0.0,50.0,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,WHITESIDE,8456.0,17104.0,2776.0,23024.0,10786.0,14995.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,519.0,NaN,0.0,NaN,NaN
98,WILL,88616.0,227108.0,44954.0,270173.0,129446.0,187276.0,NaN,NaN,NaN,...,NaN,0.0,0.0,61.0,0.0,4425.0,0.0,0.0,NaN,0.0
99,WILLIAMSON,12829.0,18368.0,4759.0,26684.0,15074.0,16339.0,NaN,NaN,NaN,...,NaN,0.0,4.0,0.0,0.0,422.0,14.0,0.0,NaN,0.0
100,WINNEBAGO,37287.0,78914.0,13019.0,104037.0,46294.0,70477.0,NaN,NaN,NaN,...,0.0,5.0,6.0,19.0,0.0,1849.0,52.0,1.0,NaN,0.0
101,WOODFORD,9519.0,10682.0,3587.0,16720.0,11178.0,9155.0,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,318.0,2.0,0.0,NaN,1.0

In [461]:
def get_race(race_string):
    race_string = race_string.title()
    race_string = race_string.replace("(Vote For 1)","")
    if "U.S. House" in race_string or 'Us House' in race_string or "Representative To Congress" in race_string or "U. S. Representative" in race_string or "United States Representative" in race_string or "Congress" in race_string:
        return "CON"
    elif "State House" in race_string or "State Representative" in race_string or "Representative" in race_string:
        return "SL"
    elif "State Senate" in race_string or "State Senator" in race_string or "Senate" in race_string:
        return "SU"
    elif "President" in race_string:
        return "PRE"
    elif "US Senate" in race_string or "Us Senate" in race_string or "U.S. Senator" in race_string or "U. S. Senator" in race_string or "United States Senator" in race_string:
        return "USS"
    elif "Public Service" in race_string:
        return "PSC"
    elif "Attorney General" in race_string:
        return "ATG"
    elif "Auditor General" in race_string or "Auditor" in race_string:
        return "AUD"
    elif "Treasurer" in race_string:
        return "TRE"
    elif "Superintendent" in race_string:
        return "SUP"
    elif "Secretary Of State" in race_string:
        return "SOS"
    elif "Governor" in race_string:
        return "GOV"
    elif "Lieutenant Governor" in race_string:
        return "LTG"

    elif "Commissioner Of Labor" in race_string:
        return "LAB"
    elif "Commissioner Of Agriculture" in race_string:
        return "AGR"
    elif "Commissioner Of Insurance" in race_string:
        return "INS"
    elif "Chief Justice Of The Supreme Court" in race_string:
        return "CJU"
    elif "Supreme" in race_string:
        return "SC"
    elif "Justice Of The Supreme Court" in race_string:
        return "JUS"
    elif "Amendment" in race_string:
        #num = race_string.split(" ")[2][:-1]
        return "AMD"
    elif "Bond Question" in race_string:
        num = race_string.split(" ")[2][:-1]
        return "BQ"+str(num)
    elif "Judicial Retention" in race_string:
        return "JR"
    elif "Commissioner Of Public Lands" in race_string:
        return "CPL"
    elif "Comptroller" in race_string:
        return "COM"
    
    elif "All Medically Appropriate Assisted" in race_string:
        return "BI1"
    
    elif "Should Any Candidate Appearing On The Illinois Ballot For Federal" in race_string:
        return "BI3"
    
    elif "Illinois Constitution Be Amended To Create An Additional 3%" in race_string:
        return "BI2"

    else:
        print("No race for:", race_string)
        raise ValueError
        
def get_election_type(race_string):
    return "G"
        
def get_party(race_string):
    race_string = race_string.replace('"',"'")

    if "JUDICIAL RETENTION" in race_string or "Amendment" in race_string or "amendment" in race_string or "Bond Question" in race_string or "Retain" in race_string:
        return ""
    elif "(REP)" in race_string or "REPUBLICAN" in race_string:
        return "R"
    elif "(DEM)" in race_string or "(Democrat)" in race_string or "DEMOCRAT" in race_string:
        return "D"
    elif "(L)" in race_string or "(LBT)" in race_string or "LIBERTARIAN" in race_string:
        return "L"
    elif "(WI)" in race_string:
        return "O"
    elif "(IND)" in race_string:
        return "I"
    elif "(NOPTY)" in race_string:
        return "N"
    elif race_string[0:3]=="YES":
        return "YES"
    elif race_string[0:2]=="NO":
        return "NO"
    else:
        return race_string.split("-:-")[-1][0]
           
def get_name(name_string):
    if "No." in name_string:
        return ""
    else:
        #print(name_string)
        name_string = name_string.replace(" (write in)","")
        name_string = name_string.split("-:-")[1]
        name_string = name_string.replace("'","")
        likely_last = name_string.split(" ")[-1]
        proposed_last = likely_last[:3]
        if proposed_last in ['II', 'III', 'Jr', 'Jr.', 'Sr.', 'JR.', "JR", "IV", 'I']:
            likely_last = name_string.split(" ")[-2]
            proposed_last = likely_last[:3]
        #print(proposed_last.upper())
        return proposed_last.upper()
#     else:
#         return name_string.split(" ")[-1][:3].upper()
import re
 

def get_district(race_string, fill_level):
    race_string = race_string.replace('"',"'")
    temp = race_string
    return re.sub("\D","",temp).zfill(fill_level)

def column_rename_function(name_string):
    election_type = get_election_type(name_string)
    year = "24"
    party = get_party(name_string)
    race = get_race(name_string)
    district = ""
    #print(name_string)
    if race in ["CON", "SU"]:
        district = get_district(name_string, 2)
        year = ""
    elif race in ["SL"]:
        district = get_district(name_string, 3)
        year = ""
    elif race in ["SC"]:
        district = get_district(name_string, 1)
        year = ""
    name = get_name(name_string)
    if "BI" in race:
        party = ""
    new_col_name = election_type + year + race + district + party + name
    print(name_string)
    print("election_type: ", election_type)
    print("year: ", year)
    print("race: ", race)
    print("district: ", district)
    print("party: ", party)
    print("name: ", name)
    if len(new_col_name) > 10:
        print("LONG NAME")
        print(name_string, "->", new_col_name)
    return new_col_name

# Make a dictionary that points to the new column names and checks for duplicates

#la_20_state_level.rename(columns = {"Lessie Olivia Leblanc (DEM)-:-U. S. Representative -- 3rd Congressional District":"Lessie OliviaLeblanc (DEM)-:-U. S. Representative -- 3rd Congressional District"}, inplace = True)

races_to_clean = [i for i in pivoted_county.columns if i not in ["County"]]


race_updates_dict = {}
race_updates_reversed = {}
#clean_dups = {}
new_names = []
for val in races_to_clean:
    if "Judge" not in val:
        new_name = column_rename_function(val)
        race_updates_dict[val] = new_name
        if new_name not in new_names:
            new_names.append(new_name)
            race_updates_reversed[new_name] = val
        else:
            print("Duplicate", new_name)
            print(race_updates_reversed[new_name])
            print(val)
            #clean_dups[val] = race_updates_reversed[new_name]
    else:
        print("ADD:", val)

"Should all medically appropriate assisted reproductive treatments, including, but not limited to, in vitro fertilization, be covered by any health insurance plan in Illinois that provides coverage for pregnancy benefits, without limitation on the number of treatments?"-:-NO-:-OTHER
election_type:  G
year:  24
race:  BI1
district:
party:
name:  NO
"Should all medically appropriate assisted reproductive treatments, including, but not limited to, in vitro fertilization, be covered by any health insurance plan in Illinois that provides coverage for pregnancy benefits, without limitation on the number of treatments?"-:-YES-:-OTHER
election_type:  G
year:  24
race:  BI1
district:
party:
name:  YES
"Should any candidate appearing on the Illinois ballot for federal, State, or local office be subject to civil penalties if the candidate interferes or attempts to interfere with an election worker's official duties?"-:-NO-:-OTHER
election_type:  G
year:  24
race:  BI3
district:
party:
name:  NO
"Should any candidate appearing on the Illinois ballot for federal, State, or local office be subject to civil penalties if the candidate interferes or attempts to interfere with an election worker's official duties?"-:-YES-:-OTHER
election_type:  G
year:  24
race:  BI3
district:
party:
name:  YES
"Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $1,000,000 for the purpose of dedicating funds raised to property tax relief?"-:-NO-:-OTHER
election_type:  G
year:  24
race:  BI2
district:
party:
name:  NO
"Should the Illinois Constitution be amended to create an additional 3% tax on income greater than $1,000,000 for the purpose of dedicating funds raised to property tax relief?"-:-YES-:-OTHER
election_type:  G
year:  24
race:  BI2
district:
party:
name:  YES
100TH REPRESENTATIVE-:-Christopher "C.D." Davidsmeyer-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  100
party:  R
name:  DAV
101ST REPRESENTATIVE-:-Chris G. Miller-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  101
party:  R
name:  MIL
102ND REPRESENTATIVE-:-Adam M. Niemerg-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  102
party:  R
name:  NIE
103RD REPRESENTATIVE-:-Carol Ammons-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  103
party:  D
name:  AMM
104TH REPRESENTATIVE-:-Brandun Schweizer-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  104
party:  R
name:  SCH
104TH REPRESENTATIVE-:-Jarrett Clem-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  104
party:  D
name:  CLE
105TH REPRESENTATIVE-:-Dennis Tipsword Jr.-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  105
party:  R
name:  TIP
105TH REPRESENTATIVE-:-Morgan Phillips-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  105
party:  D
name:  PHI
106TH REPRESENTATIVE-:-Jason R. Bunting-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  106
party:  R
name:  BUN
107TH REPRESENTATIVE-:-Brad Halbrook-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  107
party:  R
name:  HAL
108TH REPRESENTATIVE-:-Wayne A. Rosenthal-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  108
party:  R
name:  ROS
109TH REPRESENTATIVE-:-Charlie Meier-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  109
party:  R
name:  MEI
10TH CONGRESS-:-Brad Schneider-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  10
party:  D
name:  SCH
10TH CONGRESS-:-Jim Carris-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  10
party:  R
name:  CAR
10TH CONGRESS-:-Joseph Severino-:-OTHER
election_type:  G
year:
race:  CON
district:  10
party:  O
name:  SEV
10TH REPRESENTATIVE-:-Jawaharial "Omar" Williams-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  010
party:  D
name:  WIL
10TH SENATE-:-Jon Luers-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  10
party:  R
name:  LUE
10TH SENATE-:-Robert Martwick-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  10
party:  D
name:  MAR
110TH REPRESENTATIVE-:-Blaine Wilhour-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  110
party:  R
name:  WIL
111TH REPRESENTATIVE-:-Amy Elik-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  111
party:  R
name:  ELI
111TH REPRESENTATIVE-:-Nick Raftopoulos-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  111
party:  D
name:  RAF
112TH REPRESENTATIVE-:-Jay Keeven-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  112
party:  R
name:  KEE
112TH REPRESENTATIVE-:-Katie Stuart-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  112
party:  D
name:  STU
113TH REPRESENTATIVE-:-Jay Hoffman-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  113
party:  D
name:  HOF
114TH REPRESENTATIVE-:-Kevin Schmidt-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  114
party:  R
name:  SCH
114TH REPRESENTATIVE-:-LaToya Greenwood-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  114
party:  D
name:  GRE
115TH REPRESENTATIVE-:-David Friess-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  115
party:  R
name:  FRI
116TH REPRESENTATIVE-:-Dave Severin-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  116
party:  R
name:  SEV
117TH REPRESENTATIVE-:-Patrick Windhorst-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  117
party:  R
name:  WIN
118TH REPRESENTATIVE-:-Paul Jacobs-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  118
party:  R
name:  JAC
11TH CONGRESS-:-Anna Schiefelbein-:-OTHER
election_type:  G
year:
race:  CON
district:  11
party:  O
name:  SCH
11TH CONGRESS-:-Bill Foster-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  11
party:  D
name:  FOS
11TH CONGRESS-:-Jerry Evans-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  11
party:  R
name:  EVA
11TH REPRESENTATIVE-:-Ann M. Williams-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  011
party:  D
name:  WIL
12TH CONGRESS-:-Brian Roberts-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  12
party:  D
name:  ROB
12TH CONGRESS-:-Mike Bost-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  12
party:  R
name:  BOS
12TH REPRESENTATIVE-:-Margaret Croke-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  012
party:  D
name:  CRO
13TH CONGRESS-:-Chibuihe Asonye-:-OTHER
election_type:  G
year:
race:  CON
district:  13
party:  O
name:  ASO
13TH CONGRESS-:-Joshua Loyd-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  13
party:  R
name:  LOY
13TH CONGRESS-:-Nikki Budzinski-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  13
party:  D
name:  BUD
13TH REPRESENTATIVE-:-Hoan Huynh-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  013
party:  D
name:  HUY
13TH REPRESENTATIVE-:-Terry Nguyen Le-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  013
party:  R
name:  LE
13TH SENATE-:-Robert Peters-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  13
party:  D
name:  PET
14TH CONGRESS-:-Constant Connor VlaKancic-:-OTHER
election_type:  G
year:
race:  CON
district:  14
party:  O
name:  VLA
14TH CONGRESS-:-James T. "Jim" Marter-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  14
party:  R
name:  MAR
14TH CONGRESS-:-Lauren Underwood-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  14
party:  D
name:  UND
14TH CONGRESS-:-Roy Jones-:-OTHER
election_type:  G
year:
race:  CON
district:  14
party:  O
name:  JON
14TH REPRESENTATIVE-:-Kelly M. Cassidy-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  014
party:  D
name:  CAS
15TH CONGRESS-:-Mary E. Miller-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  15
party:  R
name:  MIL
15TH CONGRESS-:-William Bonnett-:-OTHER
election_type:  G
year:
race:  CON
district:  15
party:  O
name:  BON
15TH REPRESENTATIVE-:-Mark R. Albers-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  015
party:  R
name:  ALB
15TH REPRESENTATIVE-:-Michael J. Kelly-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  015
party:  D
name:  KEL
16TH CONGRESS-:-Darin LaHood-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  16
party:  R
name:  LAH
16TH CONGRESS-:-Scott Summers-:-OTHER
election_type:  G
year:
race:  CON
district:  16
party:  O
name:  SUM
16TH REPRESENTATIVE-:-Kevin John Olickal-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  016
party:  D
name:  OLI
16TH SENATE-:-Willie Preston-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  16
party:  D
name:  PRE
17TH CONGRESS-:-Eric Sorensen-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  17
party:  D
name:  SOR
17TH CONGRESS-:-Joe McGraw-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  17
party:  R
name:  MCG
17TH REPRESENTATIVE-:-Jennifer Gong-Gershowitz-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  017
party:  D
name:  GON
17TH REPRESENTATIVE-:-Jim Geldermann-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  017
party:  R
name:  GEL
18TH REPRESENTATIVE-:-Charles Hutchinson-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  018
party:  R
name:  HUT
18TH REPRESENTATIVE-:-Robyn Gabel-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  018
party:  D
name:  GAB
19TH REPRESENTATIVE-:-John "JZ" Zimmers-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  019
party:  R
name:  ZIM
19TH REPRESENTATIVE-:-Lindsey LaPointe-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  019
party:  D
name:  LAP
19TH SENATE-:-Michael E. Hastings-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  19
party:  D
name:  HAS
19TH SENATE-:-Samantha Jean Gasca-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  19
party:  R
name:  GAS
1ST CONGRESS-:-Hilary Myrick-Winston-:-OTHER
election_type:  G
year:
race:  CON
district:  01
party:  O
name:  MYR
1ST CONGRESS-:-Jonathan L. Jackson-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  01
party:  D
name:  JAC
1ST CONGRESS-:-Marcus Lewis-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  01
party:  R
name:  LEW
1ST REPRESENTATIVE-:-Aaron M. Ortiz-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  001
party:  D
name:  ORT
1ST SENATE-:-Javier Loera Cervantes-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  01
party:  D
name:  CER
1ST SUPREME - BURKE VACANCY-:-Joy Virginia Cunningham-:-DEMOCRATIC
election_type:  G
year:
race:  SC
district:  1
party:  D
name:  CUN
20TH REPRESENTATIVE-:-Brad Stephens-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  020
party:  R
name:  STE
20TH SENATE-:-Graciela Guzman-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  20
party:  D
name:  GUZ
20TH SENATE-:-Jason Proctor-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  20
party:  R
name:  PRO
21ST REPRESENTATIVE-:-Abdelnasser Rashid-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  021
party:  D
name:  RAS
22ND REPRESENTATIVE-:-Angie Guerrero-Cuellar-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  022
party:  D
name:  GUE
22ND SENATE-:-Cristina Castro-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  22
party:  D
name:  CAS
23RD REPRESENTATIVE-:-Edgar Gonzalez, Jr.-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  023
party:  D
name:  GON
24TH REPRESENTATIVE-:-Natalian Bolton-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  024
party:  R
name:  BOL
24TH REPRESENTATIVE-:-Theresa Mah-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  024
party:  D
name:  MAH
25TH REPRESENTATIVE-:-Curtis J. Tarver II-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  025
party:  D
name:  TAR
25TH SENATE-:-Heather Brown-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  25
party:  R
name:  BRO
25TH SENATE-:-Karina Villa-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  25
party:  D
name:  VIL
26TH REPRESENTATIVE-:-Audrey Barrett-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  026
party:  R
name:  BAR
26TH REPRESENTATIVE-:-Kam Buckner-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  026
party:  D
name:  BUC
27TH REPRESENTATIVE-:-Justin Q. Slaughter-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  027
party:  D
name:  SLA
27TH SENATE-:-Mark L. Walker-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  27
party:  D
name:  WAL
27TH SENATE-:-Tom Schlenhardt-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  27
party:  R
name:  SCH
28TH REPRESENTATIVE-:-Robert "Bob" Rita-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  028
party:  D
name:  RIT
28TH SENATE-:-Laura M. Murphy-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  28
party:  D
name:  MUR
29TH REPRESENTATIVE-:-Marketa Franklin-:-OTHER
election_type:  G
year:
race:  SL
district:  029
party:  O
name:  FRA
29TH REPRESENTATIVE-:-Thaddeus Jones-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  029
party:  D
name:  JON
2ND CONGRESS-:-Ashley Ramos-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  02
party:  R
name:  RAM
2ND CONGRESS-:-Hilary Myrick-Winston-:-OTHER
election_type:  G
year:
race:  CON
district:  02
party:  O
name:  MYR
2ND CONGRESS-:-Mike Vick-:-OTHER
election_type:  G
year:
race:  CON
district:  02
party:  O
name:  VIC
2ND CONGRESS-:-Robin Kelly-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  02
party:  D
name:  KEL
2ND REPRESENTATIVE-:-Elizabeth "Lisa" Hernandez-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  002
party:  D
name:  HER
2ND REPRESENTATIVE-:-Laura Hruska-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  002
party:  R
name:  HRU
30TH REPRESENTATIVE-:-Patricia Bonk-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  030
party:  R
name:  BON
30TH REPRESENTATIVE-:-William "Will" Davis-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  030
party:  D
name:  DAV
31ST REPRESENTATIVE-:-Carl R. Kunz-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  031
party:  R
name:  KUN
31ST REPRESENTATIVE-:-Michael Crawford-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  031
party:  D
name:  CRA
31ST SENATE-:-Ashley Jensen-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  31
party:  R
name:  JEN
31ST SENATE-:-Mary Edly-Allen-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  31
party:  D
name:  EDL
32ND REPRESENTATIVE-:-Lisa J. Davis-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  032
party:  D
name:  DAV
33RD REPRESENTATIVE-:-Marcus C. Evans, Jr.-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  033
party:  D
name:  EVA
34TH REPRESENTATIVE-:-Frederick L. Walls-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  034
party:  R
name:  WAL
34TH REPRESENTATIVE-:-Nicholas "Nick" Smith-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  034
party:  D
name:  SMI
34TH SENATE-:-Crystal Villarreal Soltow-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  34
party:  R
name:  SOL
34TH SENATE-:-Steve Stadelman-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  34
party:  D
name:  STA
35TH REPRESENTATIVE-:-Herbert Hebein-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  035
party:  R
name:  HEB
35TH REPRESENTATIVE-:-Mary Gill-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  035
party:  D
name:  GIL
36TH REPRESENTATIVE-:-Christine Shanahan McGovern-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  036
party:  R
name:  MCG
36TH REPRESENTATIVE-:-Rick Ryan-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  036
party:  D
name:  RYA
37TH REPRESENTATIVE-:-Patrick Sheehan-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  037
party:  R
name:  SHE
37TH SENATE-:-Li Arellano, Jr.-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  37
party:  R
name:  ARE
38TH REPRESENTATIVE-:-Debbie Meyers-Martin-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  038
party:  D
name:  MEY
39TH REPRESENTATIVE-:-Anthony Curran-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  039
party:  R
name:  CUR
39TH REPRESENTATIVE-:-Justin Tucker-:-OTHER
election_type:  G
year:
race:  SL
district:  039
party:  O
name:  TUC
39TH REPRESENTATIVE-:-Will Guzzardi-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  039
party:  D
name:  GUZ
3RD CONGRESS-:-Angel Oakley-:-OTHER
election_type:  G
year:
race:  CON
district:  03
party:  O
name:  OAK
3RD CONGRESS-:-Delia Ramirez-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  03
party:  D
name:  RAM
3RD CONGRESS-:-John Booras-:-REPUBLICAN
election_type:  G
year:
race:  CON
district:  03
party:  R
name:  BOO
3RD REPRESENTATIVE-:-Eva-Dina Delgado-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  003
party:  D
name:  DEL
40TH REPRESENTATIVE-:-Jaime M. Andrade, Jr.-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  040
party:  D
name:  AND
40TH REPRESENTATIVE-:-Patrycja Karlin-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  040
party:  R
name:  KAR
40TH SENATE-:-Patrick Joyce-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  40
party:  D
name:  JOY
40TH SENATE-:-Philip Nagel-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  40
party:  R
name:  NAG
41ST REPRESENTATIVE-:-Janet Yang Rohr-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  041
party:  D
name:  ROH
42ND REPRESENTATIVE-:-Amar Patel-:-OTHER
election_type:  G
year:
race:  SL
district:  042
party:  O
name:  PAT
42ND REPRESENTATIVE-:-Terra Costa Howard-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  042
party:  D
name:  HOW
43RD REPRESENTATIVE-:-Anna Moeller-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  043
party:  D
name:  MOE
43RD REPRESENTATIVE-:-Donald P. Puckett-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  043
party:  R
name:  PUC
43RD SENATE-:-Jennifer "Jen" Monson-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  43
party:  R
name:  MON
43RD SENATE-:-Rachel Ventura-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  43
party:  D
name:  VEN
44TH REPRESENTATIVE-:-Fred Crespo-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  044
party:  D
name:  CRE
45TH REPRESENTATIVE-:-Dennis M. Reboletti-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  045
party:  R
name:  REB
45TH REPRESENTATIVE-:-Martha "Marti" Deuter-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  045
party:  D
name:  DEU
46TH REPRESENTATIVE-:-Diane Blair-Sherlock-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  046
party:  D
name:  BLA
46TH REPRESENTATIVE-:-Robert "Rusty" Stevens-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  046
party:  R
name:  STE
46TH SENATE-:-Dave Koehler-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  46
party:  D
name:  KOE
46TH SENATE-:-Sally Owens-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  46
party:  R
name:  OWE
47TH REPRESENTATIVE-:-Amy L. Grant-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  047
party:  R
name:  GRA
47TH REPRESENTATIVE-:-Jackie Williamson-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  047
party:  D
name:  WIL
48TH REPRESENTATIVE-:-Jennifer Sanalitro-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  048
party:  R
name:  SAN
48TH REPRESENTATIVE-:-Maria C. Vesey-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  048
party:  D
name:  VES
49TH REPRESENTATIVE-:-Hannah Billingsley-:-REPUBLICAN
election_type:  G
year:
race:  SL
district:  049
party:  R
name:  BIL
49TH REPRESENTATIVE-:-Maura Hirschauer-:-DEMOCRATIC
election_type:  G
year:
race:  SL
district:  049
party:  D
name:  HIR
49TH SENATE-:-Katie Deane-Schlottman-:-REPUBLICAN
election_type:  G
year:
race:  SU
district:  49
party:  R
name:  DEA
49TH SENATE-:-Meg Loughran Cappel-:-DEMOCRATIC
election_type:  G
year:
race:  SU
district:  49
party:  D
name:  CAP
4TH CONGRESS-:-Alicia Martinez-:-OTHER
election_type:  G
year:
race:  CON
district:  04
party:  O
name:  MAR
4TH CONGRESS-:-Ed Hershey-:-WORKING CLASS PARTY
election_type:  G
year:
race:  CON
district:  04
party:  W
name:  HER
4TH CONGRESS-:-Jesus "Chuy" Garcia-:-DEMOCRATIC
election_type:  G
year:
race:  CON
district:  04
party:  D
name:  GAR

In [462]:
pivoted_county.rename(columns = race_updates_dict, inplace = True)

In [463]:
pivoted_county  = pivoted_county.fillna(0)

In [464]:
set(pivoted_county["County"].unique()).difference(pivoted_filtered["JurisName"].unique())

set()

In [465]:
pivoted_county["County"].unique()

array(['ADAMS', 'ALEXANDER', 'BOND', 'BOONE', 'BROWN', 'BUREAU',
       'CALHOUN', 'CARROLL', 'CASS', 'CHAMPAIGN', 'CHRISTIAN', 'CLARK',
       'CLAY', 'CLINTON', 'COLES', 'COOK', 'CRAWFORD', 'CUMBERLAND',
       'DOUGLAS', 'DeKALB', 'DeWITT', 'DuPAGE', 'EDGAR', 'EDWARDS',
       'EFFINGHAM', 'FAYETTE', 'FORD', 'FRANKLIN', 'FULTON', 'GALLATIN',
       'GREENE', 'GRUNDY', 'HAMILTON', 'HANCOCK', 'HARDIN', 'HENDERSON',
       'HENRY', 'IROQUOIS', 'JACKSON', 'JASPER', 'JEFFERSON', 'JERSEY',
       'JOHNSON', 'JoDAVIESS', 'KANE', 'KANKAKEE', 'KENDALL', 'KNOX',
       'LAKE', 'LAWRENCE', 'LEE', 'LIVINGSTON', 'LOGAN', 'LaSALLE',
       'MACON', 'MACOUPIN', 'MADISON', 'MARION', 'MARSHALL', 'MASON',
       'MASSAC', 'MENARD', 'MERCER', 'MONROE', 'MONTGOMERY', 'MORGAN',
       'MOULTRIE', 'McDONOUGH', 'McHENRY', 'McLEAN', 'OGLE', 'PEORIA',
       'PERRY', 'PIATT', 'PIKE', 'POPE', 'PULASKI', 'PUTNAM', 'RANDOLPH',
       'RICHLAND', 'ROCK ISLAND', 'SALINE', 'SANGAMON', 'SCHUYLER',
       'SCOTT', 'SHELBY', 'ST. CLAIR', 'STARK', 'STEPHENSON', 'TAZEWELL',
       'UNION', 'VERMILION', 'WABASH', 'WARREN', 'WASHINGTON', 'WAYNE',
       'WHITE', 'WHITESIDE', 'WILL', 'WILLIAMSON', 'WINNEBAGO',
       'WOODFORD'], dtype=object)

In [466]:
set(pivoted_filtered["JurisName"].unique()).difference(pivoted_county["County"].unique())

{'CITY OF BLOOMINGTON',
 'CITY OF CHICAGO',
 'CITY OF DANVILLE',
 'CITY OF EAST ST. LOUIS',
 'CITY OF GALESBURG',
 'CITY OF ROCKFORD'}

In [467]:
juris_counties = {'CITY OF BLOOMINGTON':"McLEAN",
 'CITY OF CHICAGO':"COOK",
 'CITY OF DANVILLE':"VERMILION",
 'CITY OF EAST ST. LOUIS':"ST. CLAIR",
 'CITY OF GALESBURG':"KNOX",
 'CITY OF ROCKFORD':"WINNEBAGO"}

In [468]:
pivoted_filtered["County"] = pivoted_filtered["JurisName"].map(juris_counties).fillna(pivoted_filtered["JurisName"])

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/257390807.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pivoted_filtered["County"] = pivoted_filtered["JurisName"].map(juris_counties).fillna(pivoted_filtered["JurisName"])

In [469]:
shared = [i for i in set(pivoted_filtered.columns).intersection(set(pivoted_county.columns)) if i != 'County']

In [470]:
[i for i in set(pivoted_filtered.columns).difference(set(pivoted_county.columns)) if "OWRI" not in i]

['JurisName', 'pivot_col']

In [471]:
pdv.county_totals_check(pivoted_county, "County", pivoted_filtered, "Precinct", shared, "County", full_print=False, method='county')

***Countywide Totals Check***

Counties that match:

['ADAMS', 'ALEXANDER', 'BOND', 'BOONE', 'BROWN', 'BUREAU', 'CALHOUN', 'CARROLL', 'CASS', 'CHAMPAIGN', 'CHRISTIAN', 'CLARK', 'CLAY', 'CLINTON', 'COLES', 'COOK', 'CRAWFORD', 'CUMBERLAND', 'DOUGLAS', 'DeKALB', 'DeWITT', 'DuPAGE', 'EDGAR', 'EDWARDS', 'EFFINGHAM', 'FAYETTE', 'FORD', 'FRANKLIN', 'FULTON', 'GALLATIN', 'GREENE', 'GRUNDY', 'HAMILTON', 'HANCOCK', 'HARDIN', 'HENDERSON', 'HENRY', 'IROQUOIS', 'JACKSON', 'JASPER', 'JEFFERSON', 'JERSEY', 'JOHNSON', 'JoDAVIESS', 'KANE', 'KANKAKEE', 'KENDALL', 'KNOX', 'LAKE', 'LAWRENCE', 'LEE', 'LIVINGSTON', 'LOGAN', 'LaSALLE', 'MACON', 'MACOUPIN', 'MADISON', 'MARION', 'MARSHALL', 'MASON', 'MASSAC', 'MENARD', 'MERCER', 'MONROE', 'MONTGOMERY', 'MORGAN', 'MOULTRIE', 'McDONOUGH', 'McHENRY', 'McLEAN', 'OGLE', 'PEORIA', 'PERRY', 'PIATT', 'PIKE', 'POPE', 'PULASKI', 'PUTNAM', 'RANDOLPH', 'RICHLAND', 'ROCK ISLAND', 'SALINE', 'SANGAMON', 'SCHUYLER', 'SCOTT', 'SHELBY', 'ST. CLAIR', 'STARK', 'STEPHENSON', 'TAZEWELL', 'UNION', 'VERMILION', 'WABASH', 'WARREN', 'WASHINGTON', 'WAYNE', 'WHITE', 'WHITESIDE', 'WILL', 'WILLIAMSON', 'WINNEBAGO', 'WOODFORD']

In [472]:
pdv.county_totals_check(pivoted_county, "County", pivoted_filtered, "Precinct", shared, "County", full_print=False, method='race')

***Countywide Totals Check***

GSL066RPAR is equal across all counties
GSL010DWIL is equal across all counties
GSL026RBAR is equal across all counties
GSL083DHAN is equal across all counties
GSL053RAND is equal across all counties
GCON08RRIC is equal across all counties
GSL029DJON is equal across all counties
GSL031DCRA is equal across all counties
GSL082RHA is equal across all counties
G24PREIKEN is equal across all counties
GSL050DHER is equal across all counties
GSL006RDWY is equal across all counties
GSL068DVEL is equal across all counties
GSU43RMON is equal across all counties
GSU52DFAR is equal across all counties
GSL005RRAS is equal across all counties
GCON14DUND is equal across all counties
GSL064RWEB is equal across all counties
GSL108RROS is equal across all counties
GSL076RBIS is equal across all counties
GSL039RCUR is equal across all counties
GSL024DMAH is equal across all counties
GSL063RREI is equal across all counties
GSL079DMOR is equal across all counties
GSL087RHAU is equal across all counties
GSU04RSUM is equal across all counties
GSL109RMEI is equal across all counties
GSL099RMOO is equal across all counties
GCON14RMAR is equal across all counties
GSL069DJAN is equal across all counties
GSL034DSMI is equal across all counties
GSL105RTIP is equal across all counties
GCON01RLEW is equal across all counties
GSL102RNIE is equal across all counties
GSL073RSPA is equal across all counties
GCON10RCAR is equal across all counties
GCON17RMCG is equal across all counties
GSL046RSTE is equal across all counties
GSL095DCHI is equal across all counties
GSL020RSTE is equal across all counties
GSL058DMOR is equal across all counties
GSU22DCAS is equal across all counties
GSL005DDUB is equal across all counties
GSU43DVEN is equal across all counties
GSU16DPRE is equal across all counties
GCON13RLOY is equal across all counties
GSL013RLE is equal across all counties
GSL079RHAA is equal across all counties
GSL012DCRO is equal across all counties
GSL009DMOR is equal across all counties
GSL040DAND is equal across all counties
GSL113DHOF is equal across all counties
GSL034RWAL is equal across all counties
G24BI3YES is equal across all counties
GSL076DBRI is equal across all counties
GSU53RBAL is equal across all counties
GSL019RZIM is equal across all counties
GSL016DOLI is equal across all counties
GSL036RMCG is equal across all counties
GSL028DRIT is equal across all counties
GSL017DGON is equal across all counties
GSL046DBLA is equal across all counties
GSL118RJAC is equal across all counties
GSL114RSCH is equal across all counties
GSL089RMCC is equal across all counties
GCON16RLAH is equal across all counties
GSL057DMUH is equal across all counties
GSL030DDAV is equal across all counties
GCON12DROB is equal across all counties
GSL062DDIA is equal across all counties
GSL065DROB is equal across all counties
G24PRERTRU is equal across all counties
GCON08DKRI is equal across all counties
GCON09DSCH is equal across all counties
GSL080RBEA is equal across all counties
GSL048DVES is equal across all counties
GSL011DWIL is equal across all counties
GSL111RELI is equal across all counties
GSU25DVIL is equal across all counties
GSL042DHOW is equal across all counties
GSL101RMIL is equal across all counties
GSL051DSYE is equal across all counties
GSL075DHEN is equal across all counties
GSU49RDEA is equal across all counties
G24BI2NO is equal across all counties
GSL080DDEL is equal across all counties
GSL114DGRE is equal across all counties
GSU46DKOE is equal across all counties
GSU55RPLU is equal across all counties
GSL045RREB is equal across all counties
GSL071RSWA is equal across all counties
GSL049DHIR is equal across all counties
GSL084DKIF is equal across all counties
GSL107RHAL is equal across all counties
GSU20RPRO is equal across all counties
GSL038DMEY is equal across all counties
GSL015DKEL is equal across all counties
GSL052RMCL is equal across all counties
GSL074RFRI is equal across all counties
GSL077RAIR is equal across all counties
GSU40RNAG is equal across all counties
GCON02DKEL is equal across all counties
GCON15RMIL is equal across all counties
GSL075RDAV is equal across all counties
GSL112DSTU is equal across all counties
GCON06RCON is equal across all counties
GSL008RCOL is equal across all counties
GSL072DJOH is equal across all counties
GSL067DWES is equal across all counties
GSL112RKEE is equal across all counties
GSL061RMIT is equal across all counties
GCON02RRAM is equal across all counties
GSL053DGRA is equal across all counties
GCON05RHAN is equal across all counties
GSL104DCLE is equal across all counties
GCON11REVA is equal across all counties
GSL006DHAR is equal across all counties
GSL092DGOR is equal across all counties
GCON12RBOS is equal across all counties
GSL035RHEB is equal across all counties
GSL078DLIL is equal across all counties
GSL093RWEA is equal across all counties
GSL070RKEI is equal across all counties
GSU28DMUR is equal across all counties
GSL025DTAR is equal across all counties
GSL044DCRE is equal across all counties
GSL082DAKH is equal across all counties
GSU31RJEN is equal across all counties
GSL056DMUS is equal across all counties
GSL022DGUE is equal across all counties
GSL041DROH is equal across all counties
GSL105DPHI is equal across all counties
GSL106RBUN is equal across all counties
GSU05DCOL is equal across all counties
GSL004DJIM is equal across all counties
GSL104RSCH is equal across all counties
GSL002RHRU is equal across all counties
GSL100RDAV is equal across all counties
GSL086DWAL is equal across all counties
GSL047DWIL is equal across all counties
GSL033DEVA is equal across all counties
GSL024RBOL is equal across all counties
GSL111DRAF is equal across all counties
GSL066DNES is equal across all counties
GSL086RLAN is equal across all counties
GSL030RBON is equal across all counties
GSU10RLUE is equal across all counties
GSU20DGUZ is equal across all counties
GSU52RBRO is equal across all counties
GSU27DWAL is equal across all counties
GSL059RHEN is equal across all counties
GSL116RSEV is equal across all counties
GSL063DMAH is equal across all counties
GSL081RPOR is equal across all counties
GSL013DHUY is equal across all counties
GSL096DSCH is equal across all counties
GCON01DJAC is equal across all counties
GSC1DCUN is equal across all counties
GSL026DBUC is equal across all counties
GCON07DDAV is equal across all counties
GCON03DRAM is equal across all counties
GSL014DCAS is equal across all counties
GSU04DLIG is equal across all counties
GSU13DPET is equal across all counties
GSU34DSTA is equal across all counties
GSL091DCHU is equal across all counties
GSU19DHAS is equal across all counties
GSL031RKUN is equal across all counties
GSL007DWEL is equal across all counties
GSL060DMAY is equal across all counties
GSL098DMAN is equal across all counties
GCON04DGAR is equal across all counties
GSL058RLAM is equal across all counties
GSL018DGAB is equal across all counties
GSC4RWHI is equal across all counties
GSL032DDAV is equal across all counties
G24BI1YES is equal across all counties
GSU01DCER is equal across all counties
GSL061DMAS is equal across all counties
GSU25RBRO is equal across all counties
GSL088RDEE is equal across all counties
GSL090RCAB is equal across all counties
GCON04RCAS is equal across all counties
GSL065RUGA is equal across all counties
GSL048RSAN is equal across all counties
GSU10DMAR is equal across all counties
GSL019DLAP is equal across all counties
GSU46ROWE is equal across all counties
GCON03RBOO is equal across all counties
GSU34RSOL is equal across all counties
GSU58RBRY is equal across all counties
G24BI2YES is equal across all counties
GSL047RGRA is equal across all counties
GSU07DSIM is equal across all counties
G24PREDHAR is equal across all counties
GSU40DJOY is equal across all counties
GSL049RBIL is equal across all counties
GSL085DAVE is equal across all counties
GSL110RWIL is equal across all counties
GSU19RGAS is equal across all counties
GSL023DGON is equal across all counties
GSL035DGIL is equal across all counties
GSU31DEDL is equal across all counties
GSL051RUFO is equal across all counties
GSL067ROLA is equal across all counties
GSU37RARE is equal across all counties
GSL039DGUZ is equal across all counties
GSL017RGEL is equal across all counties
GSL074DSIM is equal across all counties
G24BI3NO is equal across all counties

GSL087IGIL is equal across all counties
GSL103DAMM is equal across all counties
GCON05DQUI is equal across all counties
GSL059DDID is equal across all counties
GCON07RKOP is equal across all counties
GSU27RSCH is equal across all counties
GSL027DSLA is equal across all counties
GSL018RHUT is equal across all counties
GCON17DSOR is equal across all counties
GSL081DSTA is equal across all counties
GSL052DPET is equal across all counties
GSL054RHUN is equal across all counties
GSL072RHEL is equal across all counties
GSL096RSMI is equal across all counties
GSL115RFRI is equal across all counties
GCON04WHER is equal across all counties
GSL037RSHE is equal across all counties
GSL069RSOS is equal across all counties
GSL008DFOR is equal across all counties
GSL003DDEL is equal across all counties
G24BI1NO is equal across all counties
GSL043RPUC is equal across all counties
GCON13DBUD is equal across all counties
GSL001DORT is equal across all counties
GSL050RALE is equal across all counties
GSL070DOLS is equal across all counties
GSL002DHER is equal across all counties
GSL117RWIN is equal across all counties
GSL054DCAN is equal across all counties
GCON06DCAS is equal across all counties
GCON11DFOS is equal across all counties
GSL021DRAS is equal across all counties
GSL040RKAR is equal across all counties
GSL045DDEU is equal across all counties
GCON09RCOH is equal across all counties
GSL015RALB is equal across all counties
GCON10DSCH is equal across all counties
GSL097RSHA is equal across all counties
GSU49DCAP is equal across all counties
GSL036DRYA is equal across all counties
GSL094RHAM is equal across all counties
GSL055DMOY is equal across all counties
GSL043DMOE is equal across all counties
GSL077DHER is equal across all counties
GSL085RMET is equal across all counties
GSL057RBEH is equal across all counties
GSL095RCOF is equal across all counties
GSL097DBEN is equal across all counties
GSL091RAND is equal across all counties

In [473]:
# df_allocated = pivoted_filtered[pivoted_filtered["pivot_col"].str.contains("FEDERAL")]
# df_receiving = pivoted_filtered[~pivoted_filtered["pivot_col"].str.contains("FEDERAL")]

# cols = [i for i in list(df_receiving.columns) if i not in ['pivot_col','JurisName','County']]

# pivoted_filtered = pdv.allocate_absentee(df_receiving, df_allocated, cols, "County", allocating_to_all_empty_precs=False)

# pivoted_filtered.to_csv("./results_temp.csv", index = False)

In [474]:
pivoted_filtered.rename(columns = {"pivot_col":"UNIQUE_ID"}, inplace = True)

In [475]:
pivoted_filtered

cand_col,UNIQUE_ID,JurisName,G24BI1NO,G24BI1YES,G24BI2NO,G24BI2YES,G24BI3NO,G24BI3YES,G24PREDHAR,G24PREIKEN,...,GSU46DKOE,GSU46ROWE,GSU49DCAP,GSU49RDEA,GSU52DFAR,GSU52RBRO,GSU53RBAL,GSU55RPLU,GSU58RBRY,County
0,ADAMS-:-BEVERLY PCT 1,ADAMS,83,86,109,60,31,140,28,1,...,0,0,0,0,0,0,0,0,0,ADAMS
1,ADAMS-:-BURTON PCT 1,ADAMS,270,241,339,177,94,419,65,2,...,0,0,0,0,0,0,0,0,0,ADAMS
2,ADAMS-:-CAMP POINT PCT 1,ADAMS,189,208,233,160,77,322,54,3,...,0,0,0,0,0,0,0,0,0,ADAMS
3,ADAMS-:-CAMP POINT PCT 2,ADAMS,214,248,276,187,81,372,49,2,...,0,0,0,0,0,0,0,0,0,ADAMS
4,ADAMS-:-CLAYTON PCT 1,ADAMS,202,241,238,203,78,365,75,6,...,0,0,0,0,0,0,0,0,0,ADAMS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9315,WOODFORD-:-WORTH 4,WOODFORD,240,346,312,276,94,498,222,9,...,0,0,0,0,0,0,0,0,0,WOODFORD
9316,WOODFORD-:-WORTH 5,WOODFORD,242,309,307,249,86,471,221,11,...,0,0,0,0,0,0,0,0,0,WOODFORD
9317,WOODFORD-:-WORTH 6,WOODFORD,210,290,228,272,63,441,200,10,...,0,0,0,0,0,0,0,0,0,WOODFORD
9318,WOODFORD-:-WORTH 7,WOODFORD,376,474,439,420,122,735,348,14,...,0,0,0,0,0,0,0,0,0,WOODFORD
9319,WOODFORD-:-WORTH 9,WOODFORD,476,522,562,440,167,831,260,19,...,0,0,0,0,0,0,445,0,0,WOODFORD

In [476]:
pivoted_filtered['County'].unique()

array(['ADAMS', 'ALEXANDER', 'BOND', 'BOONE', 'BROWN', 'BUREAU',
       'CALHOUN', 'CARROLL', 'CASS', 'CHAMPAIGN', 'CHRISTIAN', 'McLEAN',
       'COOK', 'VERMILION', 'ST. CLAIR', 'KNOX', 'WINNEBAGO', 'CLARK',
       'CLAY', 'CLINTON', 'COLES', 'CRAWFORD', 'CUMBERLAND', 'DOUGLAS',
       'DeKALB', 'DeWITT', 'DuPAGE', 'EDGAR', 'EDWARDS', 'EFFINGHAM',
       'FAYETTE', 'FORD', 'FRANKLIN', 'FULTON', 'GALLATIN', 'GREENE',
       'GRUNDY', 'HAMILTON', 'HANCOCK', 'HARDIN', 'HENDERSON', 'HENRY',
       'IROQUOIS', 'JACKSON', 'JASPER', 'JEFFERSON', 'JERSEY', 'JOHNSON',
       'JoDAVIESS', 'KANE', 'KANKAKEE', 'KENDALL', 'LAKE', 'LAWRENCE',
       'LEE', 'LIVINGSTON', 'LOGAN', 'LaSALLE', 'MACON', 'MACOUPIN',
       'MADISON', 'MARION', 'MARSHALL', 'MASON', 'MASSAC', 'MENARD',
       'MERCER', 'MONROE', 'MONTGOMERY', 'MORGAN', 'MOULTRIE',
       'McDONOUGH', 'McHENRY', 'OGLE', 'PEORIA', 'PERRY', 'PIATT', 'PIKE',
       'POPE', 'PULASKI', 'PUTNAM', 'RANDOLPH', 'RICHLAND', 'ROCK ISLAND',
       'SALINE', 'SANGAMON', 'SCHUYLER', 'SCOTT', 'SHELBY', 'STARK',
       'STEPHENSON', 'TAZEWELL', 'UNION', 'WABASH', 'WARREN',
       'WASHINGTON', 'WAYNE', 'WHITE', 'WHITESIDE', 'WILL', 'WILLIAMSON',
       'WOODFORD'], dtype=object)

In [477]:
fips_file = pd.read_csv("./raw-from-source/FIPS/US_FIPS_Codes.csv")
fips_file = fips_file[fips_file["State"]=="Illinois"]
fips_file["FIPS County"] = fips_file["FIPS County"].astype(str)
fips_file["FIPS County"] = fips_file["FIPS County"].str.zfill(3)
fips_file["County Name"] = fips_file["County Name"].map({'St Clair':'ST. CLAIR',
'Du Page':'DuPAGE',
'De Kalb':'DeKALB',
'Jo Daviess':'JoDAVIESS',
'La Salle':'LaSALLE'}).fillna(fips_file["County Name"])
fips_dict = dict(zip(fips_file['County Name'].str.upper(), fips_file['FIPS County']))
pivoted_filtered['COUNTYFP'] = pivoted_filtered['County'].str.upper().map(fips_dict).fillna(pivoted_filtered['County'])
pivoted_filtered['COUNTYFP'] = pivoted_filtered['COUNTYFP'].astype(str)
pivoted_filtered['COUNTYFP'] = pivoted_filtered['COUNTYFP'].str.zfill(3)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/4222304594.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pivoted_filtered['COUNTYFP'] = pivoted_filtered['County'].str.upper().map(fips_dict).fillna(pivoted_filtered['County'])

In [478]:
pivoted_filtered['COUNTYFP'].unique()

array(['001', '003', '005', '007', '009', '011', '013', '015', '017',
       '019', '021', '113', '031', '183', '163', '095', '201', '023',
       '025', '027', '029', '033', '035', '041', '037', '039', '043',
       '045', '047', '049', '051', '053', '055', '057', '059', '061',
       '063', '065', '067', '069', '071', '073', '075', '077', '079',
       '081', '083', '087', '085', '089', '091', '093', '097', '101',
       '103', '105', '107', '099', '115', '117', '119', '121', '123',
       '125', '127', '129', '131', '133', '135', '137', '139', '109',
       '111', '141', '143', '145', '147', '149', '151', '153', '155',
       '157', '159', '161', '165', '167', '169', '171', '173', '175',
       '177', '179', '181', '185', '187', '189', '191', '193', '195',
       '197', '199', '203'], dtype=object)

In [479]:
pivoted_filtered["Precinct"] = pivoted_filtered["UNIQUE_ID"].apply(lambda x:x.split("-:-")[1])

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_36625/1913933772.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pivoted_filtered["Precinct"] = pivoted_filtered["UNIQUE_ID"].apply(lambda x:x.split("-:-")[1])

In [480]:
[i for i in race_cols if i not in list(pivoted_filtered.columns)]

[]

In [481]:
pivoted_filtered = pivoted_filtered[["UNIQUE_ID","COUNTYFP","JurisName","Precinct","County"]+race_cols]

In [482]:
if not os.path.exists("./il_2024_gen_prec_csv"):
    os.mkdir("./il_2024_gen_prec_csv")

In [483]:
pivoted_filtered.to_csv("./il_2024_gen_prec_csv/il_2024_gen_prec_csv.csv", index = False)

In [408]:
pivoted_filtered.columns

Index(['UNIQUE_ID', 'COUNTYFP', 'JurisName', 'Precinct', 'County', 'G24BI1NO',
       'G24BI1YES', 'G24BI2NO', 'G24BI2YES', 'G24BI3NO',
       ...
       'GSU43RMON', 'GSU46DKOE', 'GSU46ROWE', 'GSU49DCAP', 'GSU49RDEA',
       'GSU52DFAR', 'GSU52RBRO', 'GSU53RBAL', 'GSU55RPLU', 'GSU58RBRY'],
      dtype='object', name='cand_col', length=282)