In [47]:
import geopandas as gp
import pandas as pd
import os
import numpy as np
import re
from collections import Counter

# Alabama 2024 General Election Results

In [48]:
path = './raw-from-source/2024-General Precinct Level Results/'

files = [i for i in os.listdir(path) if i != ".DS_Store"]

In [49]:
county_list = []
for file in files: 
    print(file)
    temp = pd.read_excel(path + file)
    county_name = file.split("-")[-1][0:-4]
    if county_name == "StClair":
        county_name = "St. Clair"
    temp["Party"] = temp["Party"].str.strip()
    temp["Party"] = temp["Party"].fillna("")
    temp["pivot_col"] = temp["Contest Title"].str.strip()+"-:-"+temp["Candidate"].str.strip()
    temp["pivot_col"] = np.where(temp["Party"]=="",temp["pivot_col"],temp["pivot_col"]+"-:-"+temp["Party"].str.strip())

    temp.drop(["Contest Title", "Party", "Candidate"], axis = 1, inplace = True)

    
    rename_dict = {i:i+"-:-"+county_name for i in temp.columns if i != "pivot_col"}
    temp.rename(columns = rename_dict, inplace = True)
    temp_transpose = temp.set_index("pivot_col").T
    temp_transpose.reset_index(inplace = True, drop = False)
    ser = temp_transpose["index"].value_counts()
    if ser[ser>1].shape[0]>0:
        raise ValueError
    temp_transpose["County"] = county_name
    #print(temp_transpose.head(10))
    #break
#     print(temp_transpose.head())
    county_list.append(temp_transpose)

2024-General-Marion.xls
2024-General-Greene.xls
2024-General-Jackson.xls
2024-General-Marengo.xls
2024-General-Escambia.xls
2024-General-Lauderdale.xls
2024-General-Calhoun.xls
2024-General-Monroe.xls
2024-General-Walker.xls
2024-General-DeKalb.xls
2024-General-Bibb.xls
2024-General-Cullman.xls
2024-General-Macon.xls
2024-General-Wilcox.xls
2024-General-Chambers.xls
2024-General-Randolph.xls
2024-General-Blount.xls
2024-General-Dale.xls
2024-General-Perry.xls
2024-General-Covington.xls
2024-General-Hale.xls
2024-General-Lowndes.xls
2024-General-Butler.xls
2024-General-Tallapoosa.xls
2024-General-Coosa.xls
2024-General-Pickens.xls
2024-General-Cherokee.xls
2024-General-Lee.xls
2024-General-Coffee.xls
2024-General-Cleburne.xls
2024-General-Crenshaw.xls
2024-General-Houston.xls
2024-General-Autauga.xls
2024-General-Sumter.xls
2024-General-Washington.xls
2024-General-Limestone.xls
2024-General-Clarke.xls
2024-General-Dallas.xls
2024-General-Lamar.xls
2024-General-Jefferson.xls
2024-General-Russell.xls
2024-General-Baldwin.xls
2024-General-Barbour.xls
2024-General-Tuscaloosa.xls
2024-General-Lawrence.xls
2024-General-Fayette.xls
2024-General-Morgan.xls
2024-General-StClair.xls
2024-General-Geneva.xls
2024-General-Montgomery.xls
2024-General-Mobile.xls
2024-General-Choctaw.xls
2024-General-Clay.xls
2024-General-Shelby.xls
2024-General-Etowah.xls
2024-General-Conecuh.xls
2024-General-Elmore.xls
2024-General-Madison.xls
2024-General-Franklin.xls
2024-General-Marshall.xls
2024-General-Bullock.xls
2024-General-Talladega.xls
2024-General-Winston.xls
2024-General-Chilton.xls
2024-General-Pike.xls
2024-General-Henry.xls
2024-General-Colbert.xls

In [50]:
comb = pd.concat(county_list)

In [51]:
comb = comb.fillna(0)

In [52]:
comb.head()

pivot_col,index,REGISTERED VOTERS - TOTAL-:-Registered Voters - Total,BALLOTS CAST - TOTAL-:-Ballots Cast - Total,BALLOTS CAST - BLANK-:-Ballots Cast - Blank,STRAIGHT PARTY-:-Alabama Democratic Party-:-DEM,STRAIGHT PARTY-:-Alabama Republican Party-:-REP,STRAIGHT PARTY-:-Over Votes,STRAIGHT PARTY-:-Under Votes,PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Kamala D. Harris-:-DEM,PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Donald J. Trump-:-REP,...,"SUPERINTENDENT, COLBERT COUNTY BOARD OF EDUCATION-:-Over Votes","SUPERINTENDENT, COLBERT COUNTY BOARD OF EDUCATION-:-Under Votes","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 2-:-David Yarber-:-REP","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Write-In-:-NON","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Over Votes","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Under Votes","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Thomas L Burgess-:-DEM","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Write-In-:-NON","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Over Votes","MEMBER, COLBERT COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Under Votes"
0,ABSENTEE-:-Marion,0.0,451.0,1.0,36.0,324.0,0.0,91.0,55.0,389.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BACCUS UNION HALL-:-Marion,359.0,256.0,0.0,3.0,182.0,0.0,71.0,9.0,247.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BEAR CREEK CITY HALL-:-Marion,2072.0,1162.0,0.0,60.0,739.0,0.0,363.0,98.0,1051.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BRILLIANT COMM CTR-:-Marion,1185.0,694.0,0.0,34.0,490.0,0.0,170.0,46.0,640.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,BYRD VOTING CTR-:-Marion,1359.0,836.0,0.0,57.0,507.0,0.0,272.0,80.0,744.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
comb_list = [i for i in comb.columns if ("REPRESENTATIVE" in i or "PRESIDENT" in i or "DELEGATES" in i or "STATEWIDE" in i or "CHIEF JUSTICE" in i or "APPEALS JUDGE" in i or "ASSOCIATE JUSTICE" in i) and ("Under Votes" not in i and "Over Votes" not in i)]

In [54]:
[i for i in comb.columns if i not in comb_list and "Over Votes" not in i and "Under Votes" not in i]

['index',
 'REGISTERED VOTERS - TOTAL-:-Registered Voters - Total',
 'BALLOTS CAST - TOTAL-:-Ballots Cast - Total',
 'BALLOTS CAST - BLANK-:-Ballots Cast - Blank',
 'STRAIGHT PARTY-:-Alabama Democratic Party-:-DEM',
 'STRAIGHT PARTY-:-Alabama Republican Party-:-REP',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 7-:-Allen Long-:-REP',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 7-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 25TH JUDICIAL CIRCUIT, PLACE 2-:-Talmage Lee Carter-:-REP',
 'CIRCUIT COURT JUDGE, 25TH JUDICIAL CIRCUIT, PLACE 2-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, MARION COUNTY-:-Mark Hammitte-:-REP',
 'DISTRICT COURT JUDGE, MARION COUNTY-:-Write-In-:-NON',
 'CIRCUIT CLERK, MARION COUNTY-:-Denise Ledbetter Mixon-:-REP',
 'CIRCUIT CLERK, MARION COUNTY-:-Write-In-:-NON',
 'MARION COUNTY JUDGE OF PROBATE-:-Paige Nichols Vick-:-REP',
 'MARION COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'SUPERINTENDENT, MARION COUNTY BOARD OF EDUCATION-:-Patrick Sutton-:-REP',
 'SUPERINTENDENT, MARION COUNTY BOARD OF EDUCATION-:-Write-In-:-NON',
 'MEMBER, MARION COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Alex Smith-:-REP',
 'MEMBER, MARION COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Write-In-:-NON',
 'MEMBER, MARION COUNTY BOARD OF EDUCATION, DISTRICT NO. 5-:-Tim Bryant-:-REP',
 'MEMBER, MARION COUNTY BOARD OF EDUCATION, DISTRICT NO. 5-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 1A-:-Clint Green-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 1A-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 2-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 3-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 4-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 5-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 6-:-Shannon Holland-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 6-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 7-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 8-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 9 NORTH-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 10-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 11-:-Wade Berryhill-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 11-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 12-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 13-:-Tim Ganey-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 13-:-Jonathan Wiginton-:-IND',
 'MARION COUNTY CONSTABLE, PRECINCT 13-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 14-:-Russell Melton-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 14-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 15-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 16-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 17-:-Walter Drewry Jr.-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 17-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 18-:-Jeremy McGuire-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 18-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 19-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 1B-:-Walter Drewry III-:-REP',
 'MARION COUNTY CONSTABLE, PRECINCT 1B-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 1C-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 1D-:-Write-In-:-NON',
 'MARION COUNTY CONSTABLE, PRECINCT 9 SOUTH-:-Write-In-:-NON',
 'County',
 'CIRCUIT COURT JUDGE, 17TH JUDICIAL CIRCUIT, PLACE 1-:-Gregory S. Griggers-:-DEM',
 'CIRCUIT COURT JUDGE, 17TH JUDICIAL CIRCUIT, PLACE 1-:-Write-In-:-NON',
 'CIRCUIT CLERK, GREENE COUNTY-:-Veronica Morton-Jones-:-DEM',
 'CIRCUIT CLERK, GREENE COUNTY-:-Write-In-:-NON',
 'GREENE COUNTY JUDGE OF PROBATE-:-Rolonda M. Wedgeworth-:-DEM',
 'GREENE COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'GREENE COUNTY CONSTABLE, DISTRICT 1-:-Deangelo M. Hall-:-IND',
 'GREENE COUNTY CONSTABLE, DISTRICT 1-:-Write-In-:-NON',
 'GREENE COUNTY CONSTABLE, DISTRICT 2-:-Write-In-:-NON',
 'GREENE COUNTY CONSTABLE, DISTRICT 3-:-Write-In-:-NON',
 'GREENE COUNTY CONSTABLE, DISTRICT 4-:-Write-In-:-NON',
 'GREENE COUNTY CONSTABLE, DISTRICT 5-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 38TH JUDICIAL CIRCUIT, PLACE 1-:-John Graham-:-DEM',
 'CIRCUIT COURT JUDGE, 38TH JUDICIAL CIRCUIT, PLACE 1-:-Write-In-:-NON',
 'CIRCUIT CLERK, JACKSON COUNTY-:-Bart Buchanan-:-REP',
 'CIRCUIT CLERK, JACKSON COUNTY-:-Write-In-:-NON',
 'JACKSON COUNTY JUDGE OF PROBATE-:-Victor Manning-:-REP',
 'JACKSON COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, JACKSON COUNTY COMMISSION, DISTRICT NO. 3-:-A.J. Buckner-:-REP',
 'MEMBER, JACKSON COUNTY COMMISSION, DISTRICT NO. 3-:-Write-In-:-NON',
 'MEMBER, JACKSON COUNTY COMMISSION, DISTRICT NO. 4-:-Kevin McBride-:-REP',
 'MEMBER, JACKSON COUNTY COMMISSION, DISTRICT NO. 4-:-Mike Sisk-:-IND',
 'MEMBER, JACKSON COUNTY COMMISSION, DISTRICT NO. 4-:-Write-In-:-NON',
 'SUPERINTENDENT, JACKSON COUNTY BOARD OF EDUCATION-:-Jason Davidson-:-REP',
 'SUPERINTENDENT, JACKSON COUNTY BOARD OF EDUCATION-:-Write-In-:-NON',
 'MEMBER, JACKSON COUNTY BOARD OF EDUCATION, DIST NO. 1-:-Michael Matthews-:-IND',
 'MEMBER, JACKSON COUNTY BOARD OF EDUCATION, DIST NO. 1-:-Write-In-:-NON',
 'LOCAL AMENDMENT 1-:-Yes-:-NON',
 'LOCAL AMENDMENT 1-:-No-:-NON',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 5-:-Tonya Smith Chestnut-:-DEM',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 5-:-David W. Perry-:-REP',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 5-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, MARENGO COUNTY, PLACE NO. 1-:-Vince Deas-:-DEM',
 'DISTRICT COURT JUDGE, MARENGO COUNTY, PLACE NO. 1-:-Write-In-:-NON',
 'CIRCUIT CLERK, MARENGO COUNTY-:-Darren Glass-:-DEM',
 'CIRCUIT CLERK, MARENGO COUNTY-:-Write-In-:-NON',
 'MARENGO COUNTY JUDGE OF PROBATE-:-Laurie Hall-:-DEM',
 'MARENGO COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, MARENGO COUNTY COMMISSION, DISTRICT NO. 2-:-Jason Windham-:-DEM',
 'MEMBER, MARENGO COUNTY COMMISSION, DISTRICT NO. 2-:-Write-In-:-NON',
 'MEMBER, MARENGO COUNTY COMMISSION, DISTRICT NO. 4-:-Calvin Martin-:-DEM',
 'MEMBER, MARENGO COUNTY COMMISSION, DISTRICT NO. 4-:-Write-In-:-NON',
 'MEMBER, MARENGO COUNTY BOARD OF EDUCATION, DIST NO. 1-:-Freddie Charleston-:-DEM',
 'MEMBER, MARENGO COUNTY BOARD OF EDUCATION, DIST NO. 1-:-Write-In-:-NON',
 'MEMBER, MARENGO COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Mark Bedsole-:-DEM',
 'MEMBER, MARENGO COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Write-In-:-NON',
 '3 MILL SCHOOL TAX-:-For-:-NON',
 '3 MILL SCHOOL TAX-:-Against-:-NON',
 '5 MILL SCHOOL TAX-:-For-:-NON',
 '5 MILL SCHOOL TAX-:-Against-:-NON',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 1-:-Jackie Zeigler-:-REP',
 'STATE BOARD OF EDUCATION MEMBER DISTRICT 1-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 21ST JUDICIAL CIRCUIT, PLACE 1-:-Jeff White-:-REP',
 'CIRCUIT COURT JUDGE, 21ST JUDICIAL CIRCUIT, PLACE 1-:-Write-In-:-NON',
 'CIRCUIT CLERK, ESCAMBIA COUNTY-:-John R. Fountain-:-REP',
 'CIRCUIT CLERK, ESCAMBIA COUNTY-:-Write-In-:-NON',
 'ESCAMBIA COUNTY JUDGE OF PROBATE-:-Doug Agerton-:-REP',
 'ESCAMBIA COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, ESCAMBIA COUNTY COMMISSION, DISTRICT NO. 2-:-Raymond Wiggins-:-REP',
 'MEMBER, ESCAMBIA COUNTY COMMISSION, DISTRICT NO. 2-:-Write-In-:-NON',
 'MEMBER, ESCAMBIA COUNTY COMMISSION, DISTRICT NO. 4-:-Brandon Smith-:-REP',
 'MEMBER, ESCAMBIA COUNTY COMMISSION, DISTRICT NO. 4-:-Write-In-:-NON',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Danny Benjamin-:-DEM',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Greg Dawkins-:-REP',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 2-:-Write-In-:-NON',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Jerry Wilson-:-REP',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Write-In-:-NON',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 7-:-Coleman Wallace-:-REP',
 'MEMBER, ESCAMBIA COUNTY BOARD OF EDUCATION, DIST NO. 7-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 11TH JUDICIAL CIRCUIT, PLACE 4-:-Carole Coil Medley-:-REP',
 'CIRCUIT COURT JUDGE, 11TH JUDICIAL CIRCUIT, PLACE 4-:-Write-In-:-NON',
 'CIRCUIT CLERK, LAUDERDALE COUNTY-:-Missy Homan-:-REP',
 'CIRCUIT CLERK, LAUDERDALE COUNTY-:-Write-In-:-NON',
 'LAUDERDALE COUNTY JUDGE OF PROBATE-:-Will Motlow-:-REP',
 'LAUDERDALE COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'CHAIRMAN, LAUDERDALE COUNTY COMMISSION-:-Danny Pettus-:-REP',
 'CHAIRMAN, LAUDERDALE COUNTY COMMISSION-:-Write-In-:-NON',
 'MEMBER, LAUDERDALE COUNTY COMMISSION, DISTRICT NO. 1-:-William "Roger" Garner-:-REP',
 'MEMBER, LAUDERDALE COUNTY COMMISSION, DISTRICT NO. 1-:-Write-In-:-NON',
 'MEMBER, LAUDERDALE COUNTY COMMISSION, DISTRICT NO. 2-:-Todd Nix-:-REP',
 'MEMBER, LAUDERDALE COUNTY COMMISSION, DISTRICT NO. 2-:-Write-In-:-NON',
 'SUPERINTENDENT, LAUDERDALE COUNTY BOARD OF EDUCATION-:-Jerry Hill-:-REP',
 'SUPERINTENDENT, LAUDERDALE COUNTY BOARD OF EDUCATION-:-Write-In-:-NON',
 'MEMBER, LAUDERDALE COUNTY BOARD OF EDUCATION, DIST NO. 3-:-Randy Burns-:-REP',
 'MEMBER, LAUDERDALE COUNTY BOARD OF EDUCATION, DIST NO. 3-:-Write-In-:-NON',
 'MEMBER, LAUDERDALE COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Larry J. Hill-:-REP',
 'MEMBER, LAUDERDALE COUNTY BOARD OF EDUCATION, DIST NO. 4-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 7TH JUDICIAL CIRCUIT, PLACE 1-:-Dustin Merritt-:-REP',
 'CIRCUIT COURT JUDGE, 7TH JUDICIAL CIRCUIT, PLACE 1-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 7TH JUDICIAL CIRCUIT, PLACE 2-:-Timothy C. Burgess-:-REP',
 'CIRCUIT COURT JUDGE, 7TH JUDICIAL CIRCUIT, PLACE 2-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, CALHOUN COUNTY, PLACE NO. 1-:-Tom Wright-:-REP',
 'DISTRICT COURT JUDGE, CALHOUN COUNTY, PLACE NO. 1-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, CALHOUN COUNTY, PLACE NO. 2-:-Randy J. Moeller-:-REP',
 'DISTRICT COURT JUDGE, CALHOUN COUNTY, PLACE NO. 2-:-Write-In-:-NON',
 'CIRCUIT CLERK, CALHOUN COUNTY-:-Kim McCarson-:-REP',
 'CIRCUIT CLERK, CALHOUN COUNTY-:-Write-In-:-NON',
 'CALHOUN COUNTY JUDGE OF PROBATE-:-Shirley Millwood-:-REP',
 'CALHOUN COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Manuela Burton-:-DEM',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Robin R. Caler-:-DEM',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Nick Ogle-:-DEM',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Mike Almaroad-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Tobi Burt-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Allen E. George-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Joe Lathers-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Alan Mange-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Bobby R. Tittle-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Michael Webb-:-REP',
 'MEMBER, CALHOUN COUNTY BOARD OF EDUCATION, PLACE NO. 1-7-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 35TH JUDICIAL CIRCUIT, PLACE 1-:-Jack Booker Weaver-:-DEM',
 'CIRCUIT COURT JUDGE, 35TH JUDICIAL CIRCUIT, PLACE 1-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, MONROE COUNTY, PLACE NO. 1-:-Donna Lynn Silcox-:-DEM',
 'DISTRICT COURT JUDGE, MONROE COUNTY, PLACE NO. 1-:-Write-In-:-NON',
 'CIRCUIT CLERK, MONROE COUNTY-:-Wesley D. Hines-:-DEM',
 'CIRCUIT CLERK, MONROE COUNTY-:-Jade Colquett-:-REP',
 'CIRCUIT CLERK, MONROE COUNTY-:-Write-In-:-NON',
 'MONROE COUNTY JUDGE OF PROBATE-:-Sonya Stinson-:-DEM',
 'MONROE COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, MONROE COUNTY COMMISSION, DISTRICT NO. 1-:-Larry Wesley Weaver-:-REP',
 'MEMBER, MONROE COUNTY COMMISSION, DISTRICT NO. 1-:-Write-In-:-NON',
 'MEMBER, MONROE COUNTY COMMISSION, DISTRICT NO. 4-:-Corey Morrow-:-DEM',
 'MEMBER, MONROE COUNTY COMMISSION, DISTRICT NO. 4-:-Write-In-:-NON',
 'MEMBER, MONROE COUNTY BOARD OF EDUCATION, DISTRICT NO. 3-:-Brian Harrison-:-REP',
 'MEMBER, MONROE COUNTY BOARD OF EDUCATION, DISTRICT NO. 3-:-Write-In-:-NON',
 'MEMBER, MONROE COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Kenneth V. Smith-:-DEM',
 'MEMBER, MONROE COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Tammie Rainey-:-REP',
 'MEMBER, MONROE COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Derek Pugh-:-IND',
 'MEMBER, MONROE COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 1-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 2-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 3-:-Anthony Thomas-:-DEM',
 'MONROE COUNTY CONSTABLE, BEAT 3-:-Woodie Oneal Reed-:-REP',
 'MONROE COUNTY CONSTABLE, BEAT 3-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 4-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 5-:-Wallace Stanton-:-DEM',
 'MONROE COUNTY CONSTABLE, BEAT 5-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 6-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 7-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 8-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 9-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 10-:-Darryl Ikner-:-DEM',
 'MONROE COUNTY CONSTABLE, BEAT 10-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 11-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 12-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 13-:-Write-In-:-NON',
 'MONROE COUNTY CONSTABLE, BEAT 14-:-Joey Castillow-:-REP',
 'MONROE COUNTY CONSTABLE, BEAT 14-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 14TH JUDICIAL CIRCUIT, PLACE 2-:-Doug Farris-:-REP',
 'CIRCUIT COURT JUDGE, 14TH JUDICIAL CIRCUIT, PLACE 2-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 14TH JUDICIAL CIRCUIT, PLACE 3-:-Gregory M. Williams-:-REP',
 'CIRCUIT COURT JUDGE, 14TH JUDICIAL CIRCUIT, PLACE 3-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, WALKER COUNTY, PLACE NO. 2-:-Allison M. Jones-:-REP',
 'DISTRICT COURT JUDGE, WALKER COUNTY, PLACE NO. 2-:-Write-In-:-NON',
 'CIRCUIT CLERK, WALKER COUNTY-:-Susan "Suzie" Odom-:-REP',
 'CIRCUIT CLERK, WALKER COUNTY-:-Write-In-:-NON',
 'CHAIRMAN, WALKER COUNTY COMMISSION-:-Steve Miller-:-REP',
 'CHAIRMAN, WALKER COUNTY COMMISSION-:-Write-In-:-NON',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 1-:-John Dunagan-:-REP',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 1-:-Write-In-:-NON',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 2-:-Jeff Burrough-:-REP',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 2-:-Write-In-:-NON',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 3-:-James "Jim" Borden-:-REP',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 3-:-Write-In-:-NON',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 4-:-Steven Aderholt-:-REP',
 'MEMBER, WALKER COUNTY COMMISSION, DISTRICT NO. 4-:-Write-In-:-NON',
 'WALKER COUNTY JUDGE OF PROBATE-:-A. Lee Tucker-:-REP',
 'WALKER COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, WALKER COUNTY BOARD OF EDUCATION, DISTRICT NO. 1-:-Trent Kennedy-:-REP',
 'MEMBER, WALKER COUNTY BOARD OF EDUCATION, DISTRICT NO. 1-:-Write-In-:-NON',
 'MEMBER, WALKER COUNTY BOARD OF EDUCATION, DISTRICT NO. 3-:-Vonda Pate Beaty-:-REP',
 'MEMBER, WALKER COUNTY BOARD OF EDUCATION, DISTRICT NO. 3-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 1-:-Terry D. Stripling-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 1-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 2-:-Joe Thomas-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 2-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 3-:-Tommy A. Cleghorn-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 3-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 4-:-Don Frazier-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 4-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 5-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 6-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 7-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 8-:-Michael Blankenship-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 8-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 9-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 10-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 11-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 12-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 13-:-Josh Voss-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 13-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 14-:-Alex Daniel-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 14-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 15-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 16-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 17-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 18-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 19-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 20-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 21-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 22-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 23-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 24-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 25-:-Jerry S. Aultman-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 25-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 26-:-Allen Hinds-:-DEM',
 'WALKER COUNTY CONSTABLE, BEAT 26-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 27-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 28-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 29-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 30-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 31-:-Raymond Pugh-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 31-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 32-:-Allen Estell-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 32-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 33-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 34-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 35-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 36-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 37-:-Terry J. Pickett-:-DEM',
 'WALKER COUNTY CONSTABLE, BEAT 37-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 38-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 39-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 40-:-Larry Myers-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 40-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 41-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 42-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 43-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 44-:-Larry C. Odom-:-REP',
 'WALKER COUNTY CONSTABLE, BEAT 44-:-Write-In-:-NON',
 'WALKER COUNTY CONSTABLE, BEAT 45-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 9TH JUDICIAL CIRCUIT, PLACE 1-:-Shaunathan Bell-:-REP',
 'CIRCUIT COURT JUDGE, 9TH JUDICIAL CIRCUIT, PLACE 1-:-Write-In-:-NON',
 'CIRCUIT COURT JUDGE, 9TH JUDICIAL CIRCUIT, PLACE 2-:-Andrew Hairston-:-REP',
 'CIRCUIT COURT JUDGE, 9TH JUDICIAL CIRCUIT, PLACE 2-:-Write-In-:-NON',
 'DISTRICT COURT JUDGE, DEKALB COUNTY, PLACE NO. 2-:-Jeff McCurdy-:-REP',
 'DISTRICT COURT JUDGE, DEKALB COUNTY, PLACE NO. 2-:-Write-In-:-NON',
 'CIRCUIT CLERK, DEKALB COUNTY-:-Todd Greeson-:-REP',
 'CIRCUIT CLERK, DEKALB COUNTY-:-Write-In-:-NON',
 'DEKALB COUNTY JUDGE OF PROBATE-:-Ronnie Osborn-:-REP',
 'DEKALB COUNTY JUDGE OF PROBATE-:-Write-In-:-NON',
 'MEMBER, DEKALB COUNTY COMMISSION, DISTRICT NO. 1-:-Shane Wootten-:-REP',
 'MEMBER, DEKALB COUNTY COMMISSION, DISTRICT NO. 1-:-Write-In-:-NON',
 'MEMBER, DEKALB COUNTY COMMISSION, DISTRICT NO. 2-:-Brent Rhodes-:-REP',
 'MEMBER, DEKALB COUNTY COMMISSION, DISTRICT NO. 2-:-Write-In-:-NON',
 'SUPERINTENDENT, DEKALB COUNTY BOARD OF EDUCATION-:-Wayne Lyles-:-REP',
 'SUPERINTENDENT, DEKALB COUNTY BOARD OF EDUCATION-:-Write-In-:-NON',
 'MEMBER, DEKALB COUNTY BOARD OF EDUCATION, DISTRICT NO. 3-:-Carol Hiett-:-REP',
 'MEMBER, DEKALB COUNTY BOARD OF EDUCATION, DISTRICT NO. 3-:-Write-In-:-NON',
 'MEMBER, DEKALB COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Monty Darwin-:-REP',
 'MEMBER, DEKALB COUNTY BOARD OF EDUCATION, DISTRICT NO. 4-:-Write-In-:-NON',
 'DEKALB COUNTY CONSTABLE, DISTRICT NO. 1-:-Write-In-:-NON',
 'DEKALB COUNTY CONSTABLE, DISTRICT NO. 2-:-Write-In-:-NON',
 'DEKALB COUNTY CONSTABLE, DISTRICT NO. 3-:-Michael D. Twilley-:-REP',
 'DEKALB COUNTY CONSTABLE, DISTRICT NO. 3-:-Write-In-:-NON',
 'DEKALB COUNTY CONSTABLE, DISTRICT NO. 4-:-Mark Huber-:-REP',
 'DEKALB COUNTY CONSTABLE, DISTRICT NO. 4-:-Write-In-:-NON',

In [55]:
comb_list.sort()

In [56]:
comb_list

['ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Chris McCool-:-REP',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Write-In-:-NON',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Tommy Bryan-:-REP',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Write-In-:-NON',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Will Sellers-:-REP',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Write-In-:-NON',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Jay Mitchell-:-REP',
 'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Write-In-:-NON',
 'CHIEF JUSTICE OF THE SUPREME COURT-:-Greg Griffin-:-DEM',
 'CHIEF JUSTICE OF THE SUPREME COURT-:-Sarah Stewart-:-REP',
 'CHIEF JUSTICE OF THE SUPREME COURT-:-Write-In-:-NON',
 'COURT OF CIVIL APPEALS JUDGE, PLACE 1-:-Christy Edwards-:-REP',
 'COURT OF CIVIL APPEALS JUDGE, PLACE 1-:-Write-In-:-NON',
 'COURT OF CIVIL APPEALS JUDGE, PLACE 2-:-Chad Hanson-:-REP',
 'COURT OF CIVIL APPEALS JUDGE, PLACE 2-:-Write-In-:-NON',
 'COURT OF CIVIL APPEALS JUDGE, PLACE 3-:-Terry A. Moore-:-REP',
 'COURT OF CIVIL APPEALS JUDGE, PLACE 3-:-Write-In-:-NON',
 'COURT OF CRIMINAL APPEALS JUDGE, PLACE 1-:-Richard Minor-:-REP',
 'COURT OF CRIMINAL APPEALS JUDGE, PLACE 1-:-Write-In-:-NON',
 'COURT OF CRIMINAL APPEALS JUDGE, PLACE 2-:-Rich Anderson-:-REP',
 'COURT OF CRIMINAL APPEALS JUDGE, PLACE 2-:-Write-In-:-NON',
 'COURT OF CRIMINAL APPEALS JUDGE, PLACE 3-:-Bill Cole-:-REP',
 'COURT OF CRIMINAL APPEALS JUDGE, PLACE 3-:-Write-In-:-NON',
 'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Chase Oliver-:-IND',
 'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Donald J. Trump-:-REP',
 'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Jill Stein-:-IND',
 'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Kamala D. Harris-:-DEM',
 'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Robert F. Kennedy Jr.-:-IND',
 'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Write-In-:-NON',
 'PRESIDENT, PUBLIC SERVICE COMMISSION-:-Twinkle Andress Cavanaugh-:-REP',
 'PRESIDENT, PUBLIC SERVICE COMMISSION-:-Write-In-:-NON',
 'PROPOSED STATEWIDE AMENDMENT NUMBER ONE (1)-:-No-:-NON',
 'PROPOSED STATEWIDE AMENDMENT NUMBER ONE (1)-:-Yes-:-NON',
 'UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Barry Moore-:-REP',
 'UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Tom Holmes-:-DEM',
 'UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
 'UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Caroleene Dobson-:-REP',
 'UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Shomari Figures-:-DEM',
 'UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
 'UNITED STATES REPRESENTATIVE, 3RD CONGRESSIONAL DISTRICT-:-Mike Rogers-:-REP',
 'UNITED STATES REPRESENTATIVE, 3RD CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
 'UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Robert B. Aderholt-:-REP',
 'UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
 'UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Dale Strong-:-REP',
 'UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
 'UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Elizabeth Anderson-:-DEM',
 'UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Gary Palmer-:-REP',
 'UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
 'UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Robin Litaker-:-REP',
 'UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Terri A. Sewell-:-DEM',
 'UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON']

In [57]:
remaining = [i for i in list(comb.columns) if i not in comb_list]

In [58]:
deleg_dict = {i:"PRESIDENT OF THE UNITED STATES-:-"+i.split("-:-")[1]+"-:-"+i.split("-:-")[2] for i in comb_list if "DEMOCRATIC DELEGATES" in i}

In [59]:
comb = comb[["index"]+comb_list]

In [60]:
comb.rename(columns = deleg_dict, inplace = True)

In [61]:
comb2 = comb.groupby(level = 0,axis = 1).sum()

In [62]:
comb2.columns

Index(['ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Chris McCool-:-REP',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Write-In-:-NON',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Tommy Bryan-:-REP',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Write-In-:-NON',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Will Sellers-:-REP',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Write-In-:-NON',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Jay Mitchell-:-REP',
       'ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Write-In-:-NON',
       'CHIEF JUSTICE OF THE SUPREME COURT-:-Greg Griffin-:-DEM',
       'CHIEF JUSTICE OF THE SUPREME COURT-:-Sarah Stewart-:-REP',
       'CHIEF JUSTICE OF THE SUPREME COURT-:-Write-In-:-NON',
       'COURT OF CIVIL APPEALS JUDGE, PLACE 1-:-Christy Edwards-:-REP',
       'COURT OF CIVIL APPEALS JUDGE, PLACE 1-:-Write-In-:-NON',
       'COURT OF CIVIL APPEALS JUDGE, PLACE 2-:-Chad Hanson-:-REP',
       'COURT OF CIVIL APPEALS JUDGE, PLACE 2-:-Write-In-:-NON',
       'COURT OF CIVIL APPEALS JUDGE, PLACE 3-:-Terry A. Moore-:-REP',
       'COURT OF CIVIL APPEALS JUDGE, PLACE 3-:-Write-In-:-NON',
       'COURT OF CRIMINAL APPEALS JUDGE, PLACE 1-:-Richard Minor-:-REP',
       'COURT OF CRIMINAL APPEALS JUDGE, PLACE 1-:-Write-In-:-NON',
       'COURT OF CRIMINAL APPEALS JUDGE, PLACE 2-:-Rich Anderson-:-REP',
       'COURT OF CRIMINAL APPEALS JUDGE, PLACE 2-:-Write-In-:-NON',
       'COURT OF CRIMINAL APPEALS JUDGE, PLACE 3-:-Bill Cole-:-REP',
       'COURT OF CRIMINAL APPEALS JUDGE, PLACE 3-:-Write-In-:-NON',
       'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Chase Oliver-:-IND',
       'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Donald J. Trump-:-REP',
       'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Jill Stein-:-IND',
       'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Kamala D. Harris-:-DEM',
       'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Robert F. Kennedy Jr.-:-IND',
       'PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Write-In-:-NON',
       'PRESIDENT, PUBLIC SERVICE COMMISSION-:-Twinkle Andress Cavanaugh-:-REP',
       'PRESIDENT, PUBLIC SERVICE COMMISSION-:-Write-In-:-NON',
       'PROPOSED STATEWIDE AMENDMENT NUMBER ONE (1)-:-No-:-NON',
       'PROPOSED STATEWIDE AMENDMENT NUMBER ONE (1)-:-Yes-:-NON',
       'UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Barry Moore-:-REP',
       'UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Tom Holmes-:-DEM',
       'UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Caroleene Dobson-:-REP',
       'UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Shomari Figures-:-DEM',
       'UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'UNITED STATES REPRESENTATIVE, 3RD CONGRESSIONAL DISTRICT-:-Mike Rogers-:-REP',
       'UNITED STATES REPRESENTATIVE, 3RD CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Robert B. Aderholt-:-REP',
       'UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Dale Strong-:-REP',
       'UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Elizabeth Anderson-:-DEM',
       'UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Gary Palmer-:-REP',
       'UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Robin Litaker-:-REP',
       'UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Terri A. Sewell-:-DEM',
       'UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON',
       'index'],
      dtype='object', name='pivot_col')

In [63]:
def get_race(race_string):
    race_string = race_string.title()
    race_string = race_string.replace("(Vote For 1)","")
    if "U.S. House" in race_string or 'Us House' in race_string or "United States Representative" in race_string:
        return "CON"
    elif "Public Service" in race_string:
        if "1" in race_string:
            return "PS1"
        elif "2" in race_string:
            return "PS2"
        else:
            return "PSC"
    elif "United States Senator" in race_string:
        return "USS"
    elif "State House" in race_string or "State Representative" in race_string:
        return "SL"
    elif "State Senator" in race_string:
        return "SU"
    elif "President" in race_string:
        return "PRE"
    elif "US Senate" in race_string or "Us Senate" in race_string:
        return "USS"

    elif "Attorney General" in race_string:
        return "ATG"
    elif "Auditor General" in race_string or "State Auditor" in race_string:
        return "AUD"
    elif "Treasurer" in race_string:
        return "TRE"
    elif "Superintendent" in race_string:
        return "SUP"
    elif "Secretary Of State" in race_string:
        return "SOS"
    elif "Lieutenant Governor" in race_string:
        return "LTG"
    elif "Governor" in race_string:
        return "GOV"
    elif "Commissioner Of Labor" in race_string:
        return "LAB"
    elif "Commissioner Of Agriculture" in race_string:
        return "AGR"
    elif "Commissioner Of Insurance" in race_string:
        return "INS"
    elif "Associate Justice Of The Supreme Court" in race_string:
        if "1" in race_string:
            return "AJ1"
        elif "2" in race_string:
            return "AJ2"
        elif "3" in race_string:
            return "AJ3"
        elif "4" in race_string:
            return "AJ4"
    elif "Constitution" in race_string:
        return "CNS"
    elif "Chief Justice" in race_string:
        return "CFJ"
    elif "Amendment" in race_string:
        if "One " in race_string:
            return "A01"
        elif "Two " in race_string:
            return "A02"
        elif "Three " in race_string:
            return "A03"
        elif "Four " in race_string:
            return "A04"
        elif "Five " in race_string:
            return "A05"
        elif "Six " in race_string:
            return "A06"
        elif "Seven " in race_string:
            return "A07"
        elif "Eight " in race_string:
            return "A08"
        elif "Nine " in race_string:
            return "A09"
        elif "Ten " in race_string:
            return "A10"
        else:
            print("No race for:", race_string)
            raise ValueError
    elif "Referendum" in race_string:
        if "1" in race_string or "A" in race_string:
            return "RFA"
        elif "2" in race_string or "B" in race_string:
            return "RFB"
        else:
            print("No race for:", race_string)
            raise ValueError
    elif "Civil Appeals Judge" in race_string:
        if "1" in race_string:
            return "CV1"
        elif "2" in race_string:
            return "CV2"
        elif "3" in race_string:
            return "CV3"
        else:
            raise ValueError
    elif "Criminal Appeals Judge" in race_string:
        if "1" in race_string:
            return "CR1"
        elif "2" in race_string:
            return "CR2"
        elif "3" in race_string:
            return "CR3"
        else:
            raise ValueError
    else:
        print("No race for:", race_string)
        raise ValueError
        
def get_election_type(race_string):
    if "(runoff)" in race_string:
        return "R"
    else:
        return "G"
        
def get_party(race_string):
    if "REP" in race_string:
        return "R"
    elif "DEM" in race_string or "(Democrat)" in race_string:
        return "D"
    elif "LIB" in race_string or "(L)" in race_string:
        return "L"
    elif "NON" in race_string:
        return "O"
    elif "IND" in race_string:
        return "I"
    elif race_string[0:3]=="Yes":
        return "YES"
    elif race_string[0:2]=="No":
        return "NO"
    else:
        print("NO RACE", race_string)
        return ""
           
def get_name(name_string):
    if "Write-In" in name_string:
        return "WRI"
    if "AMENDMENT" not in name_string and "Referendum" not in name_string and "CONSTITUTION" not in name_string:
        #print(name_string)
        #name_string = name_string.split(" (")[0]
        name_string = name_string.replace("'","")
        likely_last = name_string.split(" ")[-1]
        proposed_last = likely_last[:3]
        if proposed_last in ['II', 'III', 'Jr', 'Jr.', 'Sr.', 'JR.', "JR", "IV","Jr-"]:
            likely_last = name_string.split(" ")[-2]
            proposed_last = likely_last[:3]
        #print(proposed_last.upper())
        return proposed_last.upper()
    else:
        return name_string.split("-:-")[1].upper()
#     name_string = name_string.split("-:-")[1]
#     name_string = name_string.replace(" (I)","")
#     name_string = name_string.replace("'","")
#     likely_last = name_string.split(" ")[-1]
#     proposed_last = likely_last[:3]
#     if proposed_last in ['II', 'III', 'Jr', 'Jr.', 'Sr.', 'JR.', "JR", "IV"]:
#         likely_last = name_string.split(" ")[-2]
#         proposed_last = likely_last[:3]
#     return proposed_last.upper()

def get_district(race_string, fill_level):
    race_string = race_string.split("-:-")[0]
    race_string = race_string.replace(" (Vote For 1)","")
    if "UNITED STATES REPRESENTATIVE" in race_string:
        break_word = "REPRESENTATIVE, "
        temp = race_string.split(break_word)[1]
        temp = re.findall('\d*', temp)[0]
    elif "STATE REPRESENTATIVE" in race_string or "STATE SENATOR" in race_string:
        break_word = "DISTRICT "
        temp = race_string.split(break_word)[1]
    else:
        raise ValueError
    
    return temp.zfill(fill_level)

def column_rename_function(name_string):
    election_type = "G"
    year = "24"
    party = get_party(name_string.split("-:-")[-1])
    race = get_race(name_string)
    district = ""
    if race in ["CON", "SU"]:
        district = get_district(name_string, 2)
        year = ""
    elif race in ["SL"]:
        district = get_district(name_string, 3)
        year = ""
    
    name = get_name(name_string)
    if "CONSTITUTION" in name_string or "STATEWIDE AMENDMENT" in name_string:

        new_col_name = election_type + year + race + district +  name
    else:
        new_col_name = election_type + year + race + district + party + name
        print(election_type)
        print(year)
        print(race)
        print(district)
        print(name)
    if len(new_col_name) > 10:
        print(name_string)
        print(new_col_name)
    return new_col_name

# Make a dictionary that points to the new column names and checks for duplicates
race_columns = [i for i in list(comb2.columns) if i != 'index']

race_updates_dict = {}
race_updates_reversed = {}
clean_dups = {}
new_names = []
for val in race_columns:
    print(val)
    new_name = column_rename_function(val)
    race_updates_dict[val] = new_name
    if new_name not in new_names:
        new_names.append(new_name)
        race_updates_reversed[new_name] = val
    else:
        print("Duplicate", new_name)
        print(race_updates_reversed[new_name])
        print(val)
        clean_dups[val] = race_updates_reversed[new_name]

ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Chris McCool-:-REP
G
24
AJ1

MCC
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Write-In-:-NON
G
24
AJ1

WRI
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Tommy Bryan-:-REP
G
24
AJ2

BRY
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Write-In-:-NON
G
24
AJ2

WRI
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Will Sellers-:-REP
G
24
AJ3

SEL
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Write-In-:-NON
G
24
AJ3

WRI
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Jay Mitchell-:-REP
G
24
AJ4

MIT
ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Write-In-:-NON
G
24
AJ4

WRI
CHIEF JUSTICE OF THE SUPREME COURT-:-Greg Griffin-:-DEM
G
24
CFJ

GRI
CHIEF JUSTICE OF THE SUPREME COURT-:-Sarah Stewart-:-REP
G
24
CFJ

STE
CHIEF JUSTICE OF THE SUPREME COURT-:-Write-In-:-NON
G
24
CFJ

WRI
COURT OF CIVIL APPEALS JUDGE, PLACE 1-:-Christy Edwards-:-REP
G
24
CV1

EDW
COURT OF CIVIL APPEALS JUDGE, PLACE 1-:-Write-In-:-NON
G
24
CV1

WRI
COURT OF CIVIL APPEALS JUDGE, PLACE 2-:-Chad Hanson-:-REP
G
24
CV2

HAN
COURT OF CIVIL APPEALS JUDGE, PLACE 2-:-Write-In-:-NON
G
24
CV2

WRI
COURT OF CIVIL APPEALS JUDGE, PLACE 3-:-Terry A. Moore-:-REP
G
24
CV3

MOO
COURT OF CIVIL APPEALS JUDGE, PLACE 3-:-Write-In-:-NON
G
24
CV3

WRI
COURT OF CRIMINAL APPEALS JUDGE, PLACE 1-:-Richard Minor-:-REP
G
24
CR1

MIN
COURT OF CRIMINAL APPEALS JUDGE, PLACE 1-:-Write-In-:-NON
G
24
CR1

WRI
COURT OF CRIMINAL APPEALS JUDGE, PLACE 2-:-Rich Anderson-:-REP
G
24
CR2

AND
COURT OF CRIMINAL APPEALS JUDGE, PLACE 2-:-Write-In-:-NON
G
24
CR2

WRI
COURT OF CRIMINAL APPEALS JUDGE, PLACE 3-:-Bill Cole-:-REP
G
24
CR3

COL
COURT OF CRIMINAL APPEALS JUDGE, PLACE 3-:-Write-In-:-NON
G
24
CR3

WRI
PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Chase Oliver-:-IND
G
24
PRE

OLI
PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Donald J. Trump-:-REP
G
24
PRE

TRU
PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Jill Stein-:-IND
G
24
PRE

STE
PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Kamala D. Harris-:-DEM
G
24
PRE

HAR
PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Robert F. Kennedy Jr.-:-IND
G
24
PRE

KEN
PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES-:-Write-In-:-NON
G
24
PRE

WRI
PRESIDENT, PUBLIC SERVICE COMMISSION-:-Twinkle Andress Cavanaugh-:-REP
G
24
PSC

CAV
PRESIDENT, PUBLIC SERVICE COMMISSION-:-Write-In-:-NON
G
24
PSC

WRI
PROPOSED STATEWIDE AMENDMENT NUMBER ONE (1)-:-No-:-NON
PROPOSED STATEWIDE AMENDMENT NUMBER ONE (1)-:-Yes-:-NON
UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Barry Moore-:-REP
G

CON
01
MOO
UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Tom Holmes-:-DEM
G

CON
01
HOL
UNITED STATES REPRESENTATIVE, 1ST CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
01
WRI
UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Caroleene Dobson-:-REP
G

CON
02
DOB
UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Shomari Figures-:-DEM
G

CON
02
FIG
UNITED STATES REPRESENTATIVE, 2ND CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
02
WRI
UNITED STATES REPRESENTATIVE, 3RD CONGRESSIONAL DISTRICT-:-Mike Rogers-:-REP
G

CON
03
ROG
UNITED STATES REPRESENTATIVE, 3RD CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
03
WRI
UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Robert B. Aderholt-:-REP
G

CON
04
ADE
UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
04
WRI
UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Dale Strong-:-REP
G

CON
05
STR
UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
05
WRI
UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Elizabeth Anderson-:-DEM
G

CON
06
AND
UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Gary Palmer-:-REP
G

CON
06
PAL
UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
06
WRI
UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Robin Litaker-:-REP
G

CON
07
LIT
UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Terri A. Sewell-:-DEM
G

CON
07
SEW
UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON
G

CON
07
WRI

In [64]:
myKeys = list(race_updates_dict.values())
myKeys.sort()
sorted_dict = dict(sorted(race_updates_dict.items(), key=lambda x:x[1]))
export_dict = {i:key for key, i in sorted_dict.items()}

In [65]:
pd.DataFrame(export_dict.items()).to_csv("./field_names_gen.csv", index = False)

In [66]:
comb = comb2.copy(deep = True)

In [67]:
comb

pivot_col,"ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Chris McCool-:-REP","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 1-:-Write-In-:-NON","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Tommy Bryan-:-REP","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 2-:-Write-In-:-NON","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Will Sellers-:-REP","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 3-:-Write-In-:-NON","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Jay Mitchell-:-REP","ASSOCIATE JUSTICE OF THE SUPREME COURT, PLACE 4-:-Write-In-:-NON",CHIEF JUSTICE OF THE SUPREME COURT-:-Greg Griffin-:-DEM,CHIEF JUSTICE OF THE SUPREME COURT-:-Sarah Stewart-:-REP,...,"UNITED STATES REPRESENTATIVE, 4TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON","UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Dale Strong-:-REP","UNITED STATES REPRESENTATIVE, 5TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON","UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Elizabeth Anderson-:-DEM","UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Gary Palmer-:-REP","UNITED STATES REPRESENTATIVE, 6TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON","UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Robin Litaker-:-REP","UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Terri A. Sewell-:-DEM","UNITED STATES REPRESENTATIVE, 7TH CONGRESSIONAL DISTRICT-:-Write-In-:-NON",index
0,390.0,3.0,389.0,4.0,389.0,3.0,389.0,4.0,55.0,384.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ABSENTEE-:-Marion
1,241.0,0.0,241.0,0.0,241.0,0.0,240.0,1.0,10.0,240.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BACCUS UNION HALL-:-Marion
2,1047.0,8.0,1045.0,9.0,1046.0,8.0,1046.0,8.0,110.0,1021.0,...,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BEAR CREEK CITY HALL-:-Marion
3,629.0,1.0,629.0,1.0,628.0,0.0,627.0,0.0,51.0,628.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BRILLIANT COMM CTR-:-Marion
4,731.0,2.0,727.0,1.0,723.0,2.0,722.0,2.0,87.0,709.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BYRD VOTING CTR-:-Marion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,142.0,0.0,142.0,0.0,142.0,0.0,141.0,0.0,21.0,137.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,SRYGLEY CH OF CHRIST-:-Colbert
32,614.0,16.0,611.0,14.0,611.0,14.0,610.0,13.0,217.0,574.0,...,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TREE HOUSE SCH-:-Colbert
33,671.0,15.0,671.0,13.0,673.0,12.0,667.0,13.0,315.0,615.0,...,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TUSCUMBIA MULTI-PURPOSE-:-Colbert
34,537.0,7.0,536.0,8.0,536.0,6.0,537.0,4.0,115.0,518.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WESTSIDE BAPT_-:-Colbert
35,848.0,16.0,846.0,14.0,847.0,12.0,844.0,14.0,367.0,764.0,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WOODWARD AVE_ BAPT_-:-Colbert

In [68]:
myKeys = list(race_updates_dict.values())
myKeys.sort()
#sorted_dict = {myKeys: race_updates_dict[i] for i in myKeys}


sorted_dict = dict(sorted(race_updates_dict.items(), key=lambda x:x[1]))
comb.rename(columns = race_updates_dict, inplace = True)

In [69]:
comb

pivot_col,G24AJ1RMCC,G24AJ1OWRI,G24AJ2RBRY,G24AJ2OWRI,G24AJ3RSEL,G24AJ3OWRI,G24AJ4RMIT,G24AJ4OWRI,G24CFJDGRI,G24CFJRSTE,...,GCON04OWRI,GCON05RSTR,GCON05OWRI,GCON06DAND,GCON06RPAL,GCON06OWRI,GCON07RLIT,GCON07DSEW,GCON07OWRI,index
0,390.0,3.0,389.0,4.0,389.0,3.0,389.0,4.0,55.0,384.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ABSENTEE-:-Marion
1,241.0,0.0,241.0,0.0,241.0,0.0,240.0,1.0,10.0,240.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BACCUS UNION HALL-:-Marion
2,1047.0,8.0,1045.0,9.0,1046.0,8.0,1046.0,8.0,110.0,1021.0,...,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BEAR CREEK CITY HALL-:-Marion
3,629.0,1.0,629.0,1.0,628.0,0.0,627.0,0.0,51.0,628.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BRILLIANT COMM CTR-:-Marion
4,731.0,2.0,727.0,1.0,723.0,2.0,722.0,2.0,87.0,709.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BYRD VOTING CTR-:-Marion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,142.0,0.0,142.0,0.0,142.0,0.0,141.0,0.0,21.0,137.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,SRYGLEY CH OF CHRIST-:-Colbert
32,614.0,16.0,611.0,14.0,611.0,14.0,610.0,13.0,217.0,574.0,...,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TREE HOUSE SCH-:-Colbert
33,671.0,15.0,671.0,13.0,673.0,12.0,667.0,13.0,315.0,615.0,...,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TUSCUMBIA MULTI-PURPOSE-:-Colbert
34,537.0,7.0,536.0,8.0,536.0,6.0,537.0,4.0,115.0,518.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WESTSIDE BAPT_-:-Colbert
35,848.0,16.0,846.0,14.0,847.0,12.0,844.0,14.0,367.0,764.0,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WOODWARD AVE_ BAPT_-:-Colbert

In [70]:
comb = comb[["index"] + myKeys]

In [71]:
comb

pivot_col,index,G24A01NO,G24A01YES,G24AJ1OWRI,G24AJ1RMCC,G24AJ2OWRI,G24AJ2RBRY,G24AJ3OWRI,G24AJ3RSEL,G24AJ4OWRI,...,GCON04OWRI,GCON04RADE,GCON05OWRI,GCON05RSTR,GCON06DAND,GCON06OWRI,GCON06RPAL,GCON07DSEW,GCON07OWRI,GCON07RLIT
0,ABSENTEE-:-Marion,55.0,202.0,3.0,390.0,4.0,389.0,3.0,389.0,4.0,...,2.0,399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BACCUS UNION HALL-:-Marion,79.0,112.0,0.0,241.0,0.0,241.0,0.0,241.0,1.0,...,0.0,243.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BEAR CREEK CITY HALL-:-Marion,143.0,757.0,8.0,1047.0,9.0,1045.0,8.0,1046.0,8.0,...,15.0,1056.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BRILLIANT COMM CTR-:-Marion,125.0,387.0,1.0,629.0,1.0,629.0,0.0,628.0,0.0,...,2.0,636.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,BYRD VOTING CTR-:-Marion,145.0,437.0,2.0,731.0,1.0,727.0,2.0,723.0,2.0,...,5.0,744.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,SRYGLEY CH OF CHRIST-:-Colbert,21.0,103.0,0.0,142.0,0.0,142.0,0.0,142.0,0.0,...,5.0,142.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,TREE HOUSE SCH-:-Colbert,89.0,484.0,16.0,614.0,14.0,611.0,14.0,611.0,13.0,...,19.0,626.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,TUSCUMBIA MULTI-PURPOSE-:-Colbert,97.0,629.0,15.0,671.0,13.0,671.0,12.0,673.0,13.0,...,17.0,687.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,WESTSIDE BAPT_-:-Colbert,72.0,429.0,7.0,537.0,8.0,536.0,6.0,536.0,4.0,...,10.0,541.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,WOODWARD AVE_ BAPT_-:-Colbert,139.0,725.0,16.0,848.0,14.0,846.0,12.0,847.0,14.0,...,14.0,857.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [72]:
export_dict = {i:key for key, i in sorted_dict.items()}

In [73]:
pd.DataFrame(export_dict.items()).to_csv("./field_names.csv", index = False)

In [74]:
comb["County"] = comb["index"].apply(lambda x:x.split("-:-")[1])

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/3688505148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["County"] = comb["index"].apply(lambda x:x.split("-:-")[1])

In [75]:
comb.groupby("County").sum().to_csv("./al_county_totals.csv")

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/1310031185.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  comb.groupby("County").sum().to_csv("./al_county_totals.csv")

In [76]:
for i in list(sorted_dict.values()):
    comb[i] = comb[i].astype(int)
    print(i, sum(comb[i]))

G24A01NO 399640
G24A01YES 1159794
G24AJ1OWRI 38088
G24AJ1RMCC 1564832
G24AJ2OWRI 36383
G24AJ2RBRY 1560072
G24AJ3OWRI 35479
G24AJ3RSEL 1557606
G24AJ4OWRI 35034
G24AJ4RMIT 1555235
G24CFJDGRI 756675
G24CFJOWRI 2350
G24CFJRSTE 1458501
G24CR1OWRI 33207
G24CR1RMIN 1547401
G24CR2OWRI 32940
G24CR2RAND 1546549
G24CR3OWRI 32746
G24CR3RCOL 1547520
G24CV1OWRI 33716
G24CV1REDW 1555361
G24CV2OWRI 33644
G24CV2RHAN 1549864
G24CV3OWRI 33096
G24CV3RMOO 1551657
G24PREDHAR 772412
G24PREIKEN 12075
G24PREIOLI 4930
G24PREISTE 4319
G24PREOWRI 8738
G24PRERTRU 1462616
G24PSCOWRI 42061
G24PSCRCAV 1538888
GCON01DHOL 70929
GCON01OWRI 306
GCON01RMOO 258619
GCON02DFIG 158041
GCON02OWRI 219
GCON02RDOB 131414
GCON03OWRI 5160
GCON03RROG 243848
GCON04OWRI 3374
GCON04RADE 274498
GCON05OWRI 12088
GCON05RSTR 250322
GCON06DAND 102504
GCON06OWRI 380
GCON06RPAL 243741
GCON07DSEW 186723
GCON07OWRI 185
GCON07RLIT 106312

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/2293604008.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb[i] = comb[i].astype(int)

In [77]:
county = pd.read_csv("/Users/peterhorton/Documents/RDH/raw_data/census/PL_COUNTYFP_NAMES.csv")
al_cnty_fips_dict = dict((zip(county[county["STUSAB"]=="AL"]["NAME"],county[county["STUSAB"]=="AL"]["COUNTYFP"].astype(str).str.zfill(3))))

In [78]:
comb["Precinct"] = comb["index"].apply(lambda x: x.split("-:-")[0])

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/545608281.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["Precinct"] = comb["index"].apply(lambda x: x.split("-:-")[0])

In [79]:
comb["County"] = comb["index"].apply(lambda x: x.split("-:-")[1])

comb["County_map"] = comb["County"] + " County"

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/2491721802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["County"] = comb["index"].apply(lambda x: x.split("-:-")[1])
/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/2491721802.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["County_map"] = comb["County"] + " County"

In [80]:
comb["COUNTYFP"] = comb["County_map"].map(al_cnty_fips_dict).fillna(comb["County"])

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/3302747155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["COUNTYFP"] = comb["County_map"].map(al_cnty_fips_dict).fillna(comb["County"])

In [81]:
comb["index"] = comb["index"].apply(lambda x: x.split("-:-")[1]+"-:-"+x.split("-:-")[0])

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/3319974299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["index"] = comb["index"].apply(lambda x: x.split("-:-")[1]+"-:-"+x.split("-:-")[0])

In [82]:
comb.rename(columns = {"index":"UNIQUE_ID"}, inplace = True)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/3538977619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb.rename(columns = {"index":"UNIQUE_ID"}, inplace = True)

In [83]:
comb = comb[["UNIQUE_ID","COUNTYFP","County","Precinct"]+list(sorted_dict.values())]

In [84]:
comb["COUNTYFP"].unique()

array(['093', '063', '071', '091', '053', '077', '015', '099', '127',
       '049', '007', '043', '087', '131', '017', '111', '009', '045',
       '105', '039', '065', '085', '013', '123', '037', '107', '019',
       '081', '031', '029', '041', '069', '001', '119', '129', '083',
       '025', '047', '075', '073', '113', '003', '005', '125', '079',
       '057', '103', '115', '061', '101', '097', '023', '027', '117',
       '055', '035', '051', '089', '059', '095', '011', '121', '133',
       '021', '109', '067', '033'], dtype=object)

In [85]:
al_cnty_fips_dict

{'Autauga County': '001',
 'Baldwin County': '003',
 'Barbour County': '005',
 'Bibb County': '007',
 'Blount County': '009',
 'Bullock County': '011',
 'Butler County': '013',
 'Calhoun County': '015',
 'Chambers County': '017',
 'Cherokee County': '019',
 'Chilton County': '021',
 'Choctaw County': '023',
 'Clarke County': '025',
 'Clay County': '027',
 'Cleburne County': '029',
 'Coffee County': '031',
 'Colbert County': '033',
 'Conecuh County': '035',
 'Coosa County': '037',
 'Covington County': '039',
 'Crenshaw County': '041',
 'Cullman County': '043',
 'Dale County': '045',
 'Dallas County': '047',
 'DeKalb County': '049',
 'Elmore County': '051',
 'Escambia County': '053',
 'Etowah County': '055',
 'Fayette County': '057',
 'Franklin County': '059',
 'Geneva County': '061',
 'Greene County': '063',
 'Hale County': '065',
 'Henry County': '067',
 'Houston County': '069',
 'Jackson County': '071',
 'Jefferson County': '073',
 'Lamar County': '075',
 'Lauderdale County': '077',
 'Lawrence County': '079',
 'Lee County': '081',
 'Limestone County': '083',
 'Lowndes County': '085',
 'Macon County': '087',
 'Madison County': '089',
 'Marengo County': '091',
 'Marion County': '093',
 'Marshall County': '095',
 'Mobile County': '097',
 'Monroe County': '099',
 'Montgomery County': '101',
 'Morgan County': '103',
 'Perry County': '105',
 'Pickens County': '107',
 'Pike County': '109',
 'Randolph County': '111',
 'Russell County': '113',
 'St. Clair County': '115',
 'Shelby County': '117',
 'Sumter County': '119',
 'Talladega County': '121',
 'Tallapoosa County': '123',
 'Tuscaloosa County': '125',
 'Walker County': '127',
 'Washington County': '129',
 'Wilcox County': '131',
 'Winston County': '133'}

In [86]:
comb["COUNTYFP"].unique()

array(['093', '063', '071', '091', '053', '077', '015', '099', '127',
       '049', '007', '043', '087', '131', '017', '111', '009', '045',
       '105', '039', '065', '085', '013', '123', '037', '107', '019',
       '081', '031', '029', '041', '069', '001', '119', '129', '083',
       '025', '047', '075', '073', '113', '003', '005', '125', '079',
       '057', '103', '115', '061', '101', '097', '023', '027', '117',
       '055', '035', '051', '089', '059', '095', '011', '121', '133',
       '021', '109', '067', '033'], dtype=object)

In [87]:
comb["UNIQUE_ID"] = comb["COUNTYFP"] + "-:-" + comb["Precinct"]

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/303240413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb["UNIQUE_ID"] = comb["COUNTYFP"] + "-:-" + comb["Precinct"]

In [88]:
comb.sort_values(["COUNTYFP","Precinct"], inplace = True)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/2103180171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb.sort_values(["COUNTYFP","Precinct"], inplace = True)

In [89]:
comb.groupby("County").sum().to_csv("./prec_county_totals_gen.csv", index = True)

/var/folders/1t/0q4w6hm92mg_zxd84dfxmq3m0000gn/T/ipykernel_6180/2354233316.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  comb.groupby("County").sum().to_csv("./prec_county_totals_gen.csv", index = True)

In [90]:
import os

if not os.path.exists("./al_2024_gen_prec_csv"):
    os.mkdir("./al_2024_gen_prec_csv")

comb.to_csv("./al_2024_gen_prec_csv/al_2024_gen_prec_csv.csv", index = False)

In [ ]:
comb

In [91]:
import shutil

shutil.make_archive("./al_2024_gen_prec_csv/", "zip", "./al_2024_gen_prec_csv/")

'/Users/peterhorton/Documents/RDH/pber_local/AL_2024/general/al_2024_gen_prec_csv.zip'